### ISSUE TITLE
about rowid

### ISSUE THREAD

**Issue by jinchunhe** [free-jqgrid/jqGrid#100]
Why rowid change to 'grd1' this format?

as-is: grid.getRowData(1);
to-be:grid.getRowData('grd1');

**Comment by OlegKi** [comment]
You should provide the code and the test data which you use. You should additionally write always which version of free jqGrid you use (free jqGrid 4.8, free jqGrid 4.9 or the latest source from GitHub). I recommend you always post the demo if you report a problem which could be a bug.

It's important to understand that jqGrid **always** assign `id` attribute of the rows with data in the grid. So one **have to** provide the rowid information in the input data. Only if reading of the rowid failed then jqGrid have to generate unique rowid. The exact value depends on combination of other jqGrid options. Thus to be able to help you more I need to see the demo or to see `colModel`, `datatype`, `jsonReader`/`xmlReader`/`localReader` and probably some other options. The test data (2-3 rows of data) are required to analyse your problem.
