### ISSUE TITLE
Sort (asc/desc) indicator icon in front of column name

### ISSUE THREAD

**Issue by zoltan-fedor** [free-jqgrid/jqGrid#102]
Hi,
This is an enhancement request to have the option to re-position the sort (ascending/descending) indicating little arrow icons in the column head from after the column name to in front of the column name.

The reason for this request, that sometimes we have long column names, longer than the width of the column, so the last few characters might not be visible. Because currently the sort indicator icons are after the column name, they are basically invisible. By looking at the table you cannot tell which column is it sorted by.

This can be achieved today by adding a new line to jquery.jqgrid.src.js at line 4375 (https://github.com/free-jqgrid/jqGrid/blob/master/js/jquery.jqgrid.src.js#L4375):
`(p.builderSortIcons || jgrid.builderSortIcons).call(ts, iCol) +`  

Thanks,
Zoltan

**Comment by OlegKi** [comment]
Thank you for the idea and the description of the real situation where new feature could be helpful! I will analyse the problem and the way of its implementation and will post you my answer later (or will be just implement the feature).

**Comment by zoltan-fedor** [comment]
Thanks for the quick response, looking forward to your reply (or just to see the new functionality in an upcoming release).
My above change just makes the sorting icons to show up in front of the column names, if you implement, you probably want to make this optional (by some kind of a setting).

**Comment by OlegKi** [comment]
Try new jqGrid option `sortIconsBeforeText: true` which is implemented now in free jqGrid. Don't forget to use latest `jquery.jqgrid.src.js` (or `jquery.jqgrid.min.js`) **and** `ui.jqgrid.css`.

**Comment by zoltan-fedor** [comment]
Thanks Oleg, this is great. Let me test it (it might only happen tomorrow, sorry) and I will report back!
Thanks for the quick action!
