### ISSUE TITLE
Pivot - hide specific column or row

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#108]
If we want to hide the column (month 7, range: border black) or hide the column(year 2015, border green)
Is there any solution or jqGrid options that we can use it?
Thank you

![d](https://cloud.githubusercontent.com/assets/8980713/8425056/7f7549be-1f34-11e5-927e-d92193d19e89.jpg)

**Comment by OlegKi** [comment]
I find your question interesting and created the demo which demonstrates how one can set `hidden: true` property of some columns of the generated grid. I think that such question would be better to post on stackoverflow, because therein more people could find the solution by searching.

In any way I suggest you [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/pivotGroupingTotalsHideSomeColumns.htm) which hides columns having either `sellyear` equal to `"2015"` or having both `sellyear` equal to `"2011"` and at the same time `sellmonth` equal to `"7"`. The most important part of the corresponding code used in the demo I includes below:
```JavaScript
beforeInitGrid: function () {
    var $self = $(this), p = $self.jqGrid("getGridParam"),
        yItems = p.pivotOptions.yIndex.items, matches, iy, y,
        colModel = p.colModel, i, cm, l = colModel.length, cmName;

    for (i = 0; i < l; i++) {
        cm = colModel[i];
        cmName = cm.name;
        if (cmName.charAt(0) === "y") { // x, y, t
            // aggregation column
            matches = /^([x|y])(\d+)(t(\d+))?(a)?(\d+)/.exec(cmName);
            if (matches !== null && matches.length > 1) {
                // matches[2] - iy - index if y item
                // matches[4] - undefined or total group index
                // matches[6] - ia - aggregation index
                iy = parseInt(matches[2], 10);
                y = yItems[iy];
                if (y != null && (y[0] === "2015" || (y[0] === "2011" && y[1] === "7"))) {
                    cm.hidden = true;
                }
            }
        }
    }
}
```

**Comment by mrjumpy** [comment]
Thank you!
Do I need to post this issues to the stackoverfolw?

**Comment by OlegKi** [comment]
You are welcome! You can post the same question on the stackoverflow now or to do this next time.

**Comment by mrjumpy** [comment]
OK!
I post this issue to the stackoverflow!!
http://stackoverflow.com/questions/31181900/jqgrid-hide-specific-column-or-row-in-pivot

**Comment by mrjumpy** [comment]
hi Oleg, don't you want answer the question?
Or, you want me answer?

**Comment by OlegKi** [comment]
I don't forget about the post, but I have to do my main job too. :-) I posted [my answer](http://stackoverflow.com/a/31185944/315935) just now.

**Comment by mrjumpy** [comment]
Wow!!
that's awsome!
maybe I should post my question to stackoverflow next time.  XD

**Comment by OlegKi** [comment]
By the way hiding and collapsing/expanding of columns which you asked in one of your previously question consist mostly from adding `<span class="fa fa-fw fa fa-fw fa-plus-square-o"></span>`, changing `fa-plus-square-o` class to `fa-minus-square-o` on click and hiding some columns which names you can get by knowing the name conversions of the pivot grid. I have to do some other things now and I am in vocation for two next weeks. So I can't help you in the question. I hope that you can implement the feature yourself based on other information which I posted.
