### ISSUE TITLE
Custom text with headertitles

### ISSUE THREAD

**Issue by arrinmurr** [free-jqgrid/jqGrid#110]
Hi,

I wanted to have a custom title text on column headers, and found the `headertitles: true` option. However, this just displays the column name as the title. I then found several ways to set a custom title for headers, [such as described here](http://stackoverflow.com/a/4806615).

But I was wondering, could there be a colModel option to directly set the header title text, which would be used if headertitles is set to true? Something like:
```javascript
colModel : [
	{	name:        'id',
		index:       'id',
		headertitle: 'This is the id column.'
	}
]
```
The following line in the code

```javascript
tooltip = p.headertitles ? (" title=\"" + stripHtml(p.colNames[iCol]) + "\"") : "";
```

...could then be changed to something like the following to make it work (and maybe some other changes are also required?):
```javascript
tooltip = p.headertitles ? (" title=\"" + (cmi.headertitle ? stripHtml(cmi.headertitle) : stripHtml(p.colNames[iCol])) + "\"") : "";
```

But maybe there is a good reason why this shouldn't be done?

**Comment by OlegKi** [comment]
Thank you very much for your suggestion!

I find it very good and implemented with small changes. The name of new property of `colModel` is `headerTitle`. It can have boolean or string value. If boolean value `headerTitle: true` are specified in some columns then the tooltips will be created in the headers of the columns based `colNames[iCol]` (or `label` property which will be used only if no `colNames` is specified). The string value of `headerTitle` (like `headerTitle: "My custom column tooltip"`) corresponds your original suggestion.

The line of code with the changes looks like
```JavaScript
tooltip = p.headertitles || cmi.headerTitle ? (" title=\"" +
    stripHtml(typeof cmi.headerTitle === "string" ? cmi.headerTitle : p.colNames[iCol]) +
    "\"") : "";
```
See [the merge](https://github.com/free-jqgrid/jqGrid/commit/2725331f054ee2a79424024b33e63d7404aff7dd).

**Comment by arrinmurr** [comment]
Excellent, thank you!

**Comment by zoltan-fedor** [comment]
This is great!
Would it be possible to have the same headerTitle to show up in the columnChooser?
When users are selecting new columns to add to the display, it could be very beneficial for them to be able to read the headerTitle of the columns, so they know what they are adding to the grid.

Thanks

**Comment by OlegKi** [comment]
@zoltan-fedor It's a good idea! Thank you!

I implemented the feature too (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/2c9f88ad4b944cd518e5ba49b0d4b174a1a7909e)). Be careful, that I changed `ui.multiselect.js` file from `plugins` and `plugins\min` directories. One have to use modified version of `ui.multiselect.js` to display correct title.

I want to mention that there are exist `buildItemText` callback option in `columnChooser` described in [the answer](http://stackoverflow.com/a/29374787/315935). It allows to create custom text displayed in `columnChooser`. The option `headerTitle` will overwrite the default title, but not the text generated by `buildItemText` callback. So one can use both without any problem.

**Comment by zoltan-fedor** [comment]
Thanks Oleg, it does work!
Actually I already had an example where I tested it to ensure that it doesn't work before I raised it, which is based on the live versions on github, so now I can see how it started working.
See the hover-over text on the "Name" column both in the grid view and the columnchooser- view: http://broadcast-this.com/treegrid-4.9.0-raw.php
