### ISSUE TITLE
Pivot - total and subtotal position

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#114]
![image](https://cloud.githubusercontent.com/assets/8980713/8539788/29e7122e-24b2-11e5-8a17-565e6f04b6b2.png)
Hi Oleg:
If we want to change total just like the image below.
We want to bringing the total's position to the every column front.
(total | total | total | $ | bonus | season)
Is it possible?
Or I should implement this by myself?

**Comment by OlegKi** [comment]
I'm in vocation for two weeks now. I can't help you in the time. You can use remapColumnsByName to change column position.

**Comment by mrjumpy** [comment]
OK!
I'll give a try.
Enjoy your vacation!!

**Comment by mrjumpy** [comment]
Thank you Oleg!!
I can use remapColumnsByName  now,
but, can I reorder it at run time(at begin)?

**Comment by mrjumpy** [comment]
Because I think when the table become larger.
Using `remapColumnsByName`  will cause render again(it'll let user wait).

**Comment by mrjumpy** [comment]
I found a problem. It seems as same as this one.
http://www.trirand.com/blog/?page_id=393/help/problem-with-importing-remapcolumns-grid-option

Meanwhile, look the demo.
http://codepen.io/mrjumpy/pen/NqYoaJ?editors=001
In the line 74, I use `.remapColumnsByName(["x0", "x1", "y0a2"], true);`
I also tried `remapColumns`, it'll a error in the `e.cellIndex`.

I think these two questions are the same.
Since you're in vacation now, I don't want to bother you.
So I manage fix this by myself.
If there are any tips, please let me know.QQ

**Comment by mrjumpy** [comment]
Since I've made a little change.
It works now.

```
$.each(permutation, function (i) {
    var e = elems[this], oldElem = row.cells[i];
    try{
        if (e.cellIndex !== i){
            e.parentNode.insertBefore(e, oldElem);
        }
    }catch(e){}
});
```

in the `grid.base.js` line 5806
I don't pull request since I think maybe there are some bugs that I missing.
So, please take a look and tell me whether properly.

**Comment by OlegKi** [comment]
I read the post today and tried the demos which you included, but I didn't seen any error in  `remapColumns` (no error in the `e.cellIndex`). The current code don't have any additional `try{ ...} catch(e){}` block. Do you have an example which throws an exception? Thank you. Oleg
