### ISSUE TITLE
Possibility to have an autofill column

### ISSUE THREAD

**Issue by willemdewit** [free-jqgrid/jqGrid#115]
Is it possible to configure jqgrid in a way that the column widths are static and one column would fill up the available spacing?

Like in a simple table:

````
<table width="100%">
  <thead>
    <tr>
      <th width="200">Fixed width</th>
      <th width="100%">Auto fill the available width</th>
    </tr>
  </thead>
  <tbody>...</body>
</table>
````

Currently when `forceFit: true` the available width is divided over all the columns.

**Comment by OlegKi** [comment]
I am in vocation for two weeks, so I can't help you now. You can try to set fixed:true property in all columns with exception the last one and use autowidth:true option of jqgrid.

**Comment by willemdewit** [comment]
Thank you, it sure did help!
