### ISSUE TITLE
Treegrid - retrieving child rows when parent is expanded

### ISSUE THREAD

**Issue by john-w-watson** [free-jqgrid/jqGrid#118]
At 4.8 with datatype="json", jqGrid would load the top-level rows, and then as each row was expanded by the user, a separate request was made to the server to retrieve/load the children.  At 4.9, after the top-level rows are retrieved, the datatype is changed to "local", and no more data gets retrieved as the parent rows are expanded.  What is the correct way to dynamically retrieve/load child rows at 4.9?

**Comment by OlegKi** [comment]
I am in vocation this week and can try to help you next week. You should provide much more information what you do, which datatype you use, which format of server response you have. It's better if you prepare small demo which demonstrates what you do and what problem you have.

**Comment by john-w-watson** [comment]
Here is the server-side (VB.Net) prototype data generator:

    Function GetPrototypeData(nodeID As String, parentID As String, n_level As Integer) As String
        Dim ser As New System.Web.Script.Serialization.JavaScriptSerializer

        Dim ret As New List(Of Dictionary(Of String, Object))

        Dim level As Integer
        Dim parent As String
        Dim row As Dictionary(Of String, Object)
        Dim id As String
        Dim i As Integer

        If String.IsNullOrEmpty(nodeID) Then
            parent = ""
            level = 0
        Else
            parent = nodeID
            level = n_level + 1
        End If

        If (level = 0) Then
            For i = 1 To 5
                row = New Dictionary(Of String, Object)
                If (level = 0) Then
                    id = i.ToString()
                Else
                    id = parent & "." & i.ToString()
                End If
                row.Add("level", level)
                row.Add("parent", parent)
                row.Add("isLeaf", False)
                row.Add("expanded", False)
                row.Add("loaded", False)
                row.Add("id", id)
                row.Add("col1", id)
                row.Add("col2", "Test row " & id & "; col2")
                row.Add("col3", "Test row " & id & "; col3")
                row.Add("col4", "Test row " & id & "; col4")
                row.Add("col5", "Test row " & id & "; col5")
                row.Add("col6", "Test row " & id & "; col6")
                row.Add("col7", "Test row " & id & "; col7")
                row.Add("col8", "Test row " & id & "; col8")
                row.Add("col9", "Test row " & id & "; col9")
                row.Add("col10", "Test row " & id & "; col10")
                ret.Add(row)
            Next
        End If

        Return jsonSerialize(ret)
    End Function

Here is the jqGrid call:

            selfElem.jqGrid({
                datatype: "json",
                loadonce: false,
                mtype: "POST",
                colModel: this.options.columns,
                height: "auto",
                scroll: false,
                scrollOffset: global.environment.vscrollWidth,
                autowidth: true,
                shrinkToFit: false,
                treeGrid: true,
                treeGridModel: "adjacency",
                ExpandColumn: "col1",
                url: this.options.dataURL
            });

I can see in the debugger that after loading the top-level rows, jqGrid checks for loadonce or treegrid and changes the datatype to "local".

**Comment by john-w-watson** [comment]
I don't know if this will help you or not, but inside expandNode a test was added for p.datatype === "local" which now prevents a treegrid from getting to the "else" block where the p.datatype would be restored to p.treedatatype followed by the data request to the server.

**Comment by OlegKi** [comment]
Probably you are right and the reason of the reported problem is unneeded test for `p.datatype === "local"` in [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0/js/grid.treegrid.js#L337) of code. I have currently no working project which can be used to debug the changes. Could you replace the line
```JavaScript
if (p.datatype === "local" || base.isNodeLoaded.call($($t), p.data[position])) {
```
to
```JavaScript
if (base.isNodeLoaded.call($($t), p.data[position])) {
```
and verify that the problem would be fixed in the case?
Thank you.

**Comment by OlegKi** [comment]
I have time now to make some tests. The error was easy to fix. One should just replace `p.datatype === "local"` to `p.treedatatype === "local"`. I committed [the changes](https://github.com/free-jqgrid/jqGrid/commit/04c6094cc47886f465173b1c8091026d47139937) to the code on GitHub. Please try the latest code, confirm that it fix the problem and close the issue finally.

Thank you once more for reporting the issue.

**Comment by john-w-watson** [comment]
Thanks - fix works great!
