### ISSUE TITLE
FilterToolbar styling suggestion

### ISSUE THREAD

**Issue by smartcorestudio** [free-jqgrid/jqGrid#12]
Hi Oleg! You asked me to create a separate issue for this. Here it is.
If we have different column widths FilterToolbar looks inaccurate
![2015-02-22 09_21_40-http___stackoverflow com_a_20165553_315935](https://cloud.githubusercontent.com/assets/2891792/6317701/215e1992-ba75-11e4-92e0-f1f753b0740d.png)
I'd like that there were no extra padding (marked with red arrows on my screenshot) even for wide columns. All this is made via tables now. Maybe it's better to do this via CSS paddings and positioning?
Also, maybe it's better to replace "x" with "×" or an icon?

**Comment by OlegKi** [comment]
Please take a look in the current version of jqGrid. I will make some more changes later, but the gap between "x" and the right edge of the column should be eliminated now.

**Comment by smartcorestudio** [comment]
Thanks! It looks OK now

**Comment by OlegKi** [comment]
Could you close the issue after your all tests will be successful and you see the problem as solved. I can close the issue too, but I prefer the the person who reported the problem decide that it's solved. OK?

It would be very good if you try the latest version in other your test cases. I made many changes relative to free jqGrid 4.8. I tried to test all, but it's impossible in all different scenarios. Any remarks and suggestions are welcome. I plan to release free jqGrid 4.9 soon (after some tests and adding documentations). I will release 4.9 beta1 in the next days.

**Comment by smartcorestudio** [comment]
Thanks Oleg! I think this issue can be closed.
The only small thing I could mention regarding toolbar searching and migrating from Tony's jqGrid 4.7 to free jqgrid is the following:
```
      {name:'ownership', index:'ownership', edittype:'select', formatter:'select', stype:'select', editoptions: {value:{'':'ЛЮБАЯ','m':'Муниципальная','r':'Региональная','f':'Федеральная','p':'Частная'}}, editable:true},
```
This worked in 4.7, but in 4.8 and the latest dev versions it throws an error "TypeError: searchoptions is undefined". So I have to specify searchoptions with the same "values". Maybe it's OK and not an issue but I didn't find anything about this in the migration guide.

**Comment by OlegKi** [comment]
Thank you for the bug report! I posted [the corresponding bug fix](https://github.com/free-jqgrid/jqGrid/commit/81c470b49b4a42df2130109b97f230bef8ee2a7c).
Please post always bug report if you find something which not work as expected. If the problem is more complex then please include small demo which reproduce the problem. If I can reproduce the problem I fix it typically very quickly.
