### ISSUE TITLE
Github repository description and url

### ISSUE THREAD

**Issue by arrinmurr** [free-jqgrid/jqGrid#123]
This is just a minor thing, but the description and url of this Github repository still says "jQuery grid plugin http://www.trirand.com". This can be a little misleading for new users, since trirand.com is not the website for the fork. Can this be changed, or has it been left this way on purpose?

**Comment by OlegKi** [comment]
Thank you! It's fixed. See https://github.com/free-jqgrid/jqGrid

**Comment by arrinmurr** [comment]
Great!
