### ISSUE TITLE
stype: 'select' with searchoptions => dataUrl related bugs

### ISSUE THREAD

**Issue by zoltan-fedor** [free-jqgrid/jqGrid#124]
Hi,
I'm trying to switch over from an old version of jqGrid to 4.9.0 and found several issues withe the searchoptions => dataUrl.

When you have an stype:'select' type column where the list of values received from a url:
... stype:'select', searchoptions:{dataUrl: 'url'} ...  
  
- The generated "select" DOM object has no name or id 

- The generated "select" DOM object has no eventlistener on change, so when the user selects a different value nothing happens.

**Comment by OlegKi** [comment]
Do you tried free jqGrid 4.9.0 or 4.9.1? Very close bug is already fixed. Please confirm the version which you use.

**Comment by zoltan-fedor** [comment]
I have downloaded the actual code from this GitHub repo today, so I'm using the most recent code possible.

**Comment by OlegKi** [comment]
Could you post more detailed information, so I can reproduce the problem:
Is the problem exist in searching dialog or in searching toolbar?
Could you include an example of response from `dataUrl` and the full column definition which produce the error?

**Comment by zoltan-fedor** [comment]
It is searching toolbar. Okey, I try to create an example.

**Comment by zoltan-fedor** [comment]
here is the example: http://broadcast-this.com/jqgrid_test.php
See column "Name" - the search toolbar's drop-down's "select" DOM object doesn't have a name or id attribute, nor an event listener on "Change"

**Comment by OlegKi** [comment]
Thank for the demo and the bug report. I posted [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/73475a2359b53bb1f93f33866ba0d150c0f6e68d) just now. Your demo uses the code from GitHub and it works correctly now.

**Comment by zoltan-fedor** [comment]
Thanks Oleg for the quick fix!!!
