### ISSUE TITLE
Reloading treegrid data from url stops the ability to expand and collapse the levels

### ISSUE THREAD

**Issue by zoltan-fedor** [free-jqgrid/jqGrid#126]
Hey Oleg,
I'm afraid either I don't know how properly reload a treegrid's data or I might have found a bug.

I have a treegrid which I'm trying to reload with new data (the behavior is the same whether the data is actually any different than the old one or not) using : 
`jqGrid('setGridParam',{url: "data-reload2.json"});  
jQuery('#tree').trigger("reloadGrid");`

The treegrid does reload (the data changes), but the drill-down and drill-up options don't work anymore.
I guess some kind of data model refreshing issue.

I have a demo at http://broadcast-this.com/treegrid-4.9.1-reload.php
1. Open up the above url an try to drill down on "Citibank Global - Americas" - it will work
2. Then reload the data using the "Reload with different data" button
3. Try #1 again and you will see that it the drill-down doesn't work anymore. Also expanded nodes cannot be collapsed either.

The new data is the same as the old one except some titles changed to prove that the grid does actual change.
The issue can be reproduced even if the exact same (data-reload1.json) data file is being reloaded.

**Comment by OlegKi** [comment]
Thank you for reporting of the problem! The bug can be fixed by changing
```JavaScript
$self.unbind("jqGridBeforeSelectRow.setTreeNode", beforeSelectRow);
```
to
```JavaScript
$self.unbind("jqGridBeforeSelectRow.setTreeNode");
```
I will post the changes to GitHub soon. I have currently just some problems in cygwin after updating to Windows 10.
In any way I would recommend you to add `jQuery('#tree').jqGrid('clearGridData');` before using of `jQuery('#tree').trigger("reloadGrid");` in `reload_grid()`

**Comment by OlegKi** [comment]
I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/14a79f26cd44d2c37f6dcd71eda9d452a09fbf76). Please retry once more and think about calling of `clearGridData`. Thanks once more for reporting the bugs.

**Comment by zoltan-fedor** [comment]
Hi @OlegKi ,
Thanks for the quick fix. I can confirm that this has resolved the issue.
I have also added `jQuery('#tree').jqGrid('clearGridData');` as you suggested.
Thanks!
