### ISSUE TITLE
div appears on top of page when resizing columns

### ISSUE THREAD

**Issue by gelo32k** [free-jqgrid/jqGrid#128]
Hello Oleg,

My jqGrid is contained within a div (using jquery ui layout) and whenever I resize the jqgrid's column this huge div appears on the top of my page.

Screenshot:
http://i.imgur.com/3PwzNB6.png

Do you know any work around to hide this div without disabling the column resize?

Thanks,
~Gelo

**Comment by OlegKi** [comment]
@gelo32k : Thanks for reporting of the problem. **Could you provide the demo which reproduces the problem?**

Just for explanation: Position of resizer div as children of `<body>` is absolutely correct. It allows to resize column to the position *out of* the grid. The problem which you have is probably applying of some other CSS to the resizer div. For example it could be `float` or some other CSS rule which are applied and which makes problems. So it's important that you include *non-jqGrid CSS* which you use in the demo which reproduce the problem.

**Comment by gelo32k** [comment]
Ok thanks. I will try.

**Comment by gelo32k** [comment]
Hello Oleg,

I did what you asked me to do and I realized that my CSS is outdated.

Everything is fixed now.

Many Thanks,
~Gelo
