### ISSUE TITLE
Question about pagination after deleting a row.

### ISSUE THREAD

**Issue by nawglan** [free-jqgrid/jqGrid#132]
I have code that does something like this:
var grid = $jq('#grid');
grid.jqGrid('delRowData', id);
var grid_elt = grid.get(0);
grid_elt.rebuildRowIndexes();
grid_elt.refreshIndexes();
grid_elt.updatepager(false, false);
grid.trigger('reloadGrid');

The grid uses local data and has loadonce set.
After the delRowData, the row disappears as expected (verified by placing an alert after that line).
However, something is keeping the data around since by the time the code above finishes, the row reappears.

If I comment out the grid_elt and the reloadGrid parts, the row comes back if I page to the next page and then come back to original page.  Also, as soon as I page to next page, the number of items in the grid goes up by 1 indicating that the row has reappeared even though I can't see it since I am on a different page.

Is there something that I am doing wrong?  Is there a way to ensure that the item really is removed forever?

**Comment by OlegKi** [comment]
Could you provide the demo, which can be used to reproduce the problem?

**Comment by nawglan** [comment]
I will try, might take me a few days as I will be traveling through the weekend.

**Comment by nawglan** [comment]
Seems load once was the culprit.  If I comment out that config directive, the delete is preserved after paging.
