### ISSUE TITLE
Column Chooser CSS in IE Edge

### ISSUE THREAD

**Issue by mbraunwart** [free-jqgrid/jqGrid#135]
Hello!

I am having an issue where the height for the column chooser divs is set to auto in IE. In Chrome and Firefox the column chooser functions as expected. However, in IE Edge, having an auto height causes the column chooser height to auto configure to almost 1000px. I have the column chooser fixed to the middle of the screen which means the buttons extend past the bottom of the browser. I have tried to override the div size with css which has caused some success. However the scroll bar does not appear for the column list when there are more columns added that extend past the fixed height.

I will attach two pictures showing both scenarios. I hope there is a way I can resolve this issue with your help. Thanks!

Auto Height
![columnchooserheightauto](https://cloud.githubusercontent.com/assets/183024/9522790/964e4710-4ca4-11e5-8d1d-642c2c6778dd.PNG)

Overriden Fixed Height
![columnchooserheightfixed](https://cloud.githubusercontent.com/assets/183024/9522789/964d9e50-4ca4-11e5-9b4d-6470e2ab05c1.PNG)

**Comment by OlegKi** [comment]
Sorry, but you should provide more details. Which version of free jqGrid you use? Which version of jQuery and jQuery UI you use? Do you use all new jqGrid CSS files (`ui.jqgrid.css`, `plugins/ui.multiselect.css`)? With which options you calls `columnChooser`? Can you provide the demo which reproduces the problem? I tried to reproduce the problem on my Windows 10 computer, in my old demos, but I see no problems neither in Microsoft Edge nor in IE11 on Windows 10.

**Comment by mbraunwart** [comment]
Hello Oleg,

I am using free jq grid 4.9.1 and jQuery 1.11.3 and jQuery-UI 1.11.4. I am using the latest ui.multiselect.js and using all new jQuery css. I have a couple over overrides:

.ui-jqdialog {
    display: none;
    font-size: .8em;
    float: left;
    left: 35% !important;
    overflow: hidden;
    position: fixed !important;
    top: 30% !important;
    z-index: 200;
}

.ui-dialog-content {
	height: 265px !important;
}

.ui-pg-table {
    height: auto !important;
}

.ui-jqgrid .ui-jqgrid-htable th div {
    /* height: auto !important; */
    overflow: hidden;
    position: relative;
    padding-right: 4px;
    padding-top: 2px;
    vertical-align: text-top;
    white-space: normal !important;
}

.ui-jqgrid tr.jqgrow td {
    white-space: normal !important;
    padding-top: 8px !important;
    padding-bottom: 8px !important;
}

**Comment by mbraunwart** [comment]
Hello Oleg,

Upon further inspection, when I access the grid outside of the parent DOM in IE, I do not have that issue (I do not have that issue regardless in Chrome or Firefox). Sorry for my lame question, but it appears that I may be having some parent CSS issues. Do you know of a way that I can tell the column chooser css to ignore any parent css?

**Comment by OlegKi** [comment]
Hello mbraunwart,

sorry, but you should prevent the usage of `!important` if you define your custom rules. For example if you need to change `white-space` from `pre` to `normal` for cells of grid you should first search for `white-space` in `ui.jqgrid.css`. You will find some places in `ui.jqgrid.css` where `white-space` is specified and only one place where is till be specified for the cells of grid (other places define formatting of column headers or footers):
```JavaScript
.ui-jqgrid tr.jqgrow > td {
    white-space: pre;
}
```
See [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.9.2/css/ui.jqgrid.css#L287) of `ui.jqgrid.css`. So you can just include the same rule
```JavaScript
.ui-jqgrid tr.jqgrow > td {
    white-space: normal;
}
```
defiled **after** `ui.jqgrid.css` on your HTML page. No `!important` is required. In the same way you will find [another line](https://github.com/free-jqgrid/jqGrid/blob/v4.9.2/css/ui.jqgrid.css#L298) where the padding in the cell is defined. So you can replace the rule
```JavaScript
.ui-jqgrid tr.jqgrow td {
white-space: normal !important;
padding-top: 8px !important;
padding-bottom: 8px !important;
}
```
to the following
```JavaScript
.ui-jqgrid tr.jqgrow > td {
    white-space: normal;
    padding: 8px 2px 8px 2px;
}
```
In the same way you should analyse and implement all your requirements **without** using of `!important`.

The rules which you applied on `.ui-jqdialog` and especially on `.ui-dialog-content` were especially bad becuse the rules will be applied **all** jqGrid dialogs and jQuery UI dialogs. So you should never ever use such rules especially with `!important`.

**Comment by mbraunwart** [comment]
Thank you Oleg, I have adhered to your suggestions with my css, as well I have figured out my issue with the display and everything is working as expected!

**Comment by OlegKi** [comment]
Grate news! You are welcome!
