### ISSUE TITLE
JQGrid column resize after column data update

### ISSUE THREAD

**Issue by mkyadav** [free-jqgrid/jqGrid#139]
Hi,
I have to resize the column after column data update, but at the same time I want to preserve autofit toggle state, i.e when autofit is false the column should resize but in true state it shouldn't resize.

**Comment by OlegKi** [comment]
Sorry, mkyadav, but I don't understand your requirements. You wrote about resizing of column "after column data update". In which way you update the data? Do you reload the data, add new row or use some method like `setCell` to update existing data? You write additionally about "autofit toggle state". What you mean? Do you mean some option of jqGrid or some property of the column? Please be exact. You can include pictures or JavaScript code to clear what you need or what you do currently.

**Comment by mkyadav** [comment]
thanks .. issue resolved..

**Comment by OlegKi** [comment]
It's a good news! You are welcome! I close the issue in the case.
