### ISSUE TITLE
What Is The Difference To jsGrid

### ISSUE THREAD

**Issue by opticyclic** [free-jqgrid/jqGrid#140]
There is another jqgrid fork here https://github.com/openpsa/jsgrid?

Is one project a superset of the other or have you addressed different bugs with jqgrid?

See similar question https://github.com/openpsa/jsgrid/issues/128

**Comment by OlegKi** [comment]
[jsgrid](https://github.com/openpsa/jsgrid) is just one more fork of jqGrid. It's based on jqGrid 4.7 like free jqGrid too. The developers of the jsgrid started good alternative documentation site http://openpsa.github.io/jsgrid/. On the other side I implemented many new features compared with jqGrid 4.7, but the development of jsgrid seems to be stopped or it is very slow. You can see the description of the most features of free jqGrid in [the wiki](https://github.com/free-jqgrid/jqGrid/wiki) and readmes to the corresponding version which I published (see files READMExx.md). I plan to publish the documentation too, but the development for free is not so easy...

**Comment by opticyclic** [comment]
Thanks for the explanation.
Is free-jqgrid a superset of jsgrid then?
i.e. do you pull in fixes that are made there too?

**Comment by OlegKi** [comment]
You should better imagine the point of publishing jqGrid 4.7. After that there are no jqGrid more. There one way which goes Guriddo jqGrid JS, one more way goes jsgrid and the third way, independent from both other, goes free jqGrid. Of cause everybody can look in the changes made in another fork, but in general the development is absolutely independent. So one can't speak that one fork is a superset of another one. All forks are living independent from the common starting point jqGrid 4.7.

**Comment by OlegKi** [comment]
It seems to me that the question is answered. I am closing the issue. You can still reopen it later, whenever you want.
