### ISSUE TITLE
JqGrid maximum number of records supported

### ISSUE THREAD

**Issue by eppsaksh** [free-jqgrid/jqGrid#142]
Hi Oleg,

I am creating JqGrid without pagination & filtration.
What will be the maximum number of records it supports on single screen?

Thanks in advance.
eppsAksh

**Comment by OlegKi** [comment]
Hi eppsAksh,

there are no exact restrictions in jqGrid. The performance of jqGrid depends on many aspects. The large number of columns of the grid for example reduce the performance more as large number of rows. The performance of the grid in different web browsers is significant different. The performance of JavaScript itself and the processing of DOM in IE6 is very very slow comparing with the current version of Google Chrome. So I can't answer on your question formulated in the way. You should just measure the time. If you have some performance problems you can post the exact jqGrid code which you use. Especially the modification of all rows of the grid after filling of the grid (inside of `loadComplete` or `gridComplete`) can essential reduce the performance of the grid.

Best regards
Oleg

**Comment by OlegKi** [comment]
It seems to me that the question is cleared. So I close the issue. You can reopen it at any time later if you want.

**Comment by eppsaksh** [comment]
Hi Oleg,
Yes, Thanks for your help.

**Comment by OlegKi** [comment]
You are welcome!
