### ISSUE TITLE
Add v4.9.2 To Webjars

### ISSUE THREAD

**Issue by opticyclic** [free-jqgrid/jqGrid#143]
The version of free-jqgrid available on webjars is 4.9.1.
4.9.2 was released on 11 Aug so it would be nice to be able to use it via webjars

**Comment by OlegKi** [comment]
Sorry, but I don't publish free jqGrid myself on webjars. I publish on [jsDelivr](http://www.jsdelivr.com/projects/free-jqgrid), and [cdnjs](https://cdnjs.com/libraries/free-jqgrid) CDNs (see [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs)) and on [npm](https://www.npmjs.com/package/free-jqgrid) (see the [readme](https://github.com/free-jqgrid/jqGrid/blob/master/README.md)), [bower](http://bower.io/search/?q=free-jqgrid)  and [NuGet](https://www.nuget.org/packages/free-jqGrid). The [github](https://github.com/free-jqgrid/jqGrid) is the main source. If you find free jqGrid on some other source then it was not me who place it on the source. 

If webjars get automatically all packages published on jsDelivr, then the source should be soon refreshed.

**Comment by opticyclic** [comment]
I don't think that they get automatically published but anyone can add a webjar if there is already an npm or bower already published elsewhere.
Webjars will automatically get it from the CDN, convert it and deploy it to maven central via a form on their site.

I added the 4.9.2 jar to maven. I hope you don't mind.
The previous group was org.webjars.bower and I accidentally did the npm :(
I subsequently deployed via the bower artifact, the unfortunate result is that there are now 2 groups in maven central. 
org.webjars.bower
org.webjars.npm

Sorry!

**Comment by OlegKi** [comment]
I'm full agree that you added free jqGrid 4.9.2 to webjars. Thank you for this! I think that the more repositories hold the code the better for all users. I think that one can close the issue now.

Best regards
Oleg
