### ISSUE TITLE
Calling getGridParam('selarrrow') is returning undefined.

### ISSUE THREAD

**Issue by mbraunwart** [free-jqgrid/jqGrid#150]
Hello Oleg,

I have a subgrid with checkboxes. When I call $(subgrid).getGridParam("selarrrow") I am returned undefined.

When debugging this code is called for getGridParam

      var selectedRows = $("#tsSubGrid_" + rowId).getGridParam("selarrrow");

		getGridParam: function (pName) {
			var $t = this[0];
			if (!$t || !$t.grid) { return null; }
			if (!pName) { return $t.p; }
			return $t.p[pName] !== undefined ? $t.p[pName] : null;
		},

the !$t.grid is returning true, which is causing the process to return null when looking for the selarrrow attribute. Is there another suggested way to acquire the selected rows from a subgrid?

This method that I am using to acquire selected rows works fine for my standalone grid, but the same code is not working for my subgrid version. Any suggestions?

**Comment by OlegKi** [comment]
Sorry, but I'm not sure that I correctly understand your scenario. If you use grid as subgrid then you create jqGrid inside of the subgrid div. Every jqGrid have `grid` property assigned during initialization. So the `!$t.grid` can be `true` only if you try to use it not with the grid or *before the grid is created*.

If you have another case then please provide the demo which can be used to reproduce the problem.

**Comment by mbraunwart** [comment]
Hi Oleg, 

I don't really have a host to put up the demo, so I have created a demo and 7zipped it. Please let me know if you have any problems running it. I commented the part of the code where I am calling getGridParam and getting a t.grid returned null. 

In order to see the issue, load the demo.html. 

Expand the sub grid under the user name : amyf

select a few rows and click the shuffle (share tasks) icon

select a department/user and input a date.

click "ok", 

At the point of clicking "ok" it will then call the getSelectedRows(gridTag) function in the demo.js, this is the piece of code where it is breaking. I have made a comment notation in the code to point this out.

if i am in fact configuring this wrong, please provide me suggestions on how I should properly configure it. Also please note that the static data being loaded is not how this data is typically loaded, it is usually calling an mvc asp.net controller to return a JsonResult.

(will provide link for 7z file very shortly. will edit when am able.)

**Comment by OlegKi** [comment]
Sorry, but I have no access to the link which you posted. You can post me the data via email to oleg.kiriljuk@ok-soft-gmbh.com for example.
