### ISSUE TITLE
How to get jqGrid to 100% width even after resize of window

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#152]
In previous release, I can use width:null option to do this, but won't work anymore in latest version.

**Comment by OlegKi** [comment]
Which exactly "previous release" you mean? The type of the `width` parameter of jqGrid should be `number` and the value should corresponds the width of the grid in pixel. All other values of `width` parameter will be ignored. Old versions of jqGrid replace such `width` parameter to the total sum of width of all columns. So it's wrong that some old version of jqGrid of free jqGrid have special behavior in case of usage `width:null`.

If you need to implement auto-adjustment of the width of the grid on changing of the width of the window you need just set `resize` event handler on the `window` and call `setGridWidth` inside of it.

For example you can place the grid inside of some container
```html
<div class="container">
    <table id="grid"></table>
</div>
```
and to call `setGridWidth` with some value based on the width of outer container.
```JavaScript
var $grid = $("#grid");
// create the grid
$grid.jqGrid({
    ....
});
// set the handle
$(window).bind("resize.jqGrid", function () {
    $grid.jqGrid("setGridWidth", $grid.closest(".container").width());
}).triggerHandler("resize.jqGrid");
```
If you need to support old version of Internet Explorer (IE8 and lower version) then one need to include additional test to recursive calls of `resize` event handler, but it's pretty simple too.

The demo http://jsfiddle.net/OlegKi/andm1299/7/ demonstrates the scenario, but it combines the approach with Bootstrap classes and functionality. It allows to implement auto-hiding of not so important column (for mobile devices for example which have not so large resolution). One can use more simple implementation of `resize` event handle to set the grid width always equal to the width of the windows.

**Comment by ryanlin1986** [comment]
Thank you so much for the explaination, I got it, sometime it's inconvenient to register container's size change(not just windows size change), ResizeSensor lib comes to rescue.
