### ISSUE TITLE
Search does not work in sub grid. jquery.jqGrid.src.js line 9270 getGrid().p.guiStyle, p is undefined

### ISSUE THREAD

**Issue by mbraunwart** [free-jqgrid/jqGrid#153]
Hello Oleg, 

I spoke with you about a similar issue the other day that I was able to resolve. However this issue I am not able to resolve. Using the built-in option to add view, search, add, edit, and delete. Search does not function in a subgrid. Below is the code I am using to create the parent grid and it's subgrid. 

This is a different grid than the previous one I inquired about, this is more streamlined and less code and still uncertain what I am doing wrong for the subgrid to be missing the 'p' object.

I am using free-jqgrid 4.9.1 and jQuery 1.11.3

    $(document).ready(function () {

    var pickerOptions = {
        dateFormat: "mm/dd/yy",
        showAnim: "slideDown",
        duration: "slow",
        autoSize: true,
        changeYear: true,
        yearRange: "1980:2025",
        fixFocusIE: false,
        onSelect: function (dateText, inst) {
            this.fixFocusIE = true;
            $(this).change().focus();
        },
        onClose: function (dateText, inst) {
            this.fixFocusIE = true;
            this.focus();
        },
        beforeShow: function (input, inst) {
            var result = navigator.userAgent.indexOf("MSIE") !== -1 ||
                navigator.userAgent.indexOf("rv:11") !== -1 ? //Only for version 11, will need to add for version 12
                !this.fixFocusIE : true;
            this.fixFocusIE = false;
            return result;
        }
    };

    var colModel = [
        { name: "FileTaskID", index: "FileTaskID", hidden: true, hidedlg: true },
        { name: "SharedTaskCount", index: "SharedTaskCount", width: 75, searchoptions: { sopt: ["eq", "ge", "le"] } },
        { name: "TaskName", index: "TaskName", width: 200, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } },
        {
            name: "SharedTaskProjectedDate",
            index: "SharedTaskProjectedDate",
            width: 74,
            align: "center",
            formatter: "date",
            formatoptions: { srcformat: "m/d/Y", newformat: "m/d/Y" },
            searchoptions: {
                sopt: ["eq", "ge", "le"],
                dataInit: function(elem) {
                    $(elem).datepicker(pickerOptions);
                }
            }
        },
        { name: "AssignedToContactName", index: "AssignedToContactName", align: "center", width: 150, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } },
        { name: "AssignedToDepartmentName", index: "AssignedToDepartmentName", align: "center", width: 250, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } }
    ];

    var colNames = ["FileTaskID", "Shared Task Count", "Task", "Projected Date", "Assigned To User", "Assigned To Department"];

    var sgColModel = [
        { name: "SharedToContactName", index: "SharedToContactName", align: "center", width: 150, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } },
        { name: "SharedToDepartmentName", index: "SharedToDepartmentName", align: "center", width: 250, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } },
        {
            name: "SharedStartDate",
            index: "SharedStartDate",
            width: 74,
            align: "center",
            formatter: "date",
            formatoptions: { srcformat: "m/d/Y", newformat: "m/d/Y" },
            searchoptions: {
                sopt: ["eq", "ge", "le"],
                dataInit: function(elem) {
                    $(elem).datepicker(pickerOptions);
                }
            }
        },
        {
            name: "SharedEndDate",
            index: "SharedEndDate",
            width: 74,
            align: "center",
            formatter: "date",
            formatoptions: { srcformat: "m/d/Y", newformat: "m/d/Y" },
            searchoptions: {
                sopt: ["eq", "ge", "le"],
                dataInit: function(elem) {
                    $(elem).datepicker(pickerOptions);
                }
            }
        },
        { name: "SharedByContactName", index: "SharedByContactName", align: "center", width: 150, searchoptions: { sopt: ["eq", "bw", "ew", "cn"] } },
        { name: "SharedToUserID", index: "SharedToUserID", hidden: true, hidedlg: true },
        { name: "SharedToDepartmentID", index: "SharedToDepartmentID", hidden: true, hidedlg: true }
    ];

    var sgColNames = [
        "Shared To User", "Shared To Department", "Shared On", "Shared Expiration", "Shared By", "SharedToUserID", "SharedToDepartmentID"
    ];
    
    $("div.ui-datepicker").css({ fontSize: "12px" });

    var caption = "Shared Task Management";

    var stGrid = $("#sharedTaskGrid");

    stGrid.jqGrid({
        url: "/SharedTask/GetSharedTaskData",
        datatype: "json",
        colNames: colNames,
        colModel: colModel,
        viewrecords: true,
        pager: "#stPager",
        sortname: "TaskName",
        sortorder: "asc",
        gridview: true,
        caption: caption,
        altRows: true,
        altclass: "myAltRowClass",
        ignoreCase: true,
        loadtext: "Please hold, Loading Data...",
        loadui: "block",
        loadonce: false,
        toppager: true,
        rownumbers: true,
        rownumWidth: 25,
        subGrid: true,
        rowNum: 50,
        rowList: [50, 100, 200, 300],
        subGridRowExpanded: function (subgrid_id, row_id) {

            var rowData = stGrid.jqGrid("getRowData", row_id);
            var fileTaskId = rowData.FileTaskID;

            var subGridTable = $("<table id=\"" + subgrid_id + "\" class=\"scroll\"></table>");
            $("#" + subgrid_id).append(subGridTable);

            var subgridPager = "#SubPager_" + row_id;
            var subGrid = $("<div id=\"" + subgridPager + "\" class=\"scroll\"></div>");
            $("body").append(subGrid);

            subGridTable.jqGrid({
                url: "/SharedTask/GetDataByTask?fileTaskId=" + fileTaskId,
                datatype: "json",
                colModel: sgColModel,
                colNames: sgColNames,
                viewrecords: true,
                pager: subgridPager,
                sortname: "SharedEndDate",
                sortorder: "asc",
                gridview: true,
                caption: caption,
                altRows: true,
                altclass: "myAltRowClass",
                ignoreCase: true,
                loadtext: "Please hold, Loading Data...",
                loadui: "block",
                loadonce: false,
                toppager: true,
                rownumbers: true,
                rownumWidth: 25
            });

            var gridPager = "#" + subgrid_id + "_toppager";

            subGridTable.jqGrid("navGrid", gridPager, {
                search: true,
                view: true,
                del: false,
                edit: false,
                add: false,
                refresh: false,
                viewtitle: "Row Information",
                searchtitle: "Search Rows"
            },
            {}, //edit button
            {}, //add button
            {}, //del button
            { multipleSearch: true, showQuery: true, drag: false, closeAfterSearch: true, closeOnEscape: true }, //search button
            { width: "300", closeOnEscape: true }); //view button

            subGridTable.jqGrid("navButtonAdd", gridPager, {
                title: "Reload Task Summary",
                caption: "",
                buttonicon: "ui-icon-refresh",
                onClickButton: function () {
                    subGridTable.jqGrid().trigger("reloadGrid", [{ page: 1 }]);
                }
            });
        }
    });
    });

**Comment by OlegKi** [comment]
I see some clear errors in your code. I mention only two the most important.

The first error is the origin of the problem which you report: you use `gridPager` (the pager of the main grid) in subgrid instead of usage `subgridPager`. See the lines
```JavaScript
subGridTable.jqGrid("navGrid", gridPager, ...);
subGridTable.jqGrid("navButtonAdd", gridPager, {...});
```
The next important problem: you have to use `idPrefix` with unique value for subgrid. It prevents from problems with id duplicates. See [the answer](http://stackoverflow.com/a/31567652/315935) or many other my old answer about the subject (see [here](http://stackoverflow.com/search?tab=newest&q=user%3a315935%20%5bjqgrid%5d%20idPrefix%20subgrid)).

**Comment by mbraunwart** [comment]
Hello Oleg,

I have implemented your suggestion for the idprefix. As per using the `gridPager` variable instead of the `subGridPager`, the `gridPager` variable points at the subgrid's top pager. I am instantiating the `gridPager` point directly above where I am identifying the nav buttons. `var gridPager = "#" + subgrid_id + "_toppager";`

If my use of `gridPager` is incorrect in adding buttons to the toppager portion, please correct me on this issue as this is how I found it in [here](http://stackoverflow.com/a/3932314/139212)

**Comment by OlegKi** [comment]
Hallo mbraunwart,

could you provide **the demo** which can be used to reproduce the problem? Do you tried that the same problem exist with jqGrid 4.9.2 or with the latest sources of jqGrid from GitHub? See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs).

**Comment by OlegKi** [comment]
I looked in the code once more prepared the demo which uses your code. The reason of the reported problem is once more your error. You use the following code
```JavaScript
subGridRowExpanded: function (subgrid_id, row_id) {
    var rowData = stGrid.jqGrid("getRowData", row_id);
    var fileTaskId = rowData.FileTaskID;

    var subGridTable = $("<table id=\"" + subgrid_id + "\" class=\"scroll\"></table>");
    $("#" + subgrid_id).append(subGridTable);
```
where you interpret the first parameter of `subGridRowExpanded` as the id of subgrid. **It's wrong!**. jqGrid creates `<div>` element with the id and you can place in the div any information. If you want to create new grid then you can't use the same id. The id is already used by `<div>` element. So the code which you posted created id duplicates and **one will have subgrid `<table>` and the parent `<div>` with the same id**. See [the answer](http://stackoverflow.com/a/31567652/315935) which I posted you in my previous comment

You can fix the code using
```JavaScript
subGridRowExpanded: function (subgridDivId, rowid) {
    var $subgrid = $("<table id='" + subgridDivId + "_t'></table>");
        
    $("#" + subgridDivId).append($subgrid);
        
    $subgrid.jqGrid({
        ...
    });
    $subgrid.jqGrid("navGrid", {...}, ...);
```
In the code above I remove additionally creating bottom div for the pager. You don't use it at all. 
The demo http://jsfiddle.net/OlegKi/andm1299/12/ contains fixed code.

Free jqGrid allows to use `navGrid` and `navButtonAdd` **without the pager parameter**. jqGrid creates the navigator and the buttons on all (top and bottom) pagers. Moreover one can use `pager: true` option for the pager (in the main grid for example). One don't need to create empty `<div>` for the page and `pager` works close to `toppager: true` parameter. See [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/SMALL-improvements-in-the-usage-of-jqGrid#one-dont-need-to-create-div-idpagerdiv). It's important to mention that you can get the selector of the pager or toppager by usage of `.jqGrid("getGridParam", "pager")` and `.jqGrid("getGridParam", "toppager")`. Initial boolean value will be replaced to the id selector of pager/toppager.

**Comment by mbraunwart** [comment]
Hello Oleg,

I have sent you an email containing my demo. I am unsure at this point what I am doing differently than yourself. I have change my code to match yours and have added that to the demo attached in the email. I appreciate all the help you are providing.

**Comment by mbraunwart** [comment]
Please disregard the previous message, I saw the error in my code when applying the ID to the table. Thank you for all of your assistance!

**Comment by OlegKi** [comment]
You are welcome!
