### ISSUE TITLE
Is it a typo in README.MD?

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#16]
Hello, Oleg!
At the end of [this chapter](https://github.com/free-jqgrid/jqGrid#the-default-values-of-the-following-old-jqgrid-options-are-changed-comparing-with-jqgrid-47) there is an unclear phrase "The data". It is a typo?

**Comment by OlegKi** [comment]
Thank you! I fixed the text. I want to divide the readme in the parts in the next days, to move the most information in [the wiki](https://github.com/free-jqgrid/jqGrid/wiki) and to reduce the text of README.MD. The new version will be published very soon.

It would be fine if you try the current code and to post bug reports or any compatibility problems which you could find during integration of free jqGrid in your existing projects. I could fix the reported problems *before* publishing release 4.8 of free jqGrid.

**Comment by okadurin** [comment]
I see changes. Thank you.
