### ISSUE TITLE
Drop Down Filter Filtering

### ISSUE THREAD

**Issue by opticyclic** [free-jqgrid/jqGrid#160]
See the Selectize theme in this demo
http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview

Notice how if you type "lb" it filters (while you are typing and without pressing enter) to 
* A**lb**ania AL
* Lebanon **LB**
* Sva**lb**ard and Jan Mayan SJ

Is it possible to add this type of filtering to the jqGrid filters?

**Comment by OlegKi** [comment]
Yes, it's possible. I use select2 permanently in projects for my customers in combination with free jqGrid. [The demo](http://www.ok-soft-gmbh.com/jqGrid/UsageFormetterSelect2.htm) created for [the old answer](http://stackoverflow.com/a/19427444/315935) demonstrates the main way of the integration. The main idea is in initializing of `select2` inside of `dataInit` used in searching toolbar or in editing. The main problem is: customization of the width and height of the control. The exact options depend on the version of `select2` which one uses, but the results will looks like on the old demo which I referenced.

**Comment by OlegKi** [comment]
@opticyclic You didn't wrote any comment to my answer on your question and don't closed the issue. Is the problem is solved?

**Comment by opticyclic** [comment]
My apologies. The problem is solved. Thank you for your help and all your efforts on a great component!
