### ISSUE TITLE
dialog position bug

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#162]
When I press any of my action buttons on my grid the dialog popup opens lower and lower each time. Setting recreateForm to true fixes the issue. I'm using the current master.

**Comment by OlegKi** [comment]
Which code you use? Free jqGrid 4.9.2 or the latest code from GitHub? If the same problem exist with the latest code, please provide a small demo (please use URLs described [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)) of at least the code, which can be used to reproduce the problem.

**Comment by Gazoo** [comment]
Sure I just took one of the other jsfiddle demo's and was able to replicate it very easily:
http://jsfiddle.net/gwj8s41p/15/

Just press the add record button then close - repeat. You can see it get lower and lower with each repetition.

**Comment by OlegKi** [comment]
Thank you! I will analyse and fix the problem tomorrow. It's too late now in Germany :-)

**Comment by OlegKi** [comment]
I posted [the bug fix](https://github.com/free-jqgrid/jqGrid/commit/b39b0a39435170da0c96ffc5c8a6261a869520dd) just now. Your demo is working correctly now. Please test the latest code in other scenarios, which you could imagine, and close the issue. I hope that the latest changes don't produce new bug in some other scenario.

Thanks you once more for reporting the problem.

**Comment by Gazoo** [comment]
Your fix is working fine for all my grids now. Thanks again for all your hard work!

**Comment by Gazoo** [comment]
It looks like there are still issues with the dialog. If I use the actions for
matter and press the edit button on a row near the bottom of the page the dialog comes up at cut off at the bottom.

![bug](https://cloud.githubusercontent.com/assets/379016/10968006/c9846246-837b-11e5-8cb3-5b54e3ee313d.png)

**Comment by OlegKi** [comment]
To be exactly the web browser window will have **vertical scroll bar**. See the picture below

![scroll1](https://cloud.githubusercontent.com/assets/249117/10968281/89f426b2-83c0-11e5-8993-84fa504a88e2.png)

If the mouse have scroll-rad then the user scould need to scroll the window till the whole dialog will be seen. One can do vertical scrolling without scroll-rad of cause too.

I see that it's new problem and it would be better to open new question instead of reopening the old issue. Moreover I see the problem not as a bug. You can use `afterShowForm` callback for example to change the position of the dialog or ot scroll the window till the dialog will be visible.

[The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/inlineEditingOnDoubleClick1.htm) uses jQuery UI position method to prevent the problem which you describe. It's just an example of implementation. It uses simple callback:
```JavaScript
afterShowForm: function ($form) {
	$form.closest(".ui-jqdialog").position({
		of: $(this).jqGrid("getGridRowById", $("#id_g").val()),
		my: "left top",
		at: "left bottom",
		collision: "flipfit flipfit"
	});
}
```
You can see that the described problem is not exist in the demo. You can use any other code to customize the position of the dialog.

**Comment by Gazoo** [comment]
Thanks for the demo. I will take a look at the fix. I think most of these problems are because of the re-
use of the dialog window. I'm just coming from jqgrid over from the free version so I wanted to document issues that users might experience. I'm including an animated gif of the dialog re-use issue. As you can see that once a dialog is opened at the bottom all future dialogs open at the bottom instead of next to their respective edit button. 
![bug2](https://cloud.githubusercontent.com/assets/379016/10969033/ee105050-8382-11e5-9c3c-0444e5969177.gif)

**Comment by OlegKi** [comment]
Sorry, but [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/inlineEditingOnDoubleClick1.htm), which I posted don't have the problem. Every time the dialog will set the position based on the currently clicked row. It seems that you made some customizations of the form editing or `formatter: "actions"`, but I can't help you having the gif only. I recommend you to examine the code of my demo and to compare it with you code.

**Comment by Gazoo** [comment]
There was no customization. All that was done was set: formatoptions to: 'editformbutton' => TRUE, 'delbutton'      => FALSE,

**Comment by OlegKi** [comment]
I just get [old demo](http://www.ok-soft-gmbh.com/jqGrid/OK/inlineEditingOnDoubleClick.htm) and added to it `afterShowForm`. You can verify the old demo that the problem which you explain don't exist. I created the same demo as FSfiddle too: http://jsfiddle.net/OlegKi/e31h9bv1/

You can make any modification in the code yorself to reproduce the problem which you describe. I can't reproduce the problem.

**Comment by Gazoo** [comment]
Yes I'm having trouble replicating it also. I'll try and see what else could be causing the issue and report back.

**Comment by Gazoo** [comment]
I was able to replicate it. Setting a default width using a full grid in jqgrid editoptions triggers the issue.

Example: editOptions: { "width" : "640" },
See: http://jsfiddle.net/gwj8s41p/19/

Click on a bottom edit first then click on a top edit second.

**Comment by OlegKi** [comment]
Thank you for the bug report. I have fixed the problem. Nevertheless I would recommend you to use **another style** of usage options of jqGrid methods. See  http://jsfiddle.net/OlegKi/gwj8s41p/21/ and the wiki article https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods

**Comment by Gazoo** [comment]
I'll definitely look at using your afterShowForm example to re-position the dialog and the new style of usage options of internal methods looks much better. Thanks again.
