### ISSUE TITLE
wrapped icon

### ISSUE THREAD

**Issue by chenster** [free-jqgrid/jqGrid#166]
I noticed the new change in the free jqgrid to allow wrapping of footer icons in multiple lines. That's great for responsive layout. However, is it possible to turn that option off in jqGrid property?  I figured out I can do that with the following CSS, but I much prefer do it in API. 

div.ui-pager-control table > tbody > tr { white-space: nowrap; }

**Comment by OlegKi** [comment]
Sorry, @chenster , but what you suggest? Or what is your question? Do you suggest to introduce some new option which sets `white-space: nowrap` or something else? **It would be helpful if you included two screenshots with the look of grid: first one with the default free jqGrid settings and another one with your additional CSS rule.**

I described the problems in the pager of old versions of jqGrid in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Redesign-of-the-structure-of-Navigator-Bar-of-the-pagers). I don't understand some advantage of the pager like
![no-wrap](https://cloud.githubusercontent.com/assets/249117/10862822/089c1bac-7fb9-11e5-83c1-d49d822f2c2a.png)
I don't think that such kind of displaying the buttons can be good in any scenario.

What I think could be probably helpful, would be the new option, which can *restrict the minimal width* of the grid: `minWidth`. I think either one should don't include so much icons or one should don't 

By the way, if one uses `gridResize` method, then one can use `minWidth` and `minHeight` options, which **prevents** that the user makes too small width or height of the grid during resizing. In the same way, if one use the code like in [the answer](http://stackoverflow.com/a/25036623/315935) for example, to make jqGrid responsive (see [the demo](http://jsfiddle.net/OlegKi/andm1299/8/) additionally), then one can easy modify the code to reduce setting of to small value for the with of the grid:
```JavaScript
$(window).on("resize", function () {
    var $grid = $("#list"),
        newWidth = $grid.closest(".ui-jqgrid").parent().width();
    if (newWidth >= 800) { // !!! 800 is the minimal size of grid
        $grid.jqGrid("setGridWidth", newWidth, true);
    }
});
```
Thus I come back to the questions and suggestions from the begin of my comment. Please insert screenshots, which shows how the CSS rule, which you suggested, helps in some grids. Please describe more detailed, what is the substance of your suggestion. What you suggest to do (to introduce) in free jqGrid to improve its visibility in case of usage many navigator icons?

**Comment by OlegKi** [comment]
@chenster : The issue is still opened. Have you some progress in your investigation? Do you have some additional questions to my answer?
