### ISSUE TITLE
Wrapped footer icon

### ISSUE THREAD

**Issue by chenster** [free-jqgrid/jqGrid#168]
Since version 4.8 it allows wrapping of footer icons in multiple lines when the grid width is small. I figured out I can do that with the following CSS, but is it possible to turn that option off in jqGrid property? 

`div.ui-pager-control table > tbody > tr {
    white-space: nowrap;
}`

**Comment by OlegKi** [comment]
Sorry, but it seems be exact dupplicate of [another issue](https://github.com/free-jqgrid/jqGrid/issues/166) which you posted two days ago. I [answerd the post](https://github.com/free-jqgrid/jqGrid/issues/166#issuecomment-152718711). Please continue the discussion on the previous issue. I closeing the dupplicate.
