### ISSUE TITLE
addChildNode does not always add

### ISSUE THREAD

**Issue by ricohumme** [free-jqgrid/jqGrid#169]
When I add elements using addChildNode where there is a parent child relationship, the element is not added when that element is a not a leaf.

when I put the following lines in comment: (in section addChildNode) around line 16480
```javascript
//if (parentid === null || base.isNodeLoaded.call($self, parentdata) || leaf) {
  base.addRowData.call($self, nodeid, data, method, rowind);
  base.setTreeNode.call($self, i, len);
//}
```
The result I expect is achieved

**Comment by OlegKi** [comment]
Sorry, but I don't find the lines of code. Which version of free jqGrid you use? Please retry with the latest version of free jqGrid by including `jquery.jqgrid.src.js`, `ui.jqgrid.css` and optionally `grid.locale-XX.js` directly from GitHud. See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit). I recommend you to use in production URLs to cdnjs or jsDelivr CDN.

**Comment by ricohumme** [comment]
The version at the top says 4.10.1-pre.
Im using the non minified version in my development environment

**Comment by OlegKi** [comment]
Sorry I'm now not on my main computer and I tried to open `jquery.jqgrid.src.js` on GitHub, but the lines was cut. What you mean are [the lines](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.treegrid.js#L596-L599) of `grid.treegrid.js` which will be placed in `jquery.jqgrid.src.js` during building process.

I could examine the problem one day later. Could you describe me more what you do? How you use TreeGrid? In which scenario you use `addChildNode`. The total code of jqGrid is large enough and I need some time in analyzing all cases of usage before making modification in the code. The final test (after the changes) is required too after making the changes. Thus one really need to have small demo for every change of the code.

I'm not sure, what you do in your code. Do you add top level node or a node in the middle? **Is `loaded` property set in the added node?**

**Comment by ricohumme** [comment]
I just added tree_loaded as property in the colModel and now it works :+1: 
Thanks for clearing that up for me :)
