### ISSUE TITLE
Question on how to do a local search with formatter

### ISSUE THREAD

**Issue by salimnanji** [free-jqgrid/jqGrid#171]
Hi There Oleg, just a question I can't find a recent answer (can only find responses from a few years ago)

When I try to do a search on a column with a local data set, searching will filter the original values instead of the filtered values. I tried using a unformatter, but found out that had nothing to do with the search.

I use a custom formatter across the project, in one example we do the following conversions with our formatter:
-0.005140476 --> (0.51)%
0.004416212 --> 0.44%
-0.003878925 --> (0.39)%

But I would like to have it so that if I type in 0.44, the formatted values will show up. I would have to type in the raw data exactly to get it to show up currently. Any idea how? Using sorttype: 'float' for the column as well

**Comment by OlegKi** [comment]
First of all I hope you use `datatype: "local"` or `loadonce: true` (which changes `datatype` to `"local"` after the first loading). Only in the case the filtering of data will be done by jqGrid.

To be able to filter by `0.44` jqGrid have to interpret the number `.004416212` saved in the data as `0.44`.

The most easy way to do this **during sorting** would be implementing `sorttype` as function, It could look like
```JavaScript
sorttype: function (cellValue) {
    return (Math.round(parseFloat(cellValue)*10000)/100;
}
```
**To filter** the data you have the following options (alternatives):
 1. modify the local `data` of jqGrid using `(Math.round(parseFloat(cellValue)*10000)/100`. Thus `0.004416212` and `-0.005140476` would be saved as `0.44` and `-0.51`, the custom formatter will be easier and you should have no problems with filtering.
 2. You can use custom filtering feature of free jqGrid. See [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Custom-filtering-searching-Operation) and [the answer](http://stackoverflow.com/a/29415927/315935).

I will consider to make some changes in the code of free jqGrid to allow to use callback function during filtering. Probably just calling `sorttype` if it is defined.

**Comment by OlegKi** [comment]
I thought a little more about the implementation of your scenario in case of usage `datatype: "local"` and found out that the usage of `jsonmap` could give the most simple implementation.

[**The demo**](http://www.ok-soft-gmbh.com/jqGrid/OK/customFilter.htm) uses the input data, which have `t` property with values `-0.005140476`, `0.004416212`, `-0.003878925` and so on. The column `t` in `colModel` uses the following properties:
```JavaScript
sorttype: "number",
jsonmap: function (item) {
    return isNaN(item.t) ? 0 : Math.round(parseFloat(item.t)*10000)/100;
},
formatter: function (value) {
    var v = isNaN(value) ? 0 : Number(value);
    return v < 0 ? "(" + (-v) + ")%" : v + "%";
}
```
As the result the data will be displayed in the same way like you do, but the input data will be **converted** and rounded **before** filtering and before formatting. One still use original input data during sorting. One can add
```JavaScript
sorttype: function (cellValue) {
    var v = isNaN(value) ? 0 : Number(value);
    return (Math.round(v*10000)/100;
}
```
additionally to use rounded values during sorting too.

**Comment by OlegKi** [comment]
The issue is still opened. Do you tried the demo from my previous comment? I didn't get any answer from you till now.

**Comment by salimnanji** [comment]
Still have not gone around to trying this out. I can close this for now as I'm not sure when I'll be able to test this.

Thanks.

**Comment by OlegKi** [comment]
You can reopen any old issue at any time. You are welcome!
