### ISSUE TITLE
Inconsistent naming of row ID and data objects

### ISSUE THREAD

**Issue by dkrey** [free-jqgrid/jqGrid#174]
when using `actionsNavOptions` the row id can accessed via `options.rowid`. But in `isDisplayButtons` the row ID is accessed via options.rowId (capital i ).
Console log output for `isDisplayButtons`:
```
baseLinkUrl : "" 
checkbox : Object
colModel : Object
currency : Object
date : Object
gid : "build_grid" 
idName : "id" 
integer : Object
number : Object
pos : 10
rowData : Object
rowId : "141" 
showAction : "" 
target : "" 
unused : "" 
__proto__ : Object
```

Console log output for `actionsNavOptions custom action onclick`:
```
action: "edit_build"
event: MouseEvent
options: Object
rowid: "204"
__proto__: Object
```

It would be great if actionsNavOptions could have the same options object as isDisplayButtons. Especially accessing the rowData directly instead of `jqGrid('getCell',options.rowid,"status_id");` would be very convenient.
But for starters it would be nice if the naming style of row ID would be consistent.

**Comment by OlegKi** [comment]
I understand the problem, but one have to decide between the **compatibility** and the common naming concept. jqGrid have a lot of places where the names are not good, but there are exist many *exiting old code*, which uses the names. I try to follow common naming concept mostly in new events/callbacks. `onClick` callback of the custom button contains **one parameter**, which contains all options as properties of the object. It's new style which I try to follow. See [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.10.0/js/jquery.fmatter.js#L670) of the code. It's the place where I try to hold common naming concept.

On the other side, the callback `isDisplayButtons` is new too, but it *forwards* just the parameters of formatter to `isDisplayButtons` to have the most information, without writing large wrapping code. Look at [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.10.0/js/jquery.fmatter.js#L732) and compare it with the options of the formatter (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.10.0/js/jquery.fmatter.js#L680)). The format of `opts`, `rwd` and `act` is old and it come from previous version of jqGrid. I could of cause wrap all parameters of `opts`, the `rwd` and `act` in new object with another names of properties, but I thought, that the format is already known by developer who wrote [custom formatter](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:custom_formatter) before.

Thus if you see a callback or event with **one parameter** then you should expect new naming concept (see [here](https://github.com/free-jqgrid/jqGrid/wiki/New-callbacks-and-jQuery-events#design-changes-in-callbacks-and-jquery-events-in-free-jqgrid-48)). On the other side, the callback with multiple options is old or it extend/forward old jqGrid structures. I don't want to change the structures to have better compatibility with the old code created for old jqGrid versions.

**Comment by dkrey** [comment]
Okay, thanks for clarification. I was just a little concerned that I'd need to refactor all my grids to one or another spelling type. Still it's all a bit of a guessing game logging the objects and see of things are named ;)
