### ISSUE TITLE
Cannot set mtype to POST for delete action

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#179]
I just updated to v4.11.0 and now all my grid delete actions are using GET instead of POST. Previously the grid could use GET for listing and POST for delete actions. I tried setting mtype to POST in the new formEditing and delOptions but it doesn't look like that works. Any ideas?

**Comment by OlegKi** [comment]
Thank you for reporting the bug! One line was erroneously removed from the code of `delGridRow`. It was a typing error. I posted [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/dc8e21edfc1e162f1321950d925b479760360ad0) to GitHub. Please reload your sources.

I will wait for reporting of other possible bugs and will publish v4.11.1 this week.

**Comment by Gazoo** [comment]
Thanks for the quick fix :)

**Comment by OlegKi** [comment]
No other bugs was reported in free jqGrid till now.

I have published free jqGrid v4.11.1 just now. It includes the bug fix.
