### ISSUE TITLE
IE9: empty grid width

### ISSUE THREAD

**Issue by Yagg** [free-jqgrid/jqGrid#182]
Let's start with the simple example: http://jsfiddle.net/0157w1Lq/3/
All is working fine for all browsers, except IE9. Under IE9 Jsfiddle is not working so I had prepared the same example placed at Dropbox: https://dl.dropboxusercontent.com/u/15187698/jqGrid/testEmpty.xhtml
**Under IE9 grid width is changing when I click on the button.** Compare with the same grid but with data: https://dl.dropboxusercontent.com/u/15187698/jqGrid/test.xhtml

**Comment by OlegKi** [comment]
Thank you for the bug report! It seems to me that the problem could be solved by adding CSS rule
```css
.ui-jqgrid .ui-jqgrid-bdiv {
	min-height: 1px;
}
```
I posted the fix [here](https://github.com/free-jqgrid/jqGrid/commit/b794a5747a7cb296a91be7c44fcb4862988d0889). Now the demo http://jsfiddle.net/OlegKi/0157w1Lq/4/ seems to work correctly.

**Comment by Yagg** [comment]
Yes, this fix solves the problem. Thank you.
