### ISSUE TITLE
focusField sets focus to tabindex=-1 element in inline edit

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#186]
If focusField: true is used, custom element contining tabindex=-1 button is in first column  and inline edit starts, focus is set to this element.

Elements with tabindex=-1 should not receive focus on editing.

Source code contains

	getFocusable = function (elem) {
			return $(elem).find("input,textarea,select,button,object,*[tabindex]")
         .filter(":input:visible:not(:disabled)");

So jqgrid puts focus  to element even if it contains `tabindex=-1`

To reproduce, create first column as Jquery UI autocomplete dropdown using custom edit type.
Made it  focusable using `focusField: true`

    $.extend(true,$.jgrid.inlineEdit, {
        position: "beforeSelected",
        focusField: true,
        keys: true } );

In jquery ui autocomplete dropdown autocomplete button is defined with tabindex=-1:

    <button type='button' class='btn btn-default btn-form-dropdown' tabindex=-1 aria-label='Open menu'>
    <span class='caret'></span></button>

It does not receive focus if tab key is pressed in inline edit.

If inline editing is started, jqgrid puts focus to autocomplete dropdown button.
Instead focus should put to autocomplete input element.

Posted also in http://stackoverflow.com/questions/34255210/how-to-set-focus-to-autocomplete-contents-on-inline-edit-in-free-jqgrid

**Comment by OlegKi** [comment]
I don't think that it's a bug of free jqGrid. I posted detailed answer on your question on the stackoverflow. Setting of `tabindex=-1` attribute do informs to make the element focusable, but one want to exclude it from *sequential focus navigation* (by <kbd>Tab</kbd> or <kbd>Shift+Tab</kbd>). See HTML5 specification [here](http://dev.w3.org/html5/spec-preview/editing.html#attr-tabindex) or to be exactly [here](http://dev.w3.org/html5/spec-preview/editing.html#negative-tabindex).

You can still change `focusField: true` option to some other integer or string value to set the focus on *some another column* addressed by column index or by column name.

**Comment by kobruleht** [comment]
For rapid data entry, input element in first column shoud focused, not button. Focus needs to be set to first column input element, not to other column.  

focusField does not support any way to specify element which should receive focus inside column. I updated answer in SO

**Comment by OlegKi** [comment]
Sorry, I don't understand what you want to implement. Either you should set the focus yourself in your code or to specify the column, which should get the focus. If you just use `focusField: true` then the focus will be set on the first focusable element. Focusable element is **not only <input>** element. If could be button, textarea, select, object or even any other element which are explicitly marked as focusable by adding `tabindex` attribute (even with negative value). One can for example use `<span calss="fa fa-floppy-o" tabindex="-1"/>` to crate focusable "Save" button.

You can't just write:
>input element in first column should focused, not button

I can't change the code of free jqGrid corresponds your current requirements. You can any time use `focusField: false` and to set the focus yourself corresponds your custom requirements of the project.
