### ISSUE TITLE
Cannot read property 'addRowData' of undefined trying to upgrade to 4.8.0

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#19]
Application using 4.6.0. contains code from http://stackoverflow.com/questions/8517988/how-to-add-new-row-in-jqgrid-in-middle-of-grid to fix 4.6.0 issue

```javascript
var oldAddRowData = $.fn.jqGrid.addRowData;
    $.jgrid.extend({
        addRowData: function (rowid, rdata, pos, src) {
            if (pos === 'afterSelected' || pos === 'beforeSelected') {
                if (typeof src === 'undefined' && this[0].p.selrow !== null) {
                    src = this[0].p.selrow;
                    pos = (pos === "afterSelected") ? 'after' : 'before';
                } else {
                    pos = (pos === "afterSelected") ? 'last' : 'first';
                }
            }
            return oldAddRowData.call(this, rowid, rdata, pos, src);
        }
    });
```

If jquery.jqgrid.src.js from git master is used, first line 

`var oldAddRowData = $.fn.jqGrid.addRowData;`

causes error in browser

`Cannot read property 'addRowData' of undefined `

Is this fix already included and is it safe to remove this code ? Or how to apply this fix ?

**Comment by OlegKi** [comment]
Sorry, but I can't reproduce the problem. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/AddRowAfterSelected.htm) uses the code and I can't get the described error.

In any way I will add the option `"afterSelected"` and `"beforeSelected"` to the main code of `addRowData`.

**Comment by OlegKi** [comment]
You can use the above code with free jqGrid 4.8 if you get it from CDN (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs)). If you use standalone version of free jqGrid you can just download the current build of jqGrid. I uploaded just now (see [here](https://github.com/free-jqgrid/jqGrid/commit/cff6aedbc40e3b908f415c825c4dffddca9a87af)) the modification of `addRowData` method. Thus the position values `"afterSelected"` and `"beforeSelected"` are supported in the main code of free jqGrid.

**Comment by kobruleht** [comment]
I'm using https://github.com/free-jqgrid/jqGrid/blob/master/jquery.jqgrid.js
This file does not contain this change.
