### ISSUE TITLE
Multisort not maintaining column order

### ISSUE THREAD

**Issue by ivcoder** [free-jqgrid/jqGrid#191]
This nasty bug still exists in free-jqgrid
https://github.com/tonytomov/jqGrid/issues/583

demo for free-jqgrid:
http://jsfiddle.net/1fj1tp8b/

Click on "Number" column, then on "Thingy" column. Grid is sorted by "Thingy" first and by "Number" second. It has to be sorted by "Number" first and by "Thingy" second.

**Comment by OlegKi** [comment]
Thank you for the bug report! I'll examine the problem and will post the bug fix in the next days (after the Christmas). I will post you the new comment after posing the fix.

**Comment by ivcoder** [comment]
Cool, thank You.

**Comment by OlegKi** [comment]
@ivcoder : I posted [the changes](https://github.com/free-jqgrid/jqGrid/commit/efea1cb604f1d17e9cdaca444ac8bb6eb6e3d227) to GitHub. Please test the new code from GitHub and confirm that the bug is fixed now. Please close the issue if the bug is fixed.

Thank you once more for reporting the bug.

**Comment by ivcoder** [comment]
Works like a charm. Thank You.
