### ISSUE TITLE
Composite and natural primary keys are not supported

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#193]
There is no support for composite primary keys. Multiple key: true properties in colmodel are quietly ignored without any error message.
Only one of key columns is picked randomly. This causes data corruption.

If primary key column contains characters not allowed as id values, strange and difficult to understand errors occur in random places in jqgrid.
jqgrid does not convert those characters to legal ones.

In those cases users are forced create custom columns with custom endoding and split/unsplit functions. This requires extra coding, adds extra column to data and increases data size.

Key field updates are also not supported. Dataset sent to server should additionally contain old key values to allow server to perform primary key updates.

**Comment by OlegKi** [comment]
It seems to me more the question as the feature request of the bug report. Look at the demo https://jsfiddle.net/OlegKi/32pdcLhs/ for example, which have the following code
```JavaScript
$("#grid").jqGrid({
    colModel: [
        { name: "firstName" },
        { name: "lastName" }
    ],
    data: [
        { firstName: "Tony", lastName: "Tomov" },
        { firstName: "Oleg", lastName: "Kiriljuk" }
    ],
    localReader: {
        id: function () {
            return function (item) {
                return item.firstName + "_" + item.lastName;
            }
        }
    }
});
```
If you examine the grid with Developer Tools you will see that the ids of the rows are `Oleg_Kiriljuk` and `Tony_Tomov` composed from `firstName` and `lastName`.

**Comment by kobruleht** [comment]
If first or last name is changed during editing and remote json data is used, this sample produces incorrect result.

Yes, there is solution for this but it requires extra coding and extra field in data. If same json API used by jqgrid is used by other applications also, every application must implement composite field creation and encoding. 
This makes API unnessecarily sophisticated. 

Maybe this conversion can done in cliend by extending this sample: before processing custom composite Id field is created from data and added to colmodel. After processing and before data is send back to server, custom id is decoded and old composite key values are also sent to server.

**Comment by kobruleht** [comment]
Thank you. It looks like this can implemented using jqgrid events: create composite id column in localreader, encode it.  Decode it in serializeGridData and add old primary key values to data sent to server.

**Comment by OlegKi** [comment]
I thought about the problem more and have made [additional modifications](https://github.com/free-jqgrid/jqGrid/commit/028858d633b3c8b24fe6c3b4e129f32bbb53826f) of the jqGrid code. Now one can use `additionalProperties` to construct composite id or/and other composite property, which can be used later.

For example one can use the following code
```JavaScript
$("#grid").jqGrid({
	colModel: [
		{ name: "firstName" },
		{ name: "lastName" }
	],
	data: [
		{ firstName: "Tony", lastName: "Tomov" },
		{ firstName: "Oleg", lastName: "Kiriljuk" }
	],
	additionalProperties: [
		{
			name: "id",
			jsonmap: function (item) {
				return item.firstName + "_" + item.lastName;
			}
		}
	]
});
```
see the demo https://jsfiddle.net/OlegKi/32pdcLhs/1/. If one would examine the items of local `data` one will see `id` property as part of every item.

One can use `key: true` too in one from `additionalProperties` items:
```JavaScript
$("#grid").jqGrid({
	colModel: [
		{ name: "firstName" },
		{ name: "lastName" }
	],
	data: [
		{ firstName: "Tony", lastName: "Tomov" },
		{ firstName: "Oleg", lastName: "Kiriljuk" }
	],
	additionalProperties: [
		{
			name: "fullName",
			key: true,
			jsonmap: function (item) {
				return item.firstName + "_" + item.lastName;
			}
		}
	]
});
```
See one more demo https://jsfiddle.net/OlegKi/32pdcLhs/2/. If one would examine the items of local `data` one will see `fullName` property as part of every item.

In all above cases, one have the same values of rowids with the composite value.

In general the usage of hidden columns can be replaced more and more to the usage of `additionalProperties`, which is the array of strings or objects. In case of string value, it provides just the name of additional property, which will be read from the input and be saved locally in case of local `datatype` or the usage of `loadonce: true` (or at least be filled in custom formatters). In case of object value, it looks mostly like `colModel` item, but it will be **not placed on DOM**, which improves the performance of the grid.

I will extend the usage of `additionalProperties` in the future to simplify sending of the values to the server during editing the rows.

**Comment by kobruleht** [comment]
Thank you. 

jsonread uses hard-coded primary key names.
jqgrid can used to edit different tables. Real primary key columns are always present id data.

How to pass primary key names to jqgrid ? Shoud additional array with primary key names passed in json response or in colmodel. Or should additional property like realKey: true added to colmodel?

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand you. If you have full information about composite primary key *on the server side*, then you can build composite value of `id` property *on the server side* and just include in in the data. If you want to place the array of key as for example `keys` property, than you can use for example `jsonmap: function (item) { return item.keys.join("_"); }` inside of `additionalProperties`. *You* can extend the data returned from the server with **any custom information** and to build rowid from the custom information inside of `jsonmap` of `additionalProperties`. You should just return from `jsonmap` the unique string, which you want to use as rowid.
