### ISSUE TITLE
Wrong insertion position (bug)

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#195]
Hi! It turns out that the bug/issue that jqGrid 4.7.0 has free-jqGrid has as well. The issue is about a wrong position of the inserted row. The **addChildNode** function inserts child row in different position depending on how the grid load children rows. If the grid loads all rows at once than position of the inserted child row is the last child. It's OK. But when a row expands if the grid loads data dynamically than position of the inserted child can be different. [Here](https://jsfiddle.net/ovkadurin/ve6k2q7L/) is a jsFiddle that shows grids and describes how to reproduce a bug. 

Below I copied the description of a bug from the above link just in case.

---
Here are 3 jqGrid tables. First two tables use autoid=true/false and load children
rows dynamically. The main thing is dynamic loading. Testing of the "autoid" property was just 
a wrong assumption.
  The third table loads data at once.
  
  The bug is about a wrong inserted row position in case of dynamic children rows loading. So first two
tables have this bug and the third one doesn't.

  Steps to reproduce a bug (might be applied to any of grids on the right)
1) Expand "name3"
2) Expand "name1"
3) Expand "nam11"
4) [Optional] Collapse "name11"
5) Click on the button below the corresponding grid

  In case of first two grids the inserted row will be after the "name11" (keeping right level) which is a wrong position.
  In case of the third grid the position will be "the last child of name1" which is a right position.

  BTW, on the step 3 you can expand "name12". In that case the position of the inserted row will be after "name12" (keeping right level).

---

I drilled down a little. And it turned out that the reason of so different behaviour is because of how children rows of a new parent row are fetched (and/or how the rows are stored in the **data** variable). In case of dynamic data loading when a row is expanded all its children are pushed in the **data** array (at the end). And when **addChildrenNode** is [invoked](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.treegrid.js#L499) it [calls](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.treegrid.js#L534) **getFullTreeNode**  function which returns unordered array of new parent row children. The last element in that array is the last child of a last expanded row. And the further logic is to [insert](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.treegrid.js#L612) a new row after the last row in the array (keeping right level). 
In case when the grid loads all the data at once the last element in the **data** array is the last visual element. It can't be at the middle. So in this case it works fine.

---
To fix a bug for this case it is needed to sort children properly in the function **getFullTreeNode**.  [Here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.treegrid.js#L292) is a place where children are sorted currently. How to make sorting and at what place is another task which is up to you.

**Comment by OlegKi** [comment]
Thank you very much for the detailed bug report, the demo and the analyzing of the problem!

I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/7454c0c8c56ad788d686f9c515ae46bf1f8caae9) to GitHub. It goes through the elements returned by `getFullTreeNode` and find the highest `rowIndex`. The [rowIndex](http://www.w3schools.com/jsref/prop_tablerow_rowindex.asp) is just the position of the row in the table. The inserted node will be inserted at the position of the highest `rowIndex` among the all children + 1.

The demo http://jsfiddle.net/OlegKi/ve6k2q7L/93/ have the same code like youth, but it uses the new code from GitHub. It seems to work correctly now.

**Comment by okadurin** [comment]
Thanks a lot for so quick fix! I've just tested it on the my local project. I works perfect.

**Comment by OlegKi** [comment]
Thanks for the info!

I forgot to mention, that free jqGrid have `beforeExpandNode` and `afterExpandNode` callbacks, which will be called inside of `expandNode`. Both callbacks have one parameter, which is the object with two properties `rowid` and `item`. The usage of `beforeExpandNode` allows to remove the requirement of "subclassing" of `$.fn.jqGrid.expandNode` method in the demo. You can just define `beforeExpandNode: function (options) {...}` callback and to use `options.rowid` (or `options.item._id_`) and `options.item.name` inside of the body of the callback function for building the data, which you would set in `postData.json`. Nevertheless, your original demo was already very good, because it simulated correctly multiple Ajax requests. It helps me quickly reproduce and fix the reported problem.

**Comment by okadurin** [comment]
Oh, it's good to know. I will change *$.fn.jqGrid.expandNode* in my project to the build in callbacks you described. Thanks :)
