### ISSUE TITLE
Missing name of field

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#197]
Pls. see this image: http://s27.postimg.org/qgm6qcwtv/error_field.png
Missing name of filed when use editrules:{required:true}.

**Comment by OlegKi** [comment]
Thank you for the bug report. Please verify that the problem is fixed after [the commit](https://github.com/free-jqgrid/jqGrid/commit/88d0597c778cbb2e39a1482afe5db37065a0d25c).
