### ISSUE TITLE
Add check to getCellIndex to fix exception in checkbox click, new pull request button redirects to tony jqgrid repository

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#20]
I added pull request below from free-jqgrid repository but triang jqgrid pull request page appears and pull request was added to tony jqgrid repository instead. So I post it here.

If clickable checkbox formatter with single click inline ediing is used , click in checkbox column causes exception in 4.6 . I fixed this by adding line

`if (c == undefined) { return -1; }`

to getCellIndex:

```javascript
	getCellIndex : function (cell) {
		var c = $(cell);
		if (c.is('tr')) { return -1; }
		c = (!c.is('td') && !c.is('th') ? c.closest("td,th") : c)[0];
	    // AMOOR next line added 25.12.12. If removed single click editing in checkbox column click causes error
		if (c == undefined) { return -1; }
		if ($.jgrid.msie) { return $.inArray(c, c.parentNode.cells); }
		return c.cellIndex;
	},
```

Can this added to 4.8 source code ?

**Comment by OlegKi** [comment]
@kobruleht : Could you describe the problem (the test case) which should the suggested changes fix? If I examine the current code of `getCellIndex` in jqGrid (see [here](https://github.com/tonytomov/jqGrid/blob/master/js/grid.base.js#L67-L73)) I don't see the described line (no ` if (c == undefined) { return -1; }`).

I suppose that you mean some fix required for some old version of jqGrid. If you examine the current code of free jqGrid (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.8.0/js/grid.base.js#L3965-L3967)) you will see that it the user click in the cell then `getCellIndex` will be called **only with DOM of `<td>` element** as the parameters. Old version of jqGrid could be called with *subelement* of `<td>`. So I suppose that the current code of free jqGrid 4.8 or even the code of jqGrid 4.7.

I can imagine only that some problem can exist inside of **double-click** event handler. I will analyse the code and include some additional line `td = $(td).closest("tr.jqgrow>td");` before the call of `getCellIndex`.

It would be helpful if you post some demo/test case which can be reproduce the problem.
