### ISSUE TITLE
Bug in createEl function

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#200]
I've just upgraded free-jqGrid to `v4.12.1` and noticed error `Uncaught TypeError: Cannot read property 'length' of undefined` when opening edit form at line https://github.com/free-jqgrid/jqGrid/blob/master/js/jquery.jqgrid.src.js#L8063:
```javascript
for (i = 0; i < optionInfo.length; i++) {
```
I think it should be:
```javascript
for (i = 0; i < optionInfos.length; i++) {
```

**Comment by OlegKi** [comment]
Thank you very much for the bug report! I verified, the bug exist in all versions starting with 4.9.2. It's difficult to test all use cases.

Now is the problem fixed (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/8ac6bbd63318f7c8503da8d57f82aeb71d9bd45f)). I will post soon some more changes based on your suggestions from another issue (show/hide columns).

**Comment by Wooya** [comment]
Thx for the fix!
