### ISSUE TITLE
Problems with search dialog in bootstrap

### ISSUE THREAD

**Issue by jranita** [free-jqgrid/jqGrid#203]
Search dialog shows up the first time, but after you close it, you cannot open it again without refreshing the page.
The problem was that the modal, at the second time, opens at a negative position. The position is the (last_position - (grid_position-grid.parent_position) ) ... if I understood the code correctly.
The first time it shows at top: 0px relative to the grid, the second time at -278px and the third time at -556px.

Deleting  $gbox.offsetParent().offset()[topOrLeft] from the return value calculation of savePositionOnHide seems to fix the problem.

**Comment by OlegKi** [comment]
Which version of free jqGrid you use? Do you use the latest sources from GitHub? Could you post the demo which can be used to reproduce the problem? [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-bootstrap1.htm), which I use have no problem, wich you describe.

In general, please include **always** the demo which can be used to reproduce the reported problem if you report a bug. I can fix the bug only if I can reproduce it.

**Comment by OlegKi** [comment]
P.S. Is saving of position of Searching dialog is not important, then one can use `recreateFilter: true` option. One can use `recreateForm: true` in Add/Edit dialog to reset the saved position on every opening of the dialog.

I would like still fix all bugs in free jqGrid, which exist. Thus I'd ask you to provide the demo, which reproduce the reported problem with the position of Searching Dialog. The above options `recreateFilter: true` and `recreateForm: true` can be used only as a workaround if you have problem in **productive** solution, which uses free jqGrid, and which can't be easy upgrade to the latest sources.

**Comment by jranita** [comment]
If you add top margins and to your demo <div> elements you can recreate the problem. 
Anyway we found a workaround... when we call the function with jquery we pass the option "overlay: 1".

**Comment by OlegKi** [comment]
**Could you provide the demo which I can use to reproduce the problem?** You wrote
>If you add top margins and to your demo

*Where* I should "add top margins"? (to outer div where the grid be created, to use `top` parameter of searching dialog, ...)? [My original demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-bootstrap1.htm) have already outer div with 5px for all margins:
```html
<div id="outerDiv" style="margin:5px;">
	<table id="list"></table>
</div>
```
If I increase the margin value to 50px I have the same results. If I use different values for margins (different top, bottom, left and right margins) or if I use for example `top:10` option of searching dialog I still can't reproduce the problem.

You wrote
>when we call the function with jquery we pass the option "overlay: 1"

Sorry, but I don't understand what you mean. The overlay is independent from the *position* of searching dialog. The option `overlay: 1` creates overlay, but the user practically unable to see it.

Even if you found a workaround for some problem, which have free jqGrid, it helps not really neither me nor other users of free jqGrid. **I want to fix all bugs, which I find.** If you know some scenario with some combinations of any options, where free jqGrid works incorrectly, please provide the corresponding demo. I can analyse and fix the bug in free jqGrid only if I can reproduce the problem and if I can debug it.

**Comment by OlegKi** [comment]
I made some additional changes in the code of free jqGrid. Please verify whether the issue still exist in case of usage the latest sources. If the bug is fixed, then please close the issue.

**Comment by jranita** [comment]
Hi Oleg,



That bug is fixed… but now it does not recall the last position of the
dialog. Once you close it, it will always reopen on the initial position (top:
0px; left: 0px;).



Thanks,



João Ranita

+32 473.207.683

Visit us http://frepple.com

Woluwestraat 17, 1930 Zaventem, Belgium

[image: frepple-logo]





*From:* Oleg Kiriljuk [mailto:notifications@github.com]
*Sent:* Monday, 8 February, 2016 02:07
*To:* free-jqgrid/jqGrid <jqGrid@noreply.github.com>
*Cc:* João Ranita <jranita@frepple.com>
*Subject:* Re: [jqGrid] Problems with search dialog in bootstrap (#203)



I made some additional changes in the code of free jqGrid. Please verify
whether the issue still exist in case of usage the latest sources. If the
bug is fixed, then please close the issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/free-jqgrid/jqGrid/issues/203#issuecomment-181150408>.

**Comment by OlegKi** [comment]
I **dropped** saving of the position of the dialog. See [the comment to my last commit](https://github.com/free-jqgrid/jqGrid/commit/2135077f77f06dd1a792f1052c1c83bcbca4ed9c). The support of the feature is very time intensive. The problem is that there are a lot of different use cases. One changes backs another test case. I examined many ways of determining the position of element relative to body or to the top of web browser window. No from the methods works correctly in complex cases of element positions. The previous changes for example worked correctly for your case, but it works incorrectly for other test cases. Thus I **removed the code of free jqGrid, which saves the position of dialog**.

**Comment by jranita** [comment]
The dialog stays on the screen... so the problem is solved.
Thank you.
