### ISSUE TITLE
Inline add button does not show row for empty table

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#21]
If inline add button is pressed in toolbar for empty table, added row does not appear.
Thi scan fixed adding `$(t).show();` to addRowData as shown in code below.
Can this patch applied to jqgrid ?

```javascript
					if(t.rows.length === 0){
						$("table:first",t.grid.bDiv).append(row);
					} else {
					    $(t).show();  // if removed, inline add does not work on empty table
						if (pos === "afterSelected" || pos === "beforeSelected") {
							if (src === undefined && p.selrow !== null) {
								src = p.selrow;
								pos = (pos === "afterSelected") ? "after" : "before";
```

**Comment by OlegKi** [comment]
Could you provide the demo which reproduce the problem? [My first fest](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons0-fa4-empty.htm) shows no problem. Moreover you opened two other issues. I answered you, but I see no replies. **If the problems are solved, please close the issues.**

**Comment by kobruleht** [comment]
In this demo edit row, next page and last page buttons are active if grid is empty. I can create test account and send credentials to you if you are willing to look into it. I closed other issues, there were my mistakes.

**Comment by OlegKi** [comment]
The buttons next page and last page are enabled by default in empty grid in jqGrid 4.6 too. One can disable there in `loadComplete` for example. If you add more as 5 rows in the grid on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons0-fa4-empty.htm) and then change the number of displayed rows to 5 then the buttons next page and last page will be enabled.

So I don't see any new problems in free jqGrid 4.8. Just try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons0-fa4-empty46.htm) which uses jqGrid 4.6 and you will see that.
