### ISSUE TITLE
Inline edit and save row

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#210]
When you add a row with inline edit and rule **required: true** ,and hover button Inchide , displays the horizontal scroll.

See http://s27.postimg.org/e3hxn06vn/fwvoc7.gif

**Comment by OlegKi** [comment]
Thank you very much for the bug report!

It's really funny effect! I've fixed it now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/cc429c771ddb85f44e856f501990ee70cc3bfd0c)). Please verify that the problem is fixed if one uses the latest sources from GitHub.
