### ISSUE TITLE
jqGrid vs Microdata

### ISSUE THREAD

**Issue by lalato** [free-jqgrid/jqGrid#211]
Hi Oleg,
Have you come across an easy way to add Microdata (for Google search Structured Data) tags to the jqGrid results?

**Comment by OlegKi** [comment]
Sorry, but your should specify more exact what you like to implement. For example, you can use `rowattr` and `cellattr` to assign custom attributes on the data of the grid (`itemprop`, `itemtype`, `itemid`, `itemref`, `itemscope`). See [here](http://stackoverflow.com/a/18313154/315935), [here](http://stackoverflow.com/a/12180842/315935), [here](http://stackoverflow.com/a/10531680/315935). In the way you can set **any** custom attribute.

**Comment by lalato** [comment]
I will take a look at the examples.  Thanks.

The grid is a list of roller derby teams with basic information like Country, City, URL, and Status. I saw the info on Structured Data on the Google Webmaster Tools and wanted to fool around with it to learn in my spare time.
