### ISSUE TITLE
poor scroll performance in IE 11 with large number of rows amplified by large horizontal grid width

### ISSUE THREAD

**Issue by cwebster2** [free-jqgrid/jqGrid#215]
We are evaluating free jqGrid as an upgrade from jqGrid 4.6 due to some nice features Oleg has added that work great for us.  However, our primary use-case requires that we support IE 11 and with any version of free jqGrid >= 4.8 we are seeing poor performance when scrolling the grid, particularly horizontal scrolling.  

I have created a small demo to show this:

https://plnkr.co/edit/Vjf2Nknt9wGp9OnpDfX4?p=preview

This javascript we are using the create the grid and populate the test case is:

```
$(document).ready(function() {
  var ipsum_long = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse odio ligula, laoreet sed urna eget, feugiat luctus augue. Cras tincidunt vitae ante blandit vestibulum. Nam a ipsum non orci porta efficitur vitae non ante. Fusce ultrices tristique ipsum. Sed eleifend, purus ut porta malesuada, dolor orci bibendum purus, a ullamcorper nisl est porta ante. Aenean aliquet risus eu eros placerat, eu rhoncus urna imperdiet. Suspendisse at velit augue. Curabitur posuere turpis pharetra vestibulum ullamcorper. Ut finibus massa ut ante scelerisque, ultricies consectetur odio commodo. Sed ut enim tincidunt, rutrum justo ut, gravida augue. Aenean ut velit volutpat, ornare massa id, pharetra dui. Nulla nec semper dolor. Nam vulputate, eros sed auctor pulvinar, tellus sem luctus ex, et lacinia risus lorem euismod elit. Maecenas ut luctus mi. Ut vehicula, nulla at viverra facilisis, justo sem tristique dui, sit amet porta justo magna sit amet sapien. Integer vitae rutrum nibh, sed condimentum arcu. Aliquam eros urna, tempus in porttitor eu, venenatis ut lacus. Nunc facilisis molestie metus, commodo porta nisi. In hac habitasse platea dictumst. Praesent molestie tortor sit amet ipsum placerat imperdiet. Ut dictum nisi pretium ullamcorper ornare. Cras bibendum rutrum fringilla. In egestas consequat risus, at porttitor urna lacinia ac. Integer nec elementum magna, nec faucibus massa. Integer sagittis, dui id viverra porta, tellus mi efficitur diam, ac commodo justo eros vel tellus. Proin eu nisl egestas, tincidunt dui ac, condimentum elit. Nullam faucibus nulla quis erat dapibus, vitae laoreet libero mollis. Aliquam aliquet lorem nibh, et tincidunt odio efficitur sit amet. Vivamus bibendum facilisis neque in commodo. Maecenas et lorem eget urna volutpat accumsan vitae ac orci. Fusce egestas feugiat eros eu venenatis. Proin faucibus sagittis cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ut ullamcorper quam, non sodales mauris. Phasellus laoreet maximus elit. Maecenas nisl ligula, sollicitudin a semper id, viverra id ante. Morbi sit amet metus a leo rhoncus interdum. Nullam vitae massa leo. In at cursus odio. Integer vel felis eget diam rhoncus gravida. In maximus posuere neque vitae cursus. Proin eu vestibulum ante. Cras interdum leo sed dui lacinia, eu tempor ligula rhoncus. Suspendisse purus dui, lobortis sit amet sapien eu, feugiat aliquet risus. Donec non arcu accumsan, placerat erat sed, auctor ligula. Nulla tempor neque at lobortis suscipit. Proin eleifend, ipsum at dignissim congue, lacus nisl consectetur ante, sit amet facilisis elit velit ut diam. Sed tincidunt enim id porta fermentum. Vestibulum libero nisl, finibus sed iaculis sed, ultrices vitae felis. Nunc dui tortor, commodo nec est tempor, auctor sagittis lorem. Donec urna leo, consectetur non felis id, efficitur sodales sapien. Morbi egestas mi sit amet massa tincidunt, sit amet convallis felis faucibus. Praesent vitae turpis at urna bibendum fermentum nec at felis. Curabitur semper est ut purus luctus rutrum. Nunc vitae justo non augue congue consectetur quis vitae nibh. Pellentesque fermentum semper mi, a commodo arcu luctus vitae. Duis fringilla mollis sem scelerisque dignissim. Aenean ullamcorper lacus nec ullamcorper congue. Curabitur et erat quis libero malesuada.",
    ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.";

  var myCm = [];
  for (var k = 0; k < 50; k++) {
    myCm.push({
      name: "column" + (k + 1),
      width: 325
    });
  }

  var myData = [];
  for (var i = 0; i < 150; i++) {
    var t = {};
    for (var j = 1; j <= 50; j++) {
      t["column" + j] = (j === 1) ? ("Row " + i) : ipsum;
    }
    myData.push(t);
  }

  var $grid = $("#list");

  $grid.jqGrid({
    colModel: myCm,
    datatype: 'local',
    data: myData,
    rowNum: 100,
    gridView: true,
    loadonce: true,
    ignoreCase: true,
    ajaxSelectOptions: {
      cache: false
    },
    pager: '#pager',
    gridview: true,
    rownumbers: true,
    sortname: 'column1',
    viewrecords: true,
    sortorder: 'asc',
    caption: "Demonstrating horizontal scroll lag",
    height: 500,
    width: 800,
    autowidth: false,
    shrinkToFit: false,
    sortable: true,
    altRows: true,
    forceClientSorting: true,
  });
});
```

This is a fairly vanilla grid we are constructing and the only thing special about it is that we are making sure we have a lot of rows and that we have many columns that create a grid wider than we can display in the window.  The scroll problem arises when we have a large number of rows and is amplified the more/wider the columns are.  You can tweak the demo to change how many rows we generate and how many columns and how wide they are.  This might seem a bit contrived, but our production grid has 100's to 1000's of rows and enough columns that horizontal scrolling is absolutely necessary. 

We do not see this behavior in jqGrid <= 4.6 and we see it in all versions of free jqGrid >= 4.8 that we tested, and we are primarily testing against 4.12.1 and 4.13.   The behavior is only exhibited in IE 11 and we cannot reproduce in chrome, so if you play with this test case, please test with IE 11 to see the behavior.  

Here is a visual of the scroll "lag" for those without IE 11 to reproduce it:
![scrollingissue](https://cloud.githubusercontent.com/assets/5762261/13497313/ace3e1ca-e122-11e5-8463-db2ef890c303.gif)

This appears to primarily be an issue with IE deciding to do style calculations on every grid cell for every scroll event causing rendering delays and delaying the invocation of scrollGrid to update the position of the header columns to match the body.  However, though it is IE being stupid, this doesn't happen with jqGrid 4.6 so we are thinking this has something to do with the way free jqGrid applies styles to the grid DOM elements or how the elements within the grid are structured.

**Comment by OlegKi** [comment]
Thank you very much for the bug report!

The visual effect depend on the settings of IE which you use. See [the answer](https://github.com/free-jqgrid/jqGrid/issues/158#issuecomment-150939066). The performance of the scrolling is another problem. I analysed it and made some changes, which I committed to GitHub (see [here](https://github.com/free-jqgrid/jqGrid/commit/629d16f14dce1357c020a46a650c7b4bd2723a85)). I hope that the performance of scrolling will be the same as in jqGrid 4.6.

I made some other changes in you demo. See https://plnkr.co/edit/tDOUZfCeFMxxIzR4BHIW?p=preview

I removed unneeded `<div>` for the pager and use `pager: true` and I removed some other unneeded options of jqGrid, used the latest version of jQuery and the latest (fixed) version of free jqGrid directly from GitHub, added Font Awesome CSS and some other small changes:
```JavaScript
$grid.jqGrid({
    colModel: myCm,
    cmTemplate: { autoResizable: true, editable: true },
    autoResizing: { compact: true, maxColWidth: 350 },
    //autoresizeOnLoad: true,
    iconSet: "fontAwesome",
    data: myData,
    rowNum: 20,
    pager: true,
    rownumbers: true,
    sortname: 'column1',
    viewrecords: true,
    caption: "Demonstrating horizontal scroll lag",
    width: 800,
    shrinkToFit: false,
    sortable: true,
    altRows: true
});
```
I'd recommend you to use default `height: "auto"` and specify the man height of the grid with respect of `rowNum` only. It removes vertical scrolling from the grid and improves the performance of horizontal scrolling additionally because one don't need scroll unneeded rows (scrolling of 20 rows in my demo is more quickly as scrolling of 100 rows in your demo).

Additionally I **reduced** the width of columns to allow the user to scroll (horizontally) more quickly  to required column. Then the user can use double-click to the column header to set the column width to the optimal width, based on the width of content. The value of jqGrid parameter `autoResizing.maxColWidth` or the same value inside of `colModel` can be used to reduce the maximal width of the column. You can try to use `autoresizeOnLoad: true` too. It can be good of less good depend on your environment and requirements.

Please test the latest version of free jqGrid in your environment and inform me about the resulting performance.

**Comment by cwebster2** [comment]
Oleg, thanks for the quick response!  You are a model developer for sure.  Our initial evaluation of the changes looks good.  If I come across anything else, I'll be sure to post.

**Comment by OlegKi** [comment]
It's a good news! Please make all the tests without hurry and report me any problem which you could find. Please don't forget to close the issue after the problem will be full investigated.

**Comment by OlegKi** [comment]
@cwebster2 : I plan to publish version 4.13.1 at the and of the week. It would be nice, if you could report all the problems, which you've found, in the next days. Please, close the issue if you see the reported problem as solved.
