### ISSUE TITLE
Change isLeaf dynamically

### ISSUE THREAD

**Issue by okadurin** [free-jqgrid/jqGrid#217]
Hi, Oleg! Could you please tell me if it's possible to change _isLeaf_ value _dynamically_ (from true to false in my case) so that the row would display the expand/collapse icon instead the bullet one? I use tree grid with adjacency model. 
I tried to accomplish it by setting the new value via the setRowData function but with no luck. The code is as follows:
```
  var row = $grid.jqGrid('getLocalRow', rowId);  // isLeaf: true
  row.isLeaf = false;
  $grid.jqGrid('setRowData', rowId, row);	
  row = $grid.jqGrid('getLocalRow', rowId);  // isLeaf: false. But the icon is still the same.
```
Thank you!

**Comment by OlegKi** [comment]
Hi, okadurin!

It's not so simple. One will have to reload the grid after the changes or better to change the icon of the node manually. The code of `addChildNode` contains fragment of code which you need (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.1/js/grid.treegrid.js#L552-L560)).

I created [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/LocalAdjacencyTree-leafToNode.htm) for you. One can select a leaf and click the last button of the navigator bar to convert selected leaf to node.

Best regards
Oleg

**Comment by okadurin** [comment]
Thank you a lot! It works like a charm.
