### ISSUE TITLE
Modal dialog is not keyboard accessible

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#22]
Steps to reproduce:

1. Click to Delete action button in jqgrid row.
Delete prompt appears.

2. Press Enter

Observed:

Enter is ignored

Expected:

Row should deleted. Default is Delete button and Enter should invoke it.

According to http://stackoverflow.com/questions/9973352/how-to-enable-keyboard-keys-for-please-select-row-message-alert-box-in-jqgrid

I replaced line

`$("#jqg_alrt").focus();`

in source code to 

`$("#" + alertIDs.modalhead + ">a.ui-jqdialog-titlebar-close").focus();`

but problem persists.

**Comment by OlegKi** [comment]
jqGrid 4.7 and so free jqGrid 4.8 have not full keyboard accessible. Delete dialog of jqGrid had never support of keyboard. I will consider to include the feature in the next version of free jqGrid.

Nevertheless you can use `beforeShowForm` to set `tabindex` attributes on the buttons, to set focus on `DelButton` and then to register `keydown` which simulate `click` on the button having the focus.

[The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/SetFocusInDeleteForm.htm) provides an example of such implementation. It uses the following `formDeleting` option:
```JavaScript
formDeleting: {
    closeOnEscape: true,
    beforeShowForm: function ($form) {
        var $dialog = $form.closest(".ui-jqdialog");

        $dialog.find("a.ui-jqdialog-titlebar-close,a.fm-button")
            .each(function (i) {
                $(this).attr("tabindex", i);
            });
        setTimeout(function(){
            $("#dData").focus(); // set focus on DelButton
            $dialog.keydown(function (e) {
                var $target = $(e.target), $focused;
                if (e.which === 13) {
                    $focused = $(':focus');
                    $focused.click();
                }
            });
        }, 50);
    }
}
```

**Comment by kobruleht** [comment]
If Delete button is pressed from top toolbar, Enter is still ingored on Delete prompt

**Comment by OlegKi** [comment]
Do you mean some problem in "Delete" dialog if the row is selected or you mean the Alert dialog which appears if "Delete" button is clicked and you want to close the dialog by pressing <kbd>Enter</kbd>? In [my demo](http://www.ok-soft-gmbh.com/jqGrid/OK/SetFocusInDeleteForm.htm) I implemented setting focus on "Delete" button of "Delete" dialog. It works without any problem in my tests with Delete button is pressed in top toolbar. I tested in IE10, Chrome, Firefox, Safari and Opera. I have never any problems.

**Comment by OlegKi** [comment]
I made more experiments and have improved the demo. [The new demo](http://www.ok-soft-gmbh.com/jqGrid/OK/SetFocusInDeleteForm1.htm) don't register `keydown` event handler. It just set additional `href="#"` and `role="button"` attributes on the buttons:
```JavaScript
beforeShowForm: function ($form) {
    var $dialog = $form.closest(".ui-jqdialog");

    setTimeout(function(){
        $dialog.find("a.ui-jqdialog-titlebar-close,a.fm-button")
            .each(function (i) {
                $(this).attr({
                    tabindex: String(i),
                    href: "#",
                    role: "button"
                });
            });
        $("#dData").focus(); // set focus on DelButton
    }, 50);
}
```

**Comment by kobruleht** [comment]
I added this code to end of beforeShowForm code in message http://stackoverflow.com/questions/6913618/jqgrid-custom-delete-dialog-message/ and it worked.

**Comment by kobruleht** [comment]
I added this code to end of beforeShowForm code in message http://stackoverflow.com/questions/6913618/jqgrid-custom-delete-dialog-message/ and it worked. I will kept it open since answer contains `I will consider ...`

**Comment by OlegKi** [comment]
@kobruleht Please review the issue. All buttons of modal dialog contains `tabindex` attribute. The warning dialog (alert) about "no rows is selected" have no buttons, but it have `tabindex` attribute in the closing button of the title of the dialog. I think that all problems described in the issue are solved already.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
