### ISSUE TITLE
Additional support for adjusting group totals

### ISSUE THREAD

**Issue by jimmccarthy** [free-jqgrid/jqGrid#221]
Hi,

I recently ran into an issue where I needed to hide certain group totals because the group total did not make sense for that particular group.  Here is the example:

Employees have an HoursPerDay column.  If I group the grid in the following way:

```
Employee Group
  Employee
    Project
      other detail
```

I want to show HoursPerDay total on the EmployeeGroup and Employee group headers but not on the Project header.  I am aware of the fact that you can set the summaryTpl and the summaryType for each group (as an array) but I was having problems with that because I need to be able to apply a group check at run time.  Also, summaryTpl and the summaryType can be set up as functions, but they do not pass the current group when formatting.  Here is what I tried locally and it seems to work pretty well.

Add a new summaryFormat function to the columnModel.
In the buildSummaryTd method, if that summaryFormat exists for a column, call it and pass the current group and the current formatted method.

```
tmpdata = jgrid.format(summaryTpl, vv);

// JMM Custom - if summary format is set, call and pass the group
if (cm.summaryFormat) {
  tmpdata = cm.summaryFormat(g, tmpdata, vv);
}
```

Then when I set up my column I have complete control over how the summary total shows.

```
col.summaryFormat = function(g, formattedColumn, rawValue) {
// Blank out for Project groups
 if (g.dataIndex == "Project") {
  return ""
}
 else {
  return formattedColumn;
}
```

Let me know what you think, this has greatly simplified things for me.

Jim

**Comment by OlegKi** [comment]
I'm sorry for the late answer.

I find the suggestion good. Thank you! I included your suggestion in jqGrid code with only minimal changes:
```JavaScript
if (cm.summaryFormat) {
    tmpdata = cm.summaryFormat.call($t, g, tmpdata, vv, cm);
}
```
See [here](https://github.com/free-jqgrid/jqGrid/commit/e309673e3ea04a0842c0777e4ef7b70756a9e704).

**Comment by jimmccarthy** [comment]
Great thanks
