### ISSUE TITLE
please add jqgrid-bootstrap css file

### ISSUE THREAD

**Issue by Nicolewxyy** [free-jqgrid/jqGrid#222]
thanks

**Comment by OlegKi** [comment]
Sorry, but I think it's a misunderstanding. The file `ui.jqgrid.css` (or `ui.jqgrid.min.css`) contains **all CSS rules** for both jQuery UI or Bootstrap. Thus you need just include `ui.jqgrid.css` and you can use `guiStyle: "bootstrap"`. To be able to use Font Awesome 4.x you need to include `font-awesome.min.css` and to use `iconSet: "fontAwesome"` option. See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa-bootstrap.htm) as an example.
