### ISSUE TITLE
Upgrade from 4.9 to 4.10 causes sortableRows to stop working

### ISSUE THREAD

**Issue by protstein** [free-jqgrid/jqGrid#223]
I recently updated free-jqGrid from 4.9 to 4.13 in order to use the excellent Bootstrap support.  I noticed that grids with sortable rows are no longer working.

In order to demonstrate, I made a jsFiddle of my old code where sortableRows **works**:
https://jsfiddle.net/protstein/d4ruxdh6/

and here is my updated code where drag and drop **no longer works** for rows:
https://jsfiddle.net/protstein/8uqst005/
The only difference is updating the js and css libraries.

I played with this a bit and discovered that my rows are no longer sortable when I switch from free-jqGrid** 4.9 to 4.10**.  Not sure if this is a bug or if there is a problem elsewhere.  I have tried all sorts of things but can not get it to work.

**Comment by OlegKi** [comment]
Thank you for the bug report!

The changes, made in the versions 4.10.0, required call of `sortableRow` *after* the rows are filled. One could place the call in `loadComplete` to make all working.

I interpret the problem as a bug and made [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/5834625cf40198a979833552c96ad1dbd529bd95), which restores original behavior. The latest code from GitHub allows to call `sortableRow` once like it was before. See https://jsfiddle.net/OlegKi/8uqst005/3/

**Comment by protstein** [comment]
Thanks Oleg!  It works perfectly now.  Thanks for fixing so quickly and explaining it so well.

Peg
