### ISSUE TITLE
Bootstrap theme

### ISSUE THREAD

**Issue by witek1902** [free-jqgrid/jqGrid#226]
Hello,
I have a little question. Can I use some bootstrap theme with free-jqgrid?

**Comment by OlegKi** [comment]
Yes, of cause. You need just include [Bootstrap CSS](http://getbootstrap.com/getting-started/) and optionally [Font Awesome CSS](http://fontawesome.io/get-started/) on the page and to add `guiStyle: "bootstrap"` or `guiStyle: "bootstrapPrimary"` option. Additionally you should add `iconSet: "fontAwesome"` option to use Font Awesome icons or `iconSet: "glyph"` to use built-in Bootstrap CSS icons (which will be probably removed from Bootstrap in version 4.x). Including of jQuery UI CSS additionally is not required but it's possible too.

See some demos from [the README](https://github.com/free-jqgrid/jqGrid/blob/master/README4.13.0.md#main-new-features-and-improvements-implemented-in-the-version-4130) to version 4.13.0. The file `ui.jqgrid.min.css` (or `ui.jqgrid.css`) includes all CSS rules required.

It's recommended that you includes all jqGrid files from CDN. See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs) for details.
