### ISSUE TITLE
Show/Hide column 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#228]
Pls see demo:   https://jsfiddle.net/pzeL55tx/1/
I have 2 grid . When select a row , i want hide or show column from grid1, but i see that both column from grid1 and grid2 is hide or show.
This happens to latest version.

**Comment by OlegKi** [comment]
Thank you very much for reporting the bug! I committed [the changes](https://github.com/free-jqgrid/jqGrid/commit/309ec1f6d3661bbff371b97f24c95903590417b5), which should fix the bug. The demo, which you posted works now correctly. I'm closing the issue now. Please confirm that the fix works and reopen it if you find any additional problems.
