### ISSUE TITLE
Invalid target element for this operation exception in IE9 in addJSONData

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#23]
In Internet Explorer 9 line

`self.firstElementChild.innerHTML += rowData.join(''); // append to innerHTML of tbody which contains the first row (.jqgfirstrow)`

in addJSONData causes error

SCRIPT600: Invalid target element for this operation. 
jquery.jqgrid.src.js at character 6

and jqgrid does not render

surrounding code is
```javascript

} else if (self.firstElementChild) {
					self.firstElementChild.innerHTML += rowData.join(''); // append to innerHTML of tbody which contains the first row (.jqgfirstrow)
					self.grid.cols = self.rows[0].cells; // update cached first row
				} else {
					// for IE8 for example
					$tbody.html($tbody.html() + rowData.join('')); // append to innerHTML of tbody which contains the first row (.jqgfirstrow)
					self.grid.cols = self.rows[0].cells; // update cached first row
				}
```

`self.firstElementChild` is undefined .  `for IE8 for example ` branch is not executed.

**Comment by OlegKi** [comment]
Do you use `<meta http-equiv="X-UA-Compatible" content="IE=edge">` in HTML `<head>`? It's mandatory. I suppose that IE9 in you test have simulates some old version of IE. In any way I still not full understand which value have `self.firstElementChild` at the moment. I don't have any IE9, but I can see that `self.firstElementChild` is undefined if IE10 simulate IE8. Probably one can change the line
```JavaScript
} else if (self.firstElementChild) {
```
to
```JavaScript
} else if (self.firstElementChild instanceof HTMLTableSectionElement) {
```
or
```JavaScript
} else if (self.firstElementChild instanceof HTMLElement) {
```
You can try to test this in IE9.

**Comment by OlegKi** [comment]
I posted just now [the fix](https://github.com/free-jqgrid/jqGrid/commit/cb11f6b1094d497990fdd759fd30ac0c8bf303d2). I hope that it will fix the problem in IE9. You need to load the current `jquery.jqgrid.src.js`, `jquery.jqgrid.min.js` and `jquery.jqgrid.min.map` from github.

**Comment by kobruleht** [comment]
I verified that this issue does not occur anymore. IE9 is in Windows Vista and is not upgraded in Vista.

**Comment by kobruleht** [comment]
This issue still occurs . I posted it in https://github.com/free-jqgrid/jqGrid/issues/31

**Comment by OlegKi** [comment]
It's better that you open **one issue** for **one problem**. You don't posted here any additional information. So it's better either to open the issue and post additional information here. Then I would post my answer here too. Alternatively you could open new issue and describe all problems in the new issue. In the case one don't need to open the issue. Is it so?

**Comment by kobruleht** [comment]
Initially I reported it as diffent issue but after that realized that it may be the same issue. Github does not allow to merge two issues into single one. I tested it after first fix and then it worked. Now I used different data and last jqgrid to test and issue occurs again.
