### ISSUE TITLE
Filtertoolbar with searchOnEnter: false 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#233]
In 20 mar 2016, you fixed removing of trailing site spaces in searchOnEnter:false mode , but the problem persists when data is returned by the server via ajax.

**Comment by OlegKi** [comment]
Could you describe more detailed how one could reproduce the problem? Do you have the demo, which I could debug to see the problem?

**Comment by davgino** [comment]
For example, when you type the phrase for searching, after the first 2 letters, grid is loaded with the required data (via json, not clientarray), but immediately i add another 1-2 letters. In this case, the last letters is removed.

**Comment by OlegKi** [comment]
One can use `loadui: "block"` to prevent changes in the grid during loading of data from the server. One can use `loadFilterDefaults: false` option of the `filterToolbar` to prevent loading of the filters from `postData.filters` in the filter toolbar. One can still trigger `"jqGridRefreshFilterValues"` event at any time to force loading of the `postData.filters` in the filter toolbar.

I will look in the code for alternative ways to skip reloading of the filter toolbar in the case which you describe. I still think that the usage of one from two described above options could solve the most practical problems.
