### ISSUE TITLE
setGroupHeaders and remapColumns problem

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#243]
Hi @OlegKi !

I think there's a problem with remaping columns order when `setGroupHeaders` is used. Columns are remaped correctly, but column names stays in old order.

There's example result with `setGroupHeaders` (fourth column should be named "IZ" after remaping instead of "Data wniosku" as were in old columns order):
![image](https://cloud.githubusercontent.com/assets/541588/16032877/08f0d950-3209-11e6-88f1-fdb217271a3f.png)

There's the same example result without calling `setGroupHeaders` (fourth column have correct name "IZ"):
![image](https://cloud.githubusercontent.com/assets/541588/16032921/47828100-3209-11e6-8e08-d3b00f4256d4.png)

I'm calling `setGroupHeaders` function after creation of grid.

**Comment by OlegKi** [comment]
`setGroupHeaders` creates custom headers structures above column headers. You should use `destroyGroupHeader` and `setGroupHeaders` to recreate the column headers *after* remaping of columns. You can get `groupHeader` option before call of `destroyGroupHeader` to have the grouping options used by `setGroupHeaders`. After that you can use `destroyGroupHeader` and then call `setGroupHeaders` with the options saved from the `groupHeader` option. It allows to recreate grouping headers without having direct access to the options used in the `setGroupHeaders` call.

**Comment by Wooya** [comment]
Thx @OlegKi for explanation!
