### ISSUE TITLE
advanced search dialog no longer indents groupings

### ISSUE THREAD

**Issue by bkwdesign** [free-jqgrid/jqGrid#247]
Try it out [on your own demo](http://www.ok-soft-gmbh.com/jqGrid/OK/ColumnChooserAndLocalStorage2_singleSelect.htm)

Here's what I'm seeing:
![advancedsearchdialog](https://cloud.githubusercontent.com/assets/3177513/16461648/9097b2f4-3dfb-11e6-8749-0b87135920a8.png)

**Comment by OlegKi** [comment]
Thank you for the bug report! [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/ColumnChooserAndLocalStorage2_singleSelect.htm) is the modification of another one old demo without adjusting of other parts of the code. It seems that there are some problem in case of usage `overlay: 0` option of the searching dialog which used the demo. I removed the option and the indents looks OK now. I will examine the problem more detailed later (probably at the weekend).

**Comment by bkwdesign** [comment]
ok, thanks so much for the quick reply. This resolves my issues with an older jqGrid implementation that I thought I had successfully transitioned. Removing the `overlay:0` option indeed fixes everything!

**Comment by bkwdesign** [comment]
FWIW - the toolbar search [on this API page of yours](https://free-jqgrid.github.io/api-documentation/index.html) doesn't seem to filter results

**Comment by OlegKi** [comment]
The problem with indents in Searching Dialog should be fixed now. Please confirm that and close the issue.

**Comment by bkwdesign** [comment]
Everything looks good. Thanks, Oleg! Closing...
