### ISSUE TITLE
Cant make custom formatter to work! 

### ISSUE THREAD

**Issue by PeterSandberg** [free-jqgrid/jqGrid#248]
Use Version 4.13.3
Cant make custom formatter to work!

in colModel:
"formatter" : "function (cellvalue, options, rowObject) { return \"<input type='button' value='Edit' />\"; } "

Show 'undefined' in the cell.

Anny help or suggestions is appreciated!

**Comment by OlegKi** [comment]
Custom formatter is the callback function and not the **string**, which contains the code of the function. Thus you should use
```JavaScript
"formatter" : function (cellvalue, options, rowObject) { return ""; } 
```
or
```JavaScript
formatter : function (cellvalue, options, rowObject) { return ""; }
```
to define the custom formatter correctly.

If you need to specify the formatter as the part of the JSON data which you return from the server (which you use as the value of `colModel`) then you should define *new formatter* and then use it in the column. You can define your formatter for example under the name "myFormatter" as following:
```JavaScript
$.fn.fmatter = $.fn.fmatter || {};
$.fn.fmatter.myFormatter = function (cellvalue, options, rowObject) {
    // your formatter code is here
    return "";
};
```
After that you can use
```JavaScript
"formatter" : "myFormatter"
```
See [the answer](http://stackoverflow.com/a/27478324/315935) or [this one](http://stackoverflow.com/a/28471964/315935) for more detailed information.

**Comment by PeterSandberg** [comment]
Thanks for your replay!
I cant get anything to work:
https://jsfiddle.net/976c2r2L/28/

**Comment by PeterSandberg** [comment]
Thanks! 
I loaded the colModel from the server.
$.fn.fmatter... will solve it!
