### ISSUE TITLE
make top toolbar tablet friendly

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#25]
Tablets:

In tablets where big buttons are used, they are wrapped to multiple lines in first column only. Pager and view records occupy separate columns in top toolbar. So in tablets jqgrid creates is lot of empty space in screen, which wastes tablet small screen space.

Add code from http://stackoverflow.com/questions/29041956/how-to-place-pager-to-end-of-top-of-toolbar-in-free-jqgrid answer to place all toolbar elements to inline-block which occupy whole row.

**Comment by OlegKi** [comment]
Thank you for the feedback. I will try to make the text and the icons of free jqGrid more salable. I'll try to include more customization on the toolbar too. The most problem is to find the middle way between compatibility with previously versions and introducing of new features or at least changing the existing structures.

**Comment by kobruleht** [comment]
https://github.com/free-jqgrid/jqGrid/issues/52 last message contains also remarks realtating to this issue.

**Comment by kobruleht** [comment]
for mobile devices it is probably better to design separate compact combo button outside of jqgrid and make those buttons to call jqgrid methods to perform jqgrid actions.
This allows to add also non-jqgrid buttons into this comact meny and allows to use html to design.

Answer in  http://stackoverflow.com/questions/33756543/how-to-use-free-jqgrid-search-and-view-toolbar-buttons-outside-its-toolbar  describes how this can be done.

So maybe it is not reasonable to implement this in jqgrid.

**Comment by OlegKi** [comment]
Thank for the feedback!
