### ISSUE TITLE
Enhancement: new event(s) for subgrid subGridAfterComplete and/or subGridAfterLoad

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#251]
Hi @OlegKi!
There're `subGridBeforeExpand`, `subGridRowExpanded`, `subGridRowColapsed `and `serializeSubGridData `events but there's no event which allows to manipulate received data and/or created legacy subgrid table. In my case those events like `subGridAfterComplete` and/or `subGridAfterLoad `can be useful :)

**Comment by OlegKi** [comment]
There are exist `subgrid` part of `jsonReader` which is responsible for reading subgrid data. The part `jsonReader.subgrid.root` has `"rows"` as default value (`subgrid: { root: "rows", repeatitems: true, cell: "cell" }`), but one can define `root` as function (see [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:retrieving_data#jsonreader_as_function)), which returns **modified** data. If I understand your question correctly, than the usage of `jsonReader.subgrid.root` as function should solve your problem.

**Comment by Wooya** [comment]
@OlegKi thx for your reply, but I think solution which you described doesn't allow to modify/add ex. generated table css classes.

**Comment by OlegKi** [comment]
What you want to modify? I think that you want to modify the **data** of subgrid returned from the server. It would be helpful if you describe what you want more detailed. I have no problem to introduce more callbacks, but having at least one *example* of usage can help to make new interface more comfortable in the usage. Could you prepare the demo with test data and the description which exact changes you want to do inside of the new `subGridAfterComplete`?

**Comment by Wooya** [comment]
@OlegKi for ex. I'd like to add some classes to html table inserted into `div.tablediv`. Pseudo code:
```
subGridAfterComplete: function(DivId, rowId) {
    var table;
    table = $('#'+DivId + ' > table');
    $(table).find('tbody > tr').addClass('table-ellipsis');
}
```

**Comment by OlegKi** [comment]
I still not sure that I correctly understand what you want to implement. The current code looks like you want to add `table-ellipsis` class to **all** rows of subgrid additionally to the class `ui-subtblcell`. The option `rowSubTable` of `guiStyles`. You can for example define
```JavaScript
$.jgrid.guiStyles.myBootstrap = {
    baseGuiStyle: "bootstrap",
    subgrid: {
        rowSubTable: "table-ellipsis"
    }
};
```
and to use `guiStyle: "myBootstrap"` option instead of `guiStyle: "bootstrap"`.

On the other side if you want just apply `text-overflow: ellipsis;` on **all** cells of legacy subgrids then you can just add the CSS rule
```css
.ui-jqgrid-legacy-subgrid .ui-subtblcell td { text-overflow: ellipsis; }
```
Is it what you need to implement?

**Comment by Wooya** [comment]
Yes. Thank you. Closing issue.
