### ISSUE TITLE
Problems with free-jqgrid and select2

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#253]
I'm having a small problem using select2 with ajax and the latest free-jqgrid search. I have a select list that could have a lot of options so I decided to use select2 with the minimumInputLength set so I can narrow the results before loading them. When multipleSearch is true the selection is cleared when I click to add a new search rule even after first selecting a valid option. 

My colmodel is calling select2 ajax as:
```
"dataInit": function(element){
    $(element).width(340).select2({
        placeholder: "Select an option",
        minimumInputLength: 3,
        dropdownCssClass : "ui-widget ui-jqdialog",
        ajax: {
            url: "/mailboxes/mailboxes",
            dataType: "json",
            delay: 250,
            data: function (params) {
                return {
                    query: params.term,
                };
            },
            processResults: function (data) {
                return {
                    results: data.items
                };
            },
        }
    });
```

I've included a screenshot that better shows the problem. See how the selection is cleared when I click "add rule". Any ideas on why this would be happening? How can I tell dataInit to not clear my selection when adding a new rule?
![bug](https://cloud.githubusercontent.com/assets/379016/17103771/36be72e4-523d-11e6-9c38-34c1dac53158.gif)

**Comment by OlegKi** [comment]
I'm not use `select2` with `ajax` option myself. I'm not sure that I correctly understand your question. The gif is good, but the working (or incorrectly working) demo would be better. Additionally I would ask you to specify the exact version of free jqGrid, which you use (for example 4.13.4). Is the problem new in free jqGrid 4.13.4 and it's not exist in some previous version of free jqGrid (for example in 4.13.3) or in some version of jqGrid (for example in 4.6)?

Without having the demo I can only guess that you could fix the problem by adding trigger `change` event (`.trigger("change")`) inside of `select2:select`. The Searching dialog hold internally the filter which will be build dynamically. I suppose that the *original* `<input>` element used by select2 don't get `change` event currently and thus the select will be not saved. `.trigger("change")` should solve the problem in the case.

**Comment by Gazoo** [comment]
Thanks for the response. I'm currently using jqGrid 4.13.4. Do you know exactly how to add the trigger change event that you are talking about so I can see if that fixes it ?
```
$(element).on("select2:select", function () { $(element).trigger("change.select2"); });
```
I tried adding that and it doesn't fix the issue I'm afraid. Its' a bit tough setting up a jsfiddle as this is only broken when using using Ajax remote requests (I'm not sure if jsfiddle supports that).

**Comment by OlegKi** [comment]
Could you prepare the demo which reproduces what you do? I verified in my projects, which uses select2, and I don't have such problem like you describes. It could be that the problem is not in the `change` event after selection the option, but for example in the `change` event after select2 fills the `<input>` or `<select>`, which exists initially. I personally don't need to use select2 with very large dataset and I uses always `dataUrl` and I create the control inside of `selectFilled` callback. In other words I fill first all options of `<select>` and I initialize select2 after that. You use another scenario. One should examine what exactly take place in your case and why you have the described problem.

**Comment by Gazoo** [comment]
OlegKI it took me a while but I created a fiddle that replicates the issue as requested:
http://jsfiddle.net/hhy4oktv/23/

Enter in "test" and select one of the emails. Then click the plus "add rule" button and you can see that the previous selection gets erased when the new search rule row is added.

**Comment by OlegKi** [comment]
I debugged the demo and I understand now the origin of the problem. You use `stype: "select"` **without** any `searchoptions.value`. If the user clicks on "Add rule" button then the searching dialog will be **recreated**. jqGrid have to find the value selected previously in the `searchoptions.value`, but can't. You can fill `searchoptions.value` on select the item. I made simplified code which just fill `searchoptions.value` with the values of the last Ajax request. See http://jsfiddle.net/OlegKi/hhy4oktv/24/ . Another demo http://jsfiddle.net/OlegKi/hhy4oktv/25/ uses `.on("select2:select"` to update `searchoptions.value`. It's not final solution, but I think that you understand the problem and the way how it could be solved.

**Comment by Gazoo** [comment]
Thanks for the detailed explanation and the examples. Yes I didn't fill in the searchoptions.value as the whole point of the exercise was to not populate the entire select list (which may have thousands of items). I think your fixes will work. Many thanks again for the help.

**Comment by Gazoo** [comment]
Dear Oleg,

It looks like I spoke too soon. The moment I add another column to your examples it no longer works I'm afraid :(

http://jsfiddle.net/hhy4oktv/27/

Any ideas?

**Comment by OlegKi** [comment]
You are right. I make some small changes in the code of free jqGrid and modified the demo to the following: https://jsfiddle.net/OlegKi/hhy4oktv/32/ . I hope that the last code will work correctly.

**Comment by Gazoo** [comment]
The new code works great. Thanks again!
