### ISSUE TITLE
Compatible to jquery 3?

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#255]
After upgrading to jquery 3, seems some part of jqgrid is broken, I'm wondering if jquery 3 is "officially" supported or not yet?

**Comment by OlegKi** [comment]
What is broken? "Which part"? If you found a bug then you should prepare the demo and to describe the test case, which can be used to reproduce the problem.

**Comment by ryanlin1986** [comment]
Just solved the problem, it's because the height() for empty jquery 3 now returns undefined, which I used to calc jqGrid height, I will open another ticket to discuss about this.
