### ISSUE TITLE
Cannot disable navbuttons

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#257]
Currently I'm using bootstrap guiStyle in free-jqgrid and I've noticed that adding `ui-state-disable` class to navbuttons doesn't work - I can still click disabled buttons and click action is performed. I'm using this extra code on `onClickButton` event to check that button can be clicked:
```JavaScript
if ($('#MyNavButton').hasClass('ui-state-disabled')) {
    return false;
}
```
Maybe there's a possibility to use `button` tag instead of `div` tag in navbuttons? Then we can perform simple `$('#MyNavButton').prop('disabled', true)` which will work for sure :)
```html
<button tabindex="0" role="button" class="btn btn-xs ui-pg-button" id="MyNavButton" title="My nav button title">
    <div class="ui-pg-div">
        <span class="fa fa-lg fa-fw fa-eye"></span>
    </div>
</button>
```

**Comment by OlegKi** [comment]
The "disabled" class is configured by `guiStyles`. If you use default `jQueryUI` then adding `"ui-state-disabled"` or better both `"ui-state-disabled"` and `"ui-jqgrid-disablePointerEvents"` would be the correct way (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L592)). On the other side, if you use Bootstrap and `guiStyle: "bootstrap"` option of free jqGrid then you should use `"disabled"` class or better both `"disabled"` and `"ui-jqgrid-disablePointerEvents"` classes together (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.4/js/grid.base.js#L680)). You can do for example the following in your code
```JavaScript
var $grid = $("#list"),
	$delButton = $("#del_" + $grid[0].id),
	disabledClass = $grid.jqGrid("getGuiStyles", "states.disabled");

// disable Delete button
$delButton.addClass(disabledClass);
		
// thesting whether the Delete button is disabled
if ($.jgrid.hasOneFromClasses($delButton, disabledClass)) {
	alert("It's disabled!");
}
```
It will work with any `guiStyles`.

**Comment by Wooya** [comment]
Works like a charm! Thx for support again - as usual :) Closing issue.
