### ISSUE TITLE
[Question/Enhancement] Bootstrap modals instead of jQueryUI modals

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#258]
Is there any chance to add support in free-jqgrid for Bootstrap modals, for ex. when Bootstrao guiStyle is used? Currently I'm replacing in my project all jQueryUI modals with Bootbox (which creates Bootstrap modals) and only place in my project where jQueryUI modals are not replaceable just like that (hard coded) is free-jqgrid.

**Comment by OlegKi** [comment]
jqGrid don't use jQueryUI modals. If you use `guiStyle: "bootstrap"` then you don't need to include any jQueryUI CSS or JS file. By the way jqGrid don't use any jQuery UI dialogs. It uses jQuery plugin [jqModal](https://github.com/free-jqgrid/jqGrid/blob/master/js/jqmodal.js). Free jqGrid don't call `.modal` method of Bootstrap, but the look of the created dialog should be very close. The main advantage of the current implementation is the migration from jQuery UI to Bootstrap: one don't need to change the existing JavaScript code, one need mostly add `guiStyle: "bootstrap"`.

**Comment by Wooya** [comment]
Thanks for explanation. Closing
