### ISSUE TITLE
The complex xml data is parsed incorrect in addXmlData

### ISSUE THREAD

**Issue by mirik123** [free-jqgrid/jqGrid#26]
When addXmlData function parses row value it executes:
`v = getXmlData(xmlr, f[i]);`
which actually calls for:
`$(f[i], xml).text();`
that causes a loosing of data when cell value is a complex xml object.
In order to convert xml to json object there should be called:
`v = getXmlData(xmlr, f[i], true);`
`v = xml2json(v[0]);`
Where xml2json can be:
```
// Changes XML to JSON
//http://davidwalsh.name/convert-xml-json
function xmlToJson(xml) {
    // Create the return object
    var obj = {};

    if (xml.nodeType === 1) { // element
        // do attributes
        if (xml.attributes.length > 0) {
            obj["@attributes"] = {};
            for (var j = 0; j < xml.attributes.length; j++) {
                var attribute = xml.attributes.item(j);
                obj["@attributes"][attribute.nodeName] = attribute.nodeValue;
            }
        }
    }
    else if (xml.nodeType === 3) { // text
        obj = xml.nodeValue;
    }
    else if (!xml.nodeType) {
        obj = xml;
    }

    // do children
    if (xml.hasChildNodes && xml.hasChildNodes()) {
        for (var i = 0; i < xml.childNodes.length; i++) {
            var item = xml.childNodes.item(i);
            if (item.nodeType === 3) {
                return item.nodeValue;
            }
            
            var nodeName = item.nodeName;
            if (typeof (obj[nodeName]) === "undefined") {
                obj[nodeName] = xmlToJson(item);
            } else {
                if (typeof (obj[nodeName].push) === "undefined") {
                    var old = obj[nodeName];
                    obj[nodeName] = [];
                    obj[nodeName].push(old);
                }
                obj[nodeName].push(xmlToJson(item));
            }
        }
    }

    return $.isEmptyObject(obj) ? null : obj;
}
```

**Comment by OlegKi** [comment]
It sounds interesting, but I'm not sure that I currently understand what you suggest. You mean probably [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.8.0/js/grid.base.js#L2381) of code which get the cell value using the method `getXmlData`. During building of grid content one needs to get **the string** which represent HTML fragment. The HTML fragment will be set in the corresponding cell of the grid using `addCell` and it will be additionally saved in `rd` which will be placed in the item of local `data` [here](https://github.com/free-jqgrid/jqGrid/blob/v4.8.0/js/grid.base.js#L2397). So the usage of `.text()` seems me really required to get a string.

If you see a problem in XML parsing, then it would be the best if you post a test XML data and the grid which parse it. You can describe which problem you see in the example and you can formulate your suggestion of changing jqGrid code.

**Comment by mirik123** [comment]
For example, when we have the following node: 
`<status><id>1</id><text>comment</text></status>`
.text() converts it to "1comment"
if you don't want it to be converted to json it can be left as a html string (*.html()*) and format it further by the custom formatter at colModel level.

**Comment by OlegKi** [comment]
What `colModel` you have? What values you want to set in which columns of the grid? If you need just place `1` or only `comment` in the cell then you can add `xmlmap` in the corresponding column of the `colModel`. Event you have JSON with an *object* instead of string then you need add `jsonmap` as string or as function. Could you post more full example of XML data (two rows of data) and the corresponding jqGrid?

**Comment by mirik123** [comment]
I found another solution using colModel formatters:
```
function complexformatter(cellvalue, options, rowObject) {
        if ($('#' + options.gid).getGridParam('datatype') === 'xml') {
            xmlvalue = $(options.colModel.name, rowObject)[0];
            //parse xml value
        }
}
```
