### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#264]
When using inline edit mode and i have combo box, width of combo box  to be equal with width cell.

**Comment by OlegKi** [comment]
I think that one can implement this by adding CSS rule
```css
tr.jqgrow select.editable { width: 100% }
```
Is it what you mean?
I'm not designer. Such CSS rule seems good for me. Probably I should add the rule to `ui.jqgrid.css`?

**Comment by davgino** [comment]
One option would be useful in colmodel -> editoptions.

**Comment by OlegKi** [comment]
The existing `editoptions` has already the feature. It's important to understand, that one can specify **any** attribute, which needed be set on the edit control. The feature is old. Look at the end ("other options") of documentation of [editoptions](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:common_rules#editoptions). It means that you can modify the standard `edittype: "select"` like
```JavaScript
edittype: "select",
editoptions: {
	value: "FE:FedEx;TN:TNT;DH:DHL",
	defaultValue: "DH"
}
```
to
```JavaScript
edittype: "select",
editoptions: {
	style: "width: 100%",
	value: "FE:FedEx;TN:TNT;DH:DHL",
	defaultValue: "DH"
}
```
or to
```JavaScript
edittype: "select",
editoptions: {
	"class": "width100",
	value: "FE:FedEx;TN:TNT;DH:DHL",
	defaultValue: "DH"
}
```
where there are CSS rule like
```css
.width100 { width: 100%; }
```
Both of the above settings will work.
