### ISSUE TITLE
Cell and Column wrapping not working

### ISSUE THREAD

**Issue by boulepick** [free-jqgrid/jqGrid#265]
Hi Oleg,

just want to point out that the cell and column header word wrap is not working as expected, unless i'm doing something wrong. From the documentation you mentioned  

> cmTemplate: { autoResizable: true } to set the property in all columns of colModel. If the property is defined, the content of every cell and every column header will be wrapped in additional <span class="ui-jqgrid-cell-wrapper"></span> element. All predefined formatters and unformatters of jqGrid are modified to support the wrapping.

now i have tried it but the long cell contents are not being wrapped and are cut-off. see example here (https://jsfiddle.net/boulepick/py10bo5s/) .

Now i'm changing from gruido-jqgrid to the free-jqgrid and basically porting and testing my code to this version. from the g-JqGrid i used the cell attribute in the colModel to wrap the text in the cell like this `cellattr: function () {	return 'style="white-space: normal;';}`. unfortunately it is not working in the f-JqGrid.

Also what i noticed coming from gruido-jqgrid is the auto-resize functionality of the grid is not working in free-jqgrid. What i mean by that is if you look in my example the grid is inside a bootstrap grid (col-sm-6) and depending on the size of the screen it would resize to it whenever the screen or browser would resize. the reason behind it is basically to have two grids beside each other each in a bootstrap grid (col-sm-6) to make up the screen. now when you resize the screen with bootstrap responsiveness it will resize its columns where as the grids inside would not resize, remain same size or overlap each other depending on how the screen was resized.

Again i might be missing something, but it would be worth looking at and document.

Thanks for the great work.

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand what you need to implement. Simple wrapping of the cells is just CSS style described in [the answer](http://stackoverflow.com/a/6915486/315935). You code contains some important error: the usage of `key: true` property in more as one columns (`groupID` and `itemID`). Moreover the `id` property seems be unneeded too. Auto-resizable of columns is absolutely another feature and it can't be used in combination with wrapping of the texts.

What you probably need is close to the following demo: https://jsfiddle.net/OlegKi/py10bo5s/2/. I recommend you to consider to use `forceClientSorting: true`, which force sorting and filtering of data returned from the server *before* the first page will be displayed by jqGrid.

By the way, free jqGrid don't need typically create any hidden columns, which are unneeded `<td>` elements in every row. If your real code loads the data from the server and you use use `loadonce: true` option then you should consider to add `additionalProperties: ["groupID", "itemID"]`. As the result, the item of local `data` contains `groupID` and `itemID` properties, but there are no unneeded `<td>` elements in every row. Free jqGrid allows to filter or to search for "additional properties" in almost the same way like for "standard data". See the following demos for details: [sortByAdditionalProperties](http://www.ok-soft-gmbh.com/jqGrid/OK/sortByAdditionalProperties.htm), [filterByAdditionalProperties](http://www.ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalProperties.htm), [filterByAdditionalPropertiesAndSearchingDialog](http://www.ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalPropertiesAndSearchingDialog.htm), [filterByAdditionalPropertiesAndSearchingDialog1](http://www.ok-soft-gmbh.com/jqGrid/OK/filterByAdditionalPropertiesAndSearchingDialog1.htm). All the demos uses [the JSON data](http://www.ok-soft-gmbh.com/jqGrid/OK/sortfunc.json) as the input.

**Comment by boulepick** [comment]
Thank You Oleg, as always you are on point. I have made the changes you recommended, removed the hidden columns and added the addtionalProperties property.

 So to be clear if i want to use wrapping i will not be able to use auto-resize feature on all the columns or only the one that has the cell wrapping, even if i define a max column size for that field.

on another note with the additionalproperties field will i be able to use the "getCell" function on those column.

thank you for your great help

**Comment by OlegKi** [comment]
You are welcome! It's important to understand that `getCell` and `getRowData` works much less effectively as `getLocalRow` and it's not recommended to use `getCell` or `getRowData` in case of `datatype: "local"` (or with `loadonce: true`). The `getRowData` method calls unformatter for every cell of the grid of the row. The unformatter get the information from **DOM** (one get typically strings which need be converted back to for example numbers). The `getLocalRow` just get the reference to the JavaScript object with the original data or originally parsed data. The properties could be even complex objects. Thus one should use `getLocalRow` and then get the cell value as the value of the property of the object. The object contains `addtionalProperties` because there are the part of the item of every `data` object, which represent the row. Just examine `data` parameter of jqGrid or the items returned by `getLocalRow`.

Is the main problem with wrapping of the text inside of the cell solved?

**Comment by boulepick** [comment]
Thank you Oleg,
yes it is closed, text wrapping is working fine with the CSS. I should recommend the implementation of cell wrapping with column auto-resize and updating the documentation to indicate that cell wrapping does not working with column auto-resize if that will not be implemented.

Cheers
