### ISSUE TITLE
Allow to use bootstrap color and background classes for cell formatting 

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#266]
Bootstrap color and backgound classes

text-danger, text-warning, bg-danger, bg-warning etc. does not change jqgrid cell colors and backgroud.

To reproduce, use code

´´´
$grid.jqGrid('setColProp', 'Unpaidsum', {
    cellattr: function(rowId, val, rawObject) {
        if ( new Date(rawObject.Duedate   ) < new Date()   ) {
            return " class='text-danger'";
        }
    }

   });
´´´

backgound is not changed.

Also jquery-ui color class

return " class='ui-state-error-text'";

not change color.

Only jquery ui class

return " class='ui-state-error'";

works but this changes background also abd added ugly 2D sunken effect.

SO  link:

http://stackoverflow.com/questions/39174443/how-to-use-bootstrap-color-classes-in-jqgrid

**Comment by OlegKi** [comment]
I'm not sure that I understand correctly what you mean. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa-bootstrap1_1.htm) uses
```JavaScript
cellattr: function () {
    return " class='text-danger'";
}
```
and it correctly displays
![untitled1](https://cloud.githubusercontent.com/assets/249117/18218577/dc23a5f2-7163-11e6-9dae-be7524b23707.png)
[Another demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa-bootstrap1_2.htm) uses
```JavaScript
cellattr: function () {
    return " class='bg-danger'";
}
```
and it displays
![untitled2](https://cloud.githubusercontent.com/assets/249117/18218579/e479432e-7163-11e6-8791-7886c8dac306.png)
I don't see any problem.
