### ISSUE TITLE
setFrozenColumns when footerrow is true

### ISSUE THREAD

**Issue by zajc** [free-jqgrid/jqGrid#272]
We are using 4.13.4 version of free-jqgrid.

If we have a table with horizontal scroolbar with zero (0) records and

> footerrow: true,
> userDataOnFooter: true,

and if we execute
> jQuery("#grid").jqGrid('setFrozenColumns');

The columns which are frozen are duplicated and over scrollbar.

Edit: I found out if we reload this grid than everything works as expected.

**Comment by OlegKi** [comment]
Could you try, whether the same problem exist with the latest sources of free jqGrid. You can load jqGrid from RawGit directly (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)). If the problem exist, please provide the demo which uses non-minimized sources (`jquery.jqgrid.src.js`) and I could use to reproduce the problem.

**Comment by zajc** [comment]
After I have build the demo I found out everything works as expected. I figure it out the main reason was my poorly written code. When frozen columns are generated scrollbar doesn't exist. I have rearranged the code and now it works.
