### ISSUE TITLE
Misaligned column headers when reordering columns in wide grids

### ISSUE THREAD

**Issue by joelwkent** [free-jqgrid/jqGrid#274]
Hi Oleg,

I have found a bug that may be caused by jqGrid or may be jQuery UI sortable. The bug occurs on wide grids when you have a horizontal scroll bar. If you scroll to the right and drag a column header to reorder the column then the column headers become misaligned from the columns in the grid as shown in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/3464839/19552452/b26e7f20-96a7-11e6-8700-dd2f267b5b57.png)

I have created a jsFiddle to demostrate this issue: https://jsfiddle.net/JoelwKent/jq9tj7z0/

Below is a quick fix I have implemented locally, basically it listens for a sortable start event then sets the scollLeft of the header to match the scrollLeft of the body of the grid. This quick fix works fine for me locally but this is not a correct fix for this issue:
```
$( '.ui-sortable' ).each(function(){
    $(this).sortable({
        start: function( event, ui ) {
            var parent = $(this).closest('.ui-jqgrid-view');
            var gridBodyScroll = parent.children('.ui-jqgrid-bdiv').scrollLeft();
            parent.children('.ui-jqgrid-hdiv').scrollLeft(gridBodyScroll);
        }
    })
});
```

Thanks for this great library, it has a lot of great features and saves developers like me many hours of coding!

**Comment by OlegKi** [comment]
Thank you very much for the bug report! I full agree that the code of `sortableColumns` used for reordering the columns misses the setting of the `scrollLeft` property of the `hDiv` (the header div) based on the `scrollLeft` of the `bDiv` (the body div). I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/b8754c2e343091d23445b0bf3592b9a5193c5670) just now. The same line (`ts.grid.hDiv.scrollLeft = ts.grid.bDiv.scrollLeft;`) exists already in many places of jqGrid code. Now it's included in the code of `sortableColumns` too.

See https://jsfiddle.net/OlegKi/jq9tj7z0/31/, which uses just the new code of free jqGrid from GitHub.

**Comment by joelwkent** [comment]
Wow! Thanks for the super quick turn around and updating the jsfiddle to demo the fix. Really appreciate it.
