### ISSUE TITLE
POST data not submitted when using jqgrid editoptions and dataUrl select list

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#280]
I was going to build some dynamic select lists using the editoptions 'dataUrl' for the select list. When I add a item the select list is built correctly on init but when I press the submit button everything else but the select list is sent to the server. If I set the editrules for the select list to required pressing submit just triggers the error [field] must not be empty rule even though an item is selected.

The ajax select list is build as a normal select:

```
<select>
<option value="body">body</option>
<option value="header">header</option>
<option value="uri">uri</option>
<option value="rawbody">rawbody</option>
<option value="full">full</option>
<option value="meta">meta</option>
<option value="uri_block_cc">uri_block_cc</option>
<option value="uri_block_cidr">uri_block_cidr</option>
<option value="uri_block_isp">uri_block_isp</option>
</select>
```

Everything works fine if I just set the select list value instead of using the 'dataUrl' option. I'm using the latest master.

**Comment by OlegKi** [comment]
I tried to reproduce the problem, which you described, on [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3-test.htm). It uses `dataUrl` in the `ship_via` column. The same column has `editrules: { required: true }` property. I couldn't see any problems neither in form editing nor in inline editing. You should provide the demo, which I could use to reproduce and to debug the problem, which you report.

By the way I'm not sure why one could need to use `editrules: { required: true }`  for the column with `edittype: "select"` is you don't specify `multiple: true` additionally to allow selection of multple select options: see [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3-test1.htm). The standard select (without  `multiple: true`) select **always** one (for example, the first one) option and one will see never any warning about the empty value. [The demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3-test1.htm) displays the error message "Shipped via: Field is required" only if one unselect all options using click with pressed <kbd>Ctrl</kbd> key.

**Comment by Gazoo** [comment]
From my testing it looks like the moment I add a "class" option to the editoptions array it triggers this bug. Removing the class options fixes it. 

Not working:
```
"editoptions": {"class": "large","dataUrl": "/myurl"}
```

Working:
```
"editoptions": {"dataUrl": "/myurl"}
```

**Comment by Gazoo** [comment]
I'm not sure if adding the "class" option to the editoptions was even in the API . I'm not sure where I got that? I guess I can work around the issue and use dataInit with $(elem).addClass('large') instead.

**Comment by OlegKi** [comment]
The reason of your problem is very easy. By specifying `"class": "large"` you **replace** the value of `class` attribute. You should use `"class": "large FormElement ui-widget-content ui-corner-all"` if you use jQuery UI guiStyle and to use `"class": "large FormElement form-control"` in case of usage Bootstrap.

**Comment by Gazoo** [comment]
Thank-you for the help Oleg!

**Comment by Gazoo** [comment]
One last note. The class value is only **replaced** when you use it in conjunction with the "dataUrl" option. If I set 'class' => 'large' without dataUrl then the class is **added** by default (not replaced). 

Without dataUrl setting "class": "large":
```
<input class="large FormElement ui-widget-content ui-corner-all"
```

**Comment by OlegKi** [comment]
Good catched! Thanks! I posted [the simple fix](https://github.com/free-jqgrid/jqGrid/commit/605e05e4c0c83d2c4c004df01af75aaa76975e19), which should fix the problem and to apply the attributes (set `class`) **before** processing of `dataUrl`. Inside of Ajax success handler it will be only set options now.

**Comment by Gazoo** [comment]
Thanks for the fix!

**Comment by aberel** [comment]
Just for the records: Oleg, you asked "I'm not sure why one could need to use editrules: { required: true } for the column with edittype: "select""
Well, in my opinion, I use this option required: true because I don't want the user hits ENTER not paying attention which select option is selected by default. In other words, I left the first option value empty, and force the user to select an option conscientiously

Regards!

**Comment by OlegKi** [comment]
@aberel Thanks for the explanation. It sounds than the property `editrules: { required: true }` could be really interesting in cases, when one want that the user should make an **explicitly** choice. Such behavior can really paying attention of the user on the importance of the choice. Thank!
