### ISSUE TITLE
Exporting Grouped Jqgrid Rows to Excel

### ISSUE THREAD

**Issue by AshK14** [free-jqgrid/jqGrid#283]
Hi Oleg,

I wanted to know the mechanism of exporting jqgrid grouped rows to excel.
I am able to export the plain data without grouping from jqgrid to excel. However I did not find any examples of exporting grouped data to excel from jqgrid.

I am using ASP.NET in server side.
Here's the fiddle for your reference,
https://jsfiddle.net/AshK14/hmj45faf/5/

Any help on this would be great.

Thanks.

**Comment by OlegKi** [comment]
Hi!

I'm not sure what you want to implement. Grouping is just the for to display the information. One sort by the grouping column and then include additional grouping header information *between* the rows, where the value of the grouping column ne changed. You don't posted how exactly you use exporting data to excel.  [My old answer](http://stackoverflow.com/a/9349688/315935) and [the another one](http://stackoverflow.com/a/13957161/315935) shows how I do the exporting in my ASP.NET code.

If you do need to know the values from the grouping headers you can find it in `groups` property of `groupingView` (the initial `groupingView` object, used as the option will be extended with other information, which jqGrid uses internally). By using `var groupingView = $("#grid").jqGrid("getGridParam", "groupingView");` you get the current value of `groupingView` and `groupingView.groups` will represent the information about the groups.

Regards
Oleg

**Comment by AshK14** [comment]
Hi Oleg,

Thanks for looking into this.
I require the output excel in the format that I have attached. (used SSRS to generate a sample)
I have input the data according to the data present in the jqgrid in this fiddle,
https://jsfiddle.net/AshK14/hmj45faf/5/

Is it possible to export the grouped data in this format from jqgrid?

Thanks for your help.
[TestRep.xlsx](https://github.com/free-jqgrid/jqGrid/files/710080/TestRep.xlsx)

**Comment by OlegKi** [comment]
Sorry, but it seems to me, that [creating grouped rows](https://support.office.com/en-us/article/Outline-group-data-in-a-worksheet-21147cfc-44c9-42c4-8bce-62fb3e067d73?NS=EXCEL&Version=16&SysLcid=1033&UiLcid=1033&AppVer=ZXL160&HelpId=21023&ui=en-US&rs=en-US&ad=US) is the question *about Excel* and not about **JavaScript** library free jqGrid. jqGrid can't generate any binary data like .XLSX files. You have to do this in your C# code, using OpenXML SDK, for example. I suppose that you should set OutlineLevel, Collapsed and Hidden [properties](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.row_properties(v=office.15).aspx) on rows of the generated Excel file.

**In any way, the discussion is outside of free jqGrid functionality and even outside of JavaScript.** Nevertheless, I wrote some short recommendation, what you could try to solve your problem.

I'd recommend you to install [Open XML SDK 2.5 for Microsoft Office](https://www.microsoft.com/en-us/download/details.aspx?id=30425) (both OpenXMLSDKV25.msi and OpenXMLSDKToolV25.msi) and to open your test file [TestRep.xlsx](https://github.com/free-jqgrid/jqGrid/files/710080/TestRep.xlsx) with respect of "Open XML SDK 2.5 Productivity Tool". By click on "Reflect Code" button you will see the code, which can be used to generate the file. The part of the code saved in the function `GenerateWorksheetPart1Content` generates the content of the grid. `Row row3` will correspond to the row with the text "test". `Row row3` will correspond to the row with the text
```
test
```
`Row row4` will correspond to the row with the text
```
test	200	10	210	TN	note
```
and the picture
![image](https://cloud.githubusercontent.com/assets/249117/22015947/965dd5fe-dca4-11e6-863d-a9349943d81e.png)
and so on. The row `row3` (like `row6`, `row8`, `row10`) will be created with the same properties like the previous lines 
```cs
Row row3 = new Row(){ RowIndex = (UInt32Value)3U, Height = 18D, CustomHeight = false };
```
but the `row4` and `row5` (the collapsing rows in the first group) have additional properties: `Hidden = true, OutlineLevel = 1, Collapsed = true`
```cs
Row row4 = new Row(){ RowIndex = (UInt32Value)4U, Height = 18D, Hidden = true, CustomHeight = false, OutlineLevel = 1, Collapsed = true };
Row row5 = new Row(){ RowIndex = (UInt32Value)5U, Height = 18D, Hidden = true, CustomHeight = false, OutlineLevel = 1, Collapsed = true };
```
I recommend you to examine C# code generated by the "Open XML SDK 2.5 Productivity Tool" from your test files. It seems to me the shortest way to solve your problem.

**Comment by AshK14** [comment]
Thanks for your suggestions.
Will give it a try..

**Comment by OlegKi** [comment]
I did't get any message since more as a week. Moreover, the thread discuss the usage of ASP.NET and has no direct relation to jqGrid. Thus I closing the issue. You can still post more comments in the tread or reopen it.
