### ISSUE TITLE
info_dialog custom buttons bug

### ISSUE THREAD

**Issue by kosiaciok** [free-jqgrid/jqGrid#284]
There might be a small bug in the `info_dialog: function ()`. If I provide it an array of buttons with custom onClick functions for each button it does not bind them. As far as I can understand `jgrid.jqID($t.id)` should be replaced with `jgrid.jqID(this.id)` to bind on individual button id? See [this fiddle](https://jsfiddle.net/kosiaciok/7tvanrat/) showing the issue.
Used version: 4.13.6
Bug location: grid.common.js:308

````javascript
// attach onclick after inserting into the dom
if (buttstr) {
   $.each(mopt.buttons, function (j) {
      $("#" + jgrid.jqID($t.id), "#info_id").on("click", function () { mopt.buttons[j].onClick.call($("#info_dialog")); return false; });
   });
}

**Comment by OlegKi** [comment]
Thank you very much for the bug report! I committed [the fix](https://github.com/free-jqgrid/jqGrid/commit/b75471f8b34690946a0551badb5a103e8b8e75d3), which should fix the bug. The modified demo https://jsfiddle.net/OlegKi/7tvanrat/1/ uses the latest code from GitHub.

**Comment by OlegKi** [comment]
Could you confirm, that the latest code of free jqGrid has no problems, which you reported? Please close the issue if the bug is fixed.

**Comment by OlegKi** [comment]
@kosiaciok: I didn't get any answer from you in the last days. The bug is fixed in my tests. Thus I'm closing the issue now. If you do will find some problem you can reopen it later or to post a new issue.

Thank you once more for reporting the bug.
