### ISSUE TITLE
Does 'jQuery('#grdName').jqGrid('footerData', 'get')' works?

### ISSUE THREAD

**Issue by PeterSandberg** [free-jqgrid/jqGrid#285]
Hello!
I got a sumrow. It shows, but I can not get the data from it!
I use to work. But now I only get a empty object.

var sumRow = jQuery($this.options.grdName).jqGrid('footerData', 'get');

Is it something I doing wrong?
Any sugestions?

**Comment by OlegKi** [comment]
Please, send more details about the problem:
- which version of free jqGrid you use?
- how you fill the data in the footer row? Do you call `$("#gridId").jqGrid(`footerData`, 'set', data);` explicitly before (inside of `loadComplete`, for example) or you use `userDataOnFooter: true` and have specified/set `userData` option (or included `userdata` in JSON/XML data of the grid's input), ...
- do you verified that the line with `...).jqGrid('footerData', 'get');` was called *after* `...).jqGrid('footerData', 'set', yourFooterData);`?

**Comment by PeterSandberg** [comment]
Hello!
Version is: 4.13.6

I call:
grid.jqGrid('footerData', 'set', { 'Name': 'Totalt:', 'Gross': sumGross, 'Tax': sumTax, 'NetPay': sumNetPay, 'PrivateKm': sumPrivKm, 'BenefitValueDriving': sumBenefitValueDriving,'PriceMile': PriceMile, 'SumBenefitValue': SumBenefitValues, 'BasisPayrollTaxPrivatDriving': sumBasisPayrollTaxPrivatDriving });

>do you verified that the line with ...).jqGrid('footerData', 'get');
Yes, I se the summs/values in the footer and when I press a button....

**Comment by OlegKi** [comment]
Thank you for the bug! I posted the corresponding bug fix in [the commit](https://github.com/free-jqgrid/jqGrid/commit/b32affbef2cb2a95f2e12f0027ff3140b63a398d) (see the comment to the commit for more details). Please, confirm that the latest code fix the problem and close the issue finally.

**Comment by PeterSandberg** [comment]
It works. Thank you (your are the best) !!!
