### ISSUE TITLE
"navButtonAdd" has problems inside a jqueryui dialog inside tabs

### ISSUE THREAD

**Issue by dkrey** [free-jqgrid/jqGrid#286]
Hi,
I think I've found a bug in connection with Jquery 3.1.1 and the most recent jqGrid.
The grid needs to be inside a dialog which is inside tabs. 
Then you create the grid and add a button to the pager with navButtonAdd.
Now you need to open the dialog, the grid and the button should appear normally.
If you now close the dialog and switch the tabs back and forth, the next time you open the dialog you see multiple buttons in the pager.
This doesn't happen with Jquery  1.12.x

Here's a demo:
http://sonores.de/jqgrid_bug/index.php
- open "Grid Test" tab
- click on "Show Grids"
- Close the dialog
- open "Home" tab
- open "Grid Test" tab
- click on "Show Grids"
- find three "new line" buttons instead of 

Thanks for looking into this!

**Comment by OlegKi** [comment]
It seems to be a bug in your demo. I don't full understand how you load all the content, but one can see from testing that you **append** the same `<table id="demo_grid1"></table>` with **the same id** on every activation of the tab "Grid Test". You can open Console and to execute
```JavaScript
$("*[id=demo_grid1]").length
```
You will see 1 on the first opening, 2 at the second opening and so on.
![t](https://cloud.githubusercontent.com/assets/249117/22122816/a626de7c-de89-11e6-86ed-35949252bd26.png)
You should change your code to have no id duplicates on the page.

**Comment by dkrey** [comment]
You're absolutely right. Sorry for the false alarm.
The problem is that, Jquery seems to place the generated dialog below the tabs. And each time I switch the tabs, the dialog gets generated again and again. 
Adding `
        activate: function(event, ui) {
            $("div[class*='ui-dialog']").empty();
            ui.oldPanel.empty(); 
        }` 
in the tab code, fixed this. Sorry to have bothered you. Keep up the good work 👍

**Comment by OlegKi** [comment]
No problem! You are welcome!
