### ISSUE TITLE
problems with search templates and select lists

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#287]
I started using tmplFilters to write some predefined search templates. Everything works well except for when the colModel entry 'stype' is 'select':

For some reason when selecting the predefined search template jqgrid is trying to select using the opt name instead of the opt value.

I tried to work around the issue by setting the tmplFilter "data" using the select list name instead its value and then the select list gets preselected like it should but then the select list name is submitted to the server instead of its option value.

Am I missing something here or is this just a bug?

**Comment by Gazoo** [comment]
Just to be a little more clear here is an example:

Colmodel builds select list
```
<select id="jqg2" name="status" size="1" class="ui-corner-all input-elm">
<option value="403">403 - Forbidden</option>
<option value="404">404 - Not Found</option>
<option value="405">405 - Method Not Allowed</option>
<option value="406">406 - Not Acceptable</option>
</select>
```

tmplFilters: [template1, template2] . Eg. template:
````
var template1 = 
{ "groupOp": "AND",
      "rules": [
        { "field": "protocol", "op": "eq", "data": "404"}
      ]
};
```
When the search template is selected 404 is not selected as it should be.

**Comment by OlegKi** [comment]
Could you post the demo, which can be used to reproduce the problem?

I tried with [**this demo**](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa-bootstrap-tmplFilters.htm). The searching templates "Template One" and  "Template Two" are defined as following
```JavaScript
tmplNames: ["Template One", "Template Two"],
tmplFilters: [{
	groupOp: "AND",
	rules: [
		{ op: "ge", field: "tax", data: "20" },
		{ op: "gt", field: "amount", data: "250" },
		{ op: "eq", field: "ship_via", data: "TN" }
	]
},
{
	groupOp: "AND",
	rules: [
		{ op: "ge", field: "tax", data: "30" },
		{ op: "gt", field: "amount", data: "250" },
		{ op: "eq", field: "ship_via", data: "FE" }
	]
}]
```
and everything seems to work correctly.

**Comment by Gazoo** [comment]
You are right its working. It looks like I had a json_encode issue. Thank you !

**Comment by OlegKi** [comment]
You are welcome!
