### ISSUE TITLE
Grouping removes the lines missing the property

### ISSUE THREAD

**Issue by tlunven** [free-jqgrid/jqGrid#288]
Hello,

We are using jqgrid with a rest service that does not return an item's property if they are the default value.
The issue that I am having is that when grouping on a property, the rows without the property disappear.

Here is a reproduction with the default demo, the line with Client = "test" from the data array should be in the closed = false group but it is missing instead.
https://jsfiddle.net/2xe4s3qL/

Is there an option or workaround that I am missing that would do the trick ? Except returning the data of course ;)

Thanks for an otherwise great library ;)
Thomas

**Comment by OlegKi** [comment]
Your can solve the problem in two steps:
1. Remove the rule `{ op: "ge", field: "amount", data: "200" }` from the `postData.filters`, because it prevent displaying the item `{ id: "10",	 invdate: "2015-10-01", name: "test",	note: "note",	ship_via: "TN", total: "" }`
2. Add `jsonmap(item) { return item.closed === true; }` to the column `closed`. It force the usage of `undefined` value as `false`.

See https://jsfiddle.net/OlegKi/2xe4s3qL/4/

**Comment by tlunven** [comment]
Thank you Oleg, I fixed it with the following in the function that sets up the columns :

    column.jsonmap = function(item) {
        if (!item[column.index]) {
            return null;
        } else {
            return item[column.index];
        }
    };

Couldn't this behaviour be made an option of the grid itself ? or be the default ?
It seems more logical to the user to put the items in the "empty" group if the value is not present since it's what is displayed anyway.

**Comment by OlegKi** [comment]
The main problem: I try to hold free jqGrid **upwards compatible to old 4.x versions of jqGrid**. jqGrid separate *reading of input data* with optional saving there in local `data` and *formatting of previously read data*. I suppose that you use `formatter: "checkbox"`. If no `jsonmap` specified then the data will be saved like there were in the input: `undefined`. The grouping skipped undefined values.

I though about your suggestion and made some changes in the code of jqGrid (see [here](https://github.com/free-jqgrid/jqGrid/commit/841ad33e0fd9c9fbc1a3d541c4a2c88dc95fa204) mostly). Now one uses `formatoptions.defaultValue` during grouping for columns, where some formatter is defined. Moreover, I set `defaultValue: false` as `formatoptions` for `formatter: "checkbox"`.

As the result the code **without any additional `jsonmap`** display all undefined values now:
https://jsfiddle.net/OlegKi/2xe4s3qL/5/

**Comment by tlunven** [comment]
I wasn't using any formatter actually, I just used the checkbox here because it reproduced the bug I had.
But thanks, I'll try using the new feature when I have the time ;)

**Comment by OlegKi** [comment]
@tlunven : You wrote "I wasn't using any formatter actually, I just used the checkbox here". Your original demo used grouping in the column `"closed"` (see the line `.jqGrid("groupingGroupBy", "closed")`), which uses `template: "booleanCheckbox"`. The `template: "booleanCheckbox"` is shortcut some other properties in the column. It's defined [here](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/jquery.fmatter.js#L158-L174). The properties includes `formatter: "checkbox"` (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.13.6/js/jquery.fmatter.js#L159)). Thus your demo do use the formatter "checkbox". I'm not sure how one could "just use the checkbox" without using `formatter: "checkbox"` or some custom formatter.

In any way, your original demo will display *all lines* in grouping, just after upgrading to the latest version of free jqGrid from [GitHub](https://github.com/free-jqgrid/jqGrid).

**Comment by tlunven** [comment]
The exemple was using the formatter but my production code wasn't ;)

Here is your example updated to reproduce my problem with the "name" column:
https://jsfiddle.net/c1tsnLvf/

I removed the name property from the id=10 line and when grouping on name, that line disappears.

**Comment by OlegKi** [comment]
Sorry, but the last demo has **no value** in `name` column. jqGrid has no information about *default value* for the column. Thus if jqGrid group by **the values** in the column `name` it can't display the corresponding item of data. You have to define *how to display* the undefined value by specifying `defaultValue` of `formatoptions`. The `formatoptions` has any sense only in case of usage some `formatter`. Then you can include some "dummy" formatter like
```JavaScript
formatter: function (value) { return value; }, formatoptions: { defaultValue: "UNDEFINED" }
```
to have the following results: https://jsfiddle.net/OlegKi/c1tsnLvf/1/

You can specify such dummy formatter with default formatting value in `cmTemplate`:
```JavaScript
cmTemplate: {
    autoResizable: true,
    editable: true,
    formatter: function (value) {
        return $.jgrid.htmlEncode(value);
    },
    formatoptions: { defaultValue: "" }
},
```
In general you can define such dummy formatter *once* as default option of jqGrid and then uses it many grids without any additional option in any grid
```
$.jgrid.defaults = {
	cmTemplate: {
		autoResizable: true,
		editable: true,
		formatter: function (value) {
			return $.jgrid.htmlEncode(value);
		},
		formatoptions: { defaultValue: "" }
	}
};
```
See https://jsfiddle.net/OlegKi/c1tsnLvf/4/

**Comment by OlegKi** [comment]
@tlunven: I didn't here anything from you about the problem since almost 20 days. Please, close the issue or post an additional information about the problem.

**Comment by tlunven** [comment]
Nothing to add, thanks for your help !
