### ISSUE TITLE
Text is not encoded in the id so it's not protected against XSS

### ISSUE THREAD

**Issue by ChronicSphinx888** [free-jqgrid/jqGrid#295]
When you edit or delete a row and the id contains XSS like the following '">><marquee><img src=x onerror=confirm(1)></marquee> that code is executed.  Or if you have <script>alert(1)</script>

**Comment by OlegKi** [comment]
jqGrid allows to render the data on the server. Thus one allow to fill the grid with any HTML data in the cell.

One should use `autoencode: true` option to prevent such problems. Try to edit the grid of [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/formEditOnDoubleClick-jqueryui-fa3.htm), for example, which uses `autoencode: true` option. The data like `<script>alert(1)</script>` will be not executed. The data will be encoded before placing on the page.

Your remark about "delete a row" and the id contains XSS seems me wrong. **The user** can't specify ids, if you correctly use jqGrid.
