### ISSUE TITLE
beforeSaveRow in format options not firing

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#299]
I am trying to fire an event when the inline Save button is clicked in order to verify some stuff before data saving. Currently, I am using afterSave method but this method fires after data saving so I cannot prevent it in case of error. In order to solve this, I tried to use the following code but the method **beforeSaveRow** in **formatoptions** is not working:

 formatoptions: {

                                keys: true,
                                beforeSaveRow: function (rowId) { 
                                               alert("before save row");
                                 },
                                afterSave: function (rowId) {
                                    var rowData = JSON.stringify($('#prodgrid').jqGrid('getRowData', rowId));
                                    $.ajax({
                                        url: 'ProdData.asmx/Edit',
                                        type: 'POST',
                                        dataType: 'json',
                                        contentType: "application/json; charset=utf-8",
                                        data: JSON.stringify({ id: rowId, data: rowData }),
                                        success: function (result) {
                                            var res = result.d;
                                            if (res.status == "KO") {
                                                $('#prodgrid').editRow(rowId, true);
                                                alert(res.message);
                                            }
                                        },
                                        error: function() { }
                                    });
                                },

Can you please help me in addressing the right method to be called?

**Comment by OlegKi** [comment]
It's not recommended to use `formatoptions` to set the options of **inline editing**. You should use jqGrid option `inlineEditing` instead. It allows to specify *any* inline editing options or callback:
```JavaScript
inlineEditing: {
    keys: true,
    beforeSaveRow: function (o, rowid, editOrAdd) {
        // one can return false to stop saving
    },
    saveRowValidation: function  (options) {
        // options.rowid, options.newData, options.savedRow, options.mode
        // one can return false to stop saving
    },
    aftersavefunc: function (rowid) {
        ...
    }
}
```
See [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods) for more details.

**Comment by OlegKi** [comment]
@Flanders89 Could you comment my answer? Is your problem is solved now? Please **close** the issue if the problem is solved.

**Comment by Flanders89** [comment]
Now it works perfectly, thanks.

**Comment by Flanders89** [comment]
Now it works perfectly, thanks.
