### ISSUE TITLE
Part of jqGrid is broken

### ISSUE THREAD

**Issue by johncze** [free-jqgrid/jqGrid#3]
Hi Oleg :)

A) Yesterday I crossed to your jqGrid version, but part of jqGrid is not work. I included **jquery.jqGrid.src.js** and I used **sortableRows** function in previous version jqGrid (official release 4.7.0.). Now browser throws exception: 
```javascript
Uncaught TypeError: Cannot read property 'NumberFormat' of undefined
```
, but NumberFormat function is contained in **jquery.jqGrid.src.js**. So I included jquery.fmatter.js. After JqGrid throws:
```javascript
Uncaught TypeError: Cannot read property 'sortableRows' of undefined
```
Then I looked at source **jquery.jqGrid.src.js** and **jquery.jqGrid.min.js** and part of source is commented in Netbeans and Sublime Text. The error is probably on line 10614 see https://github.com/OlegKi/jqGrid/blob/master/js/jquery.jqGrid.src.js#L10614. The source is commented from 10614 line. This same problem in **jquery.jqGrid.min.js**.

B) Should I include initFontAwesome and autoWidthColumns or both are contained in your version jqGrid ? After must I call 
```javascript
$("#table").jqGrid("initFontAwesome ").jqGrid("autoWidthColumns ");
```
before $("#table").jqGrid(options) ? I don't know if I should include plugins or plugins are contained in current your version jqGrid.

Many thanks,

Daniel

**Comment by johncze** [comment]
to A)
Now I found solution. The problem was that I don't include jquery.ui, because default version of jqGrid not required jquery.ui. You could write this requirement into README, please.

**Comment by OlegKi** [comment]
Hi!

Thank you for your feedback.

A) The method `sortableRows` is old jqGrid method described [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jquery_ui_methods#sortable_rows). It needs jQuery UI JavaScript file (not only CSS file). 

B) You should not use more `autoWidthColumns` plugin. I wrote it before for jqGrid 4.6/4.7, but I was not satisfied with the performance. So I **rewrote it full**. Now it's a part of my fork of jqGrid. To activate it you need to do the following 1) define `autoResizable: true` property in all columns of `colModel` which could be resizeable. You can use `cmTemplate: { autoResizable: true }` option of jqGrid to set the property in all columns. 2) Include `autoresizeOnLoad: true` options of jqGrid. There are exist some additional options which allow to change a little the algorithm used to calculate the "optimal" column width. See [demos](https://github.com/OlegKi/jqGrid#some-demos-which-demonstrates-new-features) at the end readme as examples.

B) To use `initFontAwesome` you need use `$("#table").jqGrid("initFontAwesome")` (without the space at the end of the function name: `"initFontAwesome "`, see exactly the text of your question). It's important only that you use the files `jQuery.jqGrid.fontAwesome4.css` and `jQuery.jqGrid.fontAwesome4.js` **from `plugins` folder of NEW jqGrid** (I mean from [my fork](https://github.com/OlegKi/jqGrid) of jqGrid).

If you would report bugs in the future, please include 1-3 lines of code with the error. I publish currently many changes in the day so the links like https://github.com/OlegKi/jqGrid/blob/master/js/jquery.jqGrid.src.js#L10614 will point to another line.

Best regards
Oleg

**Comment by johncze** [comment]
Hi,

thank you for your detail description. 

1) Ok, I removed `autoWidthColumns` plugin. I looked at http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnLoad1.htm demo, but it seems is different against `autoWidthColumns`, because If I will write into client column long text, then I will save row. So column won't be resizable according to his content. This behavior was implemented in autoWidthColumns plugin. Is it possible to do it now ?

2) Sorry, but I use `$("#table").jqGrid("initFontAwesome")` without space of cource. The space was mistake during copy & paste :) I use `jQuery.jqGrid.fontAwesome4.css` and `jQuery.jqGrid.fontAwesome4.js` from new jqGrid from you. But browser still throws:
```javascript
Uncaught TypeError: Cannot read property 'multiselect' of undefined
Uncaught jqGrid - No such method: initFontAwesome
```

and I don't know, because `initFontAwesome` is included before creating jqGrid this way:

```javascript
$("#table").jqGrid("initFontAwesome");
$("#table").jqGrid(myOptions);
```
and I don't understand why it is required multiselect, because old jqGrid (4.7.0) this exception didn't throw.

Ok, I will include more lines in the future.


Many thanks,

Daniel

**Comment by OlegKi** [comment]
Sorry Daniel, but you didn't included any URL to your demo, so I can't reproduce the problem. I suppose that you use jqGrid with wrong parameters or includes wrong JavaScript files.

Compare [the demo](http://www.ok-soft-gmbh.com/jqGrid/AutowidthColumn3-OK.htm) which uses new version of jqGrid with the [old demo](http://www.ok-soft-gmbh.com/jqGrid/AutowidthColumn3.htm). I don't see any problem. I included `autoResizing: { maxColWidth: 1024 }` option to increase the default `300` restriction for the maximal width of the resized column to display full texts in "Notes" column.

In the same way [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/FontAwesome4.htm) or [this one](http://www.ok-soft-gmbh.com/jqGrid/OK/navButtons2-fa4.htm) uses fontAwesome4 and I can't reproduce any problems which you describe.

So **please post always the demos which reproduces the problem if you report a problem**.

Best regards
Oleg

**Comment by johncze** [comment]
Ok, many thanks. Now it is ok. The mistake was that I still use old plugins. I removed them and now your new version of jqgrid works.
