### ISSUE TITLE
getGuiStyles is not defined exception in 2015-03-21 build

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#30]
In todays jquery.jqgrid.src.js:4782:49  exception  getGuiStyles is not defined   occurs with stack trace below.

In 2015-03-09  build this exception does not occur.

I downloaded jquery.jqgrid.src.js from master today but it contains yesterdays date in header:

 * Date: 2015-03-21
 
Uncaught ReferenceError: getGuiStyles is not defined Line 4782 Column 49ReferenceError: getGuiStyles is not defined    at HTMLTableElement.<anonymous> (http://localhost:52216/admin/Scripts/jqgrid-4.8.0/js/jquery.jqgrid.src.js:4782:49)    at Function.jQuery.extend.each (http://localhost:52216/admin/Scripts/jquery/jquery-1.11.1.js:383:23)    at jQuery.fn.jQuery.each (http://localhost:52216/admin/Scripts/jquery/jquery-1.11.1.js:136:17)    at jgrid.extend.addRowData (http://localhost:52216/admin/Scripts/jqgrid-4.8.0/js/jquery.jqgrid.src.js:4748:9)    at $.fn.jqGrid (http://localhost:52216/admin/Scripts/jqgrid-4.8.0/js/jquery.jqgrid.src.js:1608:13)    at addNewRow (http://localhost:52216/admin/Detail?_entity=DokG&_id=130632&_vmnr=&_isik=:829:15)    at HTMLTableElement.$grid.jqGrid.loadComplete (http://localhost:52216/admin/Detail?_entity=DokG&_id=130632&_vmnr=&_isik=:647:38)    at finalReportVirtual (http://localhost:52216/admin/Scripts/jqgrid-4.8.0/js/jquery.jqgrid.src.js:3190:18)    at Object.$.ajax.$.extend.success (http://localhost:52216/admin/Scripts/jqgrid-4.8.0/js/jquery.jqgrid.src.js:3222:8)    at fire (http://localhost:52216/admin/Scripts/jquery/jquery-1.11.1.js:3119:30)

**Comment by kobruleht** [comment]
Creating global function

```javascript
var getGuiStyles = function (jqClasses, path) {
    return '';
};
```

removes exception but in this case row numbers appear in jqgrid. If dynamic row number column switching is used, row numbers should initially turned on and disabled after in code. Using this fix row number column is not disabled

**Comment by OlegKi** [comment]
Thank you! The bug should be fixed now (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/77b21dd374fe8ef1943aefba181a60fa3b0839e3)).

The new `guiStyle` option (with default value `"jQueryUI"`) allows to specify classes used by jqGrid components. It will be close to `iconSet` option. The default option `guiStyles: "jQueryUI"` should set the same jQuery UI CSS styles like before. The feature is not yet full implemented (only in base module).

**Comment by kobruleht** [comment]
Thank you. How to use guiStyle to replace jquery UI with twitter bootstrap ?

**Comment by OlegKi** [comment]
**The feature is still in developing**. Later one will be able to use the code like 
````
$.extend(true, $.jgrid.guiStyles, {
    bootstrap: {
        ...,
        hTable: "table table-bordered table-hover",
        grid: "table table-condensed table-bordered table-hover table-striped",
        ....
    }
});
````
one will be able to define new style `"bootstrap"`. One can then use `guiStyle: "bootstrap"` option to apply the style. So all will work close to [creating of custom iconSet](https://github.com/free-jqgrid/jqGrid/wiki/Using-Font-Awesome-in-free-jqGrid-4.8#creating-of-custom-iconset)
