### ISSUE TITLE
New feature generateValue: true 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#300]
New feature generateValue: true  not work with data load from server.
Pls. see http://jsfiddle.net/6n3gakf0/

**Comment by OlegKi** [comment]
I think that there is a small misunderstanding about `generateValue: true`. It generate the index of **local** data. If one loads only *one page* of data, then jqGrid is unable to generate the full list of all unique values in the column. One can use  `generateValue: true` in `loadonce: true` scenario like in modified demo http://jsfiddle.net/OlegKi/6n3gakf0/3/, but one can't use the feature without holding local data.
