### ISSUE TITLE
Auto-adjustable responsive columns 

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#303]
I am trying to create a responsive jqgrid which has width equals to the 100% width of the parent DIV. I need that the width of the columns were automatically adjusted on grid loading in order to adjust column width on the content of each column. The grid is dynamically generated so it has no predefined number of columns.
Here, a screenshoot of the comparison between AS IS and TO BE:
![picture2](https://cloud.githubusercontent.com/assets/26380480/24209230/fdd80c14-0f25-11e7-89f4-b369b78dd88a.png)

I tried by adding the following methods to my jqgrid but it does not work:

```
cmTemplate: { autoResizable: true },
autoResizing: { compact: true },               
autoresizeOnLoad: true,
```
Is there any specific method that I could use to auto-adjust the column width?

**Comment by OlegKi** [comment]
It seems that you have the question, which is very close to [the old issue 289](https://github.com/free-jqgrid/jqGrid/issues/289). I suggest you to try the demo https://jsfiddle.net/OlegKi/ejpn9/149/, which is small modification of https://jsfiddle.net/OlegKi/ejpn9/140/ (published for the issue 289), which uses the following jqGrid options
```JavaScript
cmTemplate: { autoResizable: true },
autoResizing: { compact: true, resetWidthOrg: true },
autowidth: true,
autoresizeOnLoad: true,
```
Additional it uses
```JavaScript
var maximizeGrid = function() {
        var newWidth = applicationGrid.closest(".ui-jqgrid").parent().width();
        applicationGrid.jqGrid("setGridWidth", newWidth, true);
    };
$(window).on("resize", maximizeGrid);
```
I hope, it provides the solution of your problem.

**Comment by Flanders89** [comment]
Thnaks. `resetWidthOrg` is what I was looking for my issue. I add `resetWidthOrg` and now it works perfectly.
