### ISSUE TITLE
Translations hr, ba

### ISSUE THREAD

**Issue by Nimesin-Boxmark** [free-jqgrid/jqGrid#306]
Hello,

What I need to do to commit translations fixes in croatian and bosnian language?
(attachment)

[i18n hr and ba.zip](https://github.com/free-jqgrid/jqGrid/files/864835/i18n.hr.and.ba.zip)

**Comment by OlegKi** [comment]
Thank you!

One can post pull request with the changes to https://github.com/free-jqgrid/jqGrid/pulls, but it's not required. I committed your changes [here](https://github.com/free-jqgrid/jqGrid/commit/648c0f388278be7ce3f8303af9e122c5372ca866).

By the way, is msajko@gmail.com your email address? You can post me your name and optionally email, which I could add in the license statement of the files `grid.locale-hr.js` and `grid.locale-bs.js`.

**Comment by Nimesin-Boxmark** [comment]
no, it is not my email :) 
I didnt change that line.

You can change it to info@nimesin.com and name to Nimesin

Thank you

**Comment by OlegKi** [comment]
Thanks! I added the information to the files (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/8b0baf747ee6058020dbca60d713e898c8250943)).
