### ISSUE TITLE
Invalid target element for this operation in Internet Explorer 9 (regresson)

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#31]
In IE9 in 2015-03-22  build line 2740 

self.firstElementChild.innerHTML += rowData.join(''); 

in IE 9 causes exception

Invalid target element for this operation

jqGrid 4.6  worked without issue.

I looked in debugger but found that all properties are defined:

![invalidtarget](https://cloud.githubusercontent.com/assets/1274923/6829599/1e5624c2-d31d-11e4-99be-3626ee878b76.png)

**Comment by kobruleht** [comment]
IE8 branch of this code is not executed

**Comment by OlegKi** [comment]
could you verify that you have the same problem with the current sources from github. You can use `<link rel="stylesheet" href="//rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css">` and `<script src="//rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js"></script>` for the quick test.

**Comment by kobruleht** [comment]
I copied just jquery.jqgrid.src from github and verified that problem persists. Its date is 22 March and github shows that last chenge was 3 days ago so this was probably the same file which I used when reporting it.

**Comment by OlegKi** [comment]
I hope that I fix the bug finally. Please retry with the latest sources from GitHub.

**Comment by kobruleht** [comment]
It is working now. Thank you.

**Comment by OlegKi** [comment]
Thank you too for reporting the bug.
