### ISSUE TITLE
keep responsive column width on resize and scroll

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#311]
Hi,
I'd like to have a grid fitting inside a parent container to display an horizontal scroll bar if the grid has too many columns and to have the width of its columns proportionate to the data inside.
I used 
```JavaScript
cmTemplate: { autoResizable: true }, 
autoResizing: { compact: true, resetWidthOrg: true, minColWidth: 80 },
autoresizeOnLoad: true, 
```

to make each columns as big as its data, while keeping a minimum size even if it's empty.
It works but the grid ignores the `minColWidth` and forces some columns to be smaller than my given width to keep the table the same size as the parent container.

Another issue is that I'm using `scroll:1` and every time I scroll past the `rowNum` the width gets recalculated and changes according to the new data inside the table but I'd prefer to keep the same layout from the first load.

**Comment by OlegKi** [comment]
Thank you for pointing on the problem with `minColWidth` during autoresizing of the whole grid. I will fix the problem in the next days.

The usage of `scroll:1` is **not recommended**. You should use the standard paging of the data using bottom or top pager (or both).

**Comment by bolzo5** [comment]
ok, thank you,
I understand that is not recommended but I need the infinite scroll on this grid, so can you help me about that? Is there any other way to get it without using scroll:1 ? if not can I use some event  to set the older layout again?

**Comment by OlegKi** [comment]
I don't understand what you mean under "the older layout". The option `scroll:1` was buggy and have many restrictions. You can examine "Limitations" of old jqGrid documentation (like [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:grouping#limitations)) and find the requirement don't use `scroll` option. If you want to use `scroll:1` than you can't uses a lot of features of jqGrid. Just don't use it and use the standard pager. In other words, the option `scroll` is deprecated in free jqGrid.
