### ISSUE TITLE
Jqgrid event on Column sort click

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#313]
There is any jqgrid  event fired on the sorting icon click?

**Comment by OlegKi** [comment]
It's [onSortCol](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/ts/free-jqgrid.d.ts#L1139) callback or [jqGridSortCol](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/ts/free-jqgrid.d.ts#L1963) event. One can return `false` or `"stop"` from the callback or from the event to prevent sorting.

**Comment by Flanders89** [comment]
thank you!
