### ISSUE TITLE
Store columns width at paging

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#316]
I'm facing an issue when I'm trying to keept the same columns width in all the different jqgrid pages calling a function at load complete event, but unfortunately it works only for the fisrt column and not for the other columns (I cannot set a fixed width when I create the table because I load data from database dynamically)
```JavaScript
gridComplete: function () {
        reDefineColWidth();                       
 },

function reDefineColWidth() {
    var columnWidths = '400px|408px|175px|140px|200px|75px|140px|150px|130px|220px|125px|230px|200px|111px'
    var widthsArr = columnWidths.split('|');
    for (var j = 0; j < widthsArr.length ; j++) {
        $('.ui-jqgrid-labels > th:eq(' + j + ')').css('width', widthsArr[j]); // will set the column header widths
        $('#grid tr').find('td:eq(' + j + ')').each(function () { $(this).css('width', widthsArr[j]); }) // will set the column widths
    }
}
```
do you know why?

**Comment by OlegKi** [comment]
Sorry, but your code seems be wrong. I don't full understand what you want to implement, which kind of grid you use (TreeGrid, data grouping and so on) and which options of the grid you use. The option `shrinkToFit: false` inform jqGrid to use the `width` values for columns, which you specified in `colModel`. No other code is required. In any way, manual setting of width via CSS is wrong. If you need to change the column width dynamically then you should use `setColWidth` method.

By the way, the usage of `gridComplete` callback is bad idea in the most cases. The callback `loadComplete` is better in almost always better. One should use `gridComplete` callback only to set some information in the pager. See [the old answer](http://stackoverflow.com/a/15439276/315935) for more detaile.

**Comment by Ant02** [comment]
I just added a demo https://jsfiddle.net/Ant02/01th999n/4/
I want that columns in all pages have the same size of columns at page 1 and as you can see ID column width is different betwenn page 1 and 2.
My problem it that I can not set the width in the colModel because I need to adapt the column width at the text size but once that we have this size in the first page I wanna apply it to all the page of the grid.
Is something that I can do?

**Comment by OlegKi** [comment]
Now I understand the problem. You don't wrote before that you use `autoresizeOnLoad: true` option.

You can solve the problem very easy. You need just set the value of `autoresizeOnLoad` dynamically inside of `loadComplete` based on the current page number. Only if the `page` parameter is 1 you set `autoresizeOnLoad: true`. The option `autoresizeOnLoad` will be processed by jqGrid **after** `loadComplete`. Thus such changing of `autoresizeOnLoad` will work. See https://jsfiddle.net/OlegKi/01th999n/5/

**Comment by Ant02** [comment]
It works, Thanks!
