### ISSUE TITLE
Show Loading Icon during the update line operation

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#317]
I'm still using the jqgrid that I mentioned in previous question, my problem now is that:
 at save of a line I have a lot of validations for each field, so during these validations there is a way to show a loading icon so I can prevent that user will do something on the jqgrid during these validations?

**Comment by OlegKi** [comment]
Please post always some code, which describes the problem. How you implemented the validation? Which editing mode you use (inline editing, form editing, cell editing)?

**Comment by Ant02** [comment]
here you will see an exmple
https://jsfiddle.net/Ant02/01th999n/6/

I added comment (//here I wanna show a loading icon) where I wanna add the loading icon and a comment  (//here there is a call to a webmethod that will do all the validations on code behind) where I call a method for all validations

let me know if is possibile to show a loading when system is performing all validations

**Comment by OlegKi** [comment]
One can use `this.grid.beginReq.call(this);` to show the standard loading text or blocking the grid (if `loadui: "block"` option are used) and `this.grid.endReq.call(this);` to hide it. See https://jsfiddle.net/OlegKi/01th999n/7/. Nevertheless you will have the problem with **asynchronous** requests to the server.

I suppose that you not full understand the interface to `editurl`, which jqGrid use. The URL will be used not only for successful saving of data. The Ajax request can return an error HTTP code and include the error description in the response body. jqGrid will display the error message and the edit mode will be hold. In other word, `editurl` is the interface for **server side validation** *and* saving the data if the validation is successful. `errorfunc` option of inline editing can be used additionally to parse the server response and to generating the error message. The callback `saveRowValidation` and `editrules` options are introduced for the *client side validation*.

**Comment by Ant02** [comment]
do you have a link where I can check a jqgrid example that is using editurl and errorfunc ?

**Comment by OlegKi** [comment]
The most easy example you will see on https://jsfiddle.net/OlegKi/01th999n/8/, where I just added `editurl: "/anyDummyUrl/"` option and the following options of inline editing:
```JavaScript
restoreAfterError: false,
errorfunc: function (rowid, jqXHR, textStatus, errorThrow) {
    alert("Error: " + jqXHR.statusText + " (" + jqXHR.status + ")");
}
```
One makes request to not existing URL and receive the HTTP response with the status code 404. Thus the `errorfunc` will be called.
One can use `$.jgrid.info_dialog` to display the error message in the style used by jqGrid:
```JavaScript
errorfunc: function (rowid, jqXHR, textStatus, errorThrow) {
    //alert("Error: " + jqXHR.statusText + " (" + jqXHR.status + ")");
    $.jgrid.info_dialog.call(this,
        "Error is saving of row with rowid=" + rowid,
        "<p>" + jqXHR.statusText + " (" + jqXHR.status + ")</p>",
        "Close",
        { buttonalign: "right" }
    );
}
```
See https://jsfiddle.net/OlegKi/01th999n/9/

**Comment by Ant02** [comment]
Sorry a last question, to pass to my webservice the edited line values and some additional parameters  I need to specify it also in editUrl or there is an other specific parameter where I have to specify them?

**Comment by OlegKi** [comment]
It seems be new question. There are many ways to send additional parameters to `editUrl`:

1. the usage of `extraparam`, which properties can be defined as functions if the value is dynamic.
2. the usage of `url` of `inlineEditing` (or `editUrl`) defined as callback function. It allows to add any parameter, which will be the part of URL.
3. the usage of `beforeSaveRow` to modify parameters of `saveRow` (to modify the `url` for example or to modify `extraparam`).
4. the usage of `serializeRowData` callback, which allow to extend or to modify the data or to change the format of the data to JSON for example. The last approach don't allow to change the URL dynamically, but because HTTP POST or HTTP PUT be typically used for editing of data, the parameters will be send in the *body* of HTTP request and `serializeRowData` get you full control over the data.

**Comment by Ant02** [comment]
It works thanks!
