### ISSUE TITLE
form-edit, dynamic input control

### ISSUE THREAD

**Issue by alpastar** [free-jqgrid/jqGrid#318]
one have  add/edit form which include nation,state,city input 
where nation is (always) select option 

if  selected nation is 1(first) 
 then state and city input should become select option 
if not,  state and city input should become text input 

is there any possibility to acheive this goal ? 

here is my code 
```JavaScript
colModel: [
   { name:"nation" 
     ,label:"nation"
     ,formattype:'select'
     ,edittype:'select'
     , editoptions: { 
       value: go_addr_nation
       , dataEvents:[
        { type: 'keyup' , fn:function(e) {$(e.target).trigger('change'); }  }, 
        { type: 'change', fn:function(e) { 
            change_state($(e.target).val(),e.target); } }
       ] 
    }
   },

   { name: "state"  , label: "state"    },
   { name: "city"   , label: "city"     },
  ....
]
```

**Comment by OlegKi** [comment]
jqGrid (and free jqGrid) don't contains any perfect built-it implementation of dependent selects. I recommend you to read [the old answer](http://stackoverflow.com/a/4480184/315935), which provides [the demo](http://www.ok-soft-gmbh.com/jqGrid/EditWithDependendSelects2_.htm) as an example of one possible implementation.

**Comment by OlegKi** [comment]
@alpastar : Please, close the issue or post some additional information.

**Comment by OlegKi** [comment]
@alpastar : The issue staying opened since a long time without any feedback from your side. I'm closeing the issue now. You can reopen it or post new issue with more details about the problem.
