### ISSUE TITLE
inlineEditing Add row with grouping: true

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#319]
(version jqgrid-4.13.6)
Using option "grouping: true" in conjunction with inlineEditing, when you click the "ADD" button, the new row appears bellow the first group title, and all the grouped rows are messed up.
(images attached)

![grid add 1](https://cloud.githubusercontent.com/assets/11968628/25059425/f5154aee-215c-11e7-80ce-ff32f74ff270.jpg)
![grid add 2](https://cloud.githubusercontent.com/assets/11968628/25059424/f5155b9c-215c-11e7-8cb8-e1f17e1c0ba5.jpg)

**Comment by OlegKi** [comment]
Thank you for reporting of the bug! I committed [the fix](https://github.com/free-jqgrid/jqGrid/commit/f80827fa1cbb53916e41df71ab6a17c06edae002) just now. Please confirm that the new code fix the problem and close the issue finally.

I recommend you to reload the grid after adding the row to place the new row in the correct group. One should place `.trigger("reloadGrid")` inside of `setTimeout(function () {/*here*/}, 0);` to allow the adding of data will be finished before the reload will be started.

**Comment by aberel** [comment]
Oleg, your welcome!  I will try the fix and tell if it works.
I always use to realod the grid after add or edit any row.
Regards.

**Comment by aberel** [comment]
Oleg, all the fixes you apply are on the last version of jqrid?
My problem is I'm in version 4.13.6 and don't want to upgrade version by now (I plan to upgrade in the future, but you know I have to test all my wrapper every time I upgrade version)
So, my only solution for these fixes is to copy the piece of code and edit my local jqgrid.js file, which is a bad idea, I know that :-(

**Comment by aberel** [comment]
I tried the patch and works ok!!
