### ISSUE TITLE
Show Loading Icon during a request AJAX 

### ISSUE THREAD

**Issue by cptaimless** [free-jqgrid/jqGrid#325]
Hi,
I want to use the beginReq and endReq, but i have the error : 
> self.grid is undefined

I call the function by this line :
`$("#jqGrid_home")[0].grid.beginReq();`

I don't understand my mistake. however this line of code is working :
`console.dir($("#jqGrid_home")[0].grid);` 

Can you help me please ?

Regards,

**Comment by OlegKi** [comment]
It's important correctly initialize `this` on calling of `beginReq` or `endReq`. The correct usage will be the following:
```JavaScript
var domOfGrid = $("#jqGrid_home")[0];
domOfGrid.grid.beginReq.call(domOfGrid);
...
domOfGrid.grid.endReq.call(domOfGrid);
```

**Comment by cptaimless** [comment]
yes, yes !!! I found my mistake... And I'm reading your answer !!! :)
The good way is :
`$("#jqGrid_home")[0].grid.endReq.call($("#jqGrid_home")[0]);`

Thank you very much for your quick response ... and your work!

**Comment by cptaimless** [comment]
It works :+1:
