### ISSUE TITLE
Initialization with multisort and spaces in column names gets wrong parsed

### ISSUE THREAD

**Issue by Manu-san** [free-jqgrid/jqGrid#329]
e.g.
```javascript
...
options.multiSort = true;
options.sortname = 'col one asc, col two asc, col three';
options.sortorder = 'asc';
domElem.jqGrid(options);
```
does not activate sort of any column.
After some debugging, the problem may be at this code
```javascript
if (p.multiSort) {
  sortarr = p.sortname.split(",");
  var iSort;
  for (iSort = 0; iSort < sortarr.length; iSort++) {
    sotmp = trim(sortarr[iSort]).split(" ");
    sortarr[iSort] = trim(sotmp[0]);
    sortord[iSort] = sotmp[1] ? trim(sotmp[1]) : p.sortorder || "asc";
  }
}
```
results in 
```javascript
sortarr = ['col', 'col', 'col']
sortord = ['one'. 'two', 'three']
```

Or is it just not permitted to use spaces in colModel names?

**Comment by OlegKi** [comment]
The `name` properties of `colModel` have to be unique (different columns have to have different values) and the value of `name` properties have to hold the restrictions of `id` attribute in HTML. **HTML5 don't allows to use spaces in `id`** (see [the part](https://www.w3.org/TR/html5/dom.html#the-id-attribute) of HTML specification). It's strictly recommended don't use other symbols which have special meaning in CSS, like commas, dots, `*` and so on.

I suppose that you mix the `colNames` with the `name` property of `colModel`. The user sees not the `name`. The user sees only the column label, which one specifies in `colNames` or in `label` property of `colModel` (if no `colNames` is specified). If spaces exist in JSON/XML input of the grid, then one can use `jsonmap` to read the data. In all cases one can use `name` properties without spaces.

**Comment by OlegKi** [comment]
I don't received any response on my previous comment. Please close the issue if the question is cleared now.
