### ISSUE TITLE
Add new row button does not add new row on first click

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#33]
Steps to reproduce:

1. Open http://www.ok-soft-gmbh.com/jqGrid/OK/dateInput_48_.htm  (from http://stackoverflow.com/questions/29194381/how-to-use-native-date-picker-in-both-form-and-row-editing-in-free-jqgrid answer ) in latest desktop Chrome.
2. Click in add new row button in toolbar

Observed:

Grid flashes and new row does not appear. New row appers only after second click. Maybe it is related to https://github.com/free-jqgrid/jqGrid/issues/21

**Comment by OlegKi** [comment]
Thank you for the bug report. The problem is in the demo and not in the code of free jqGrid. The code of `onSelectRow` should be like
```JavaScript
onSelectRow: function (rowid) {
    var $self = $(this),
        savedRow = $self.jqGrid("getGridParam", "savedRow");
    if (savedRow.length > 0 && savedRow[0].id !== rowid) {
        $self.jqGrid("restoreRow", savedRow[0].id);
    }
    $self.jqGrid("editRow", rowid);
}
```
instead of
```JavaScript
onSelectRow: function (rowid) {
    var $self = $(this),
        savedRow = $self.jqGrid("getGridParam", "savedRow");
    if (savedRow.length > 0) {
        $self.jqGrid("restoreRow", savedRow[0].id);
    }
    $self.jqGrid("editRow", rowid);
}
```
I have fixed the demo.

**Comment by kobruleht** [comment]
Thank you. It is working now.
