### ISSUE TITLE
Performance improvement point

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#330]
In my scenario, the isCellClassHidden function costs a lot of cpu usage, as the following chart see.
![image](https://cloud.githubusercontent.com/assets/11850439/25833365/539b94a2-34a3-11e7-85ab-8223f2c790be.png)

Add an option to disable isCellClassHidden call will improve the performance a lot, any consideration?

**Comment by OlegKi** [comment]
**Could you describe more clear what you measure, what grid you used and so on.?** Do you want to improve the performance of filling the grid, the performance of resizing, ...? Which version of jqGrid and jQuery UI you used? Which version of free jqGrid you used for your tests? Do you use `classes` property in `colModel`? I can continue...

Please, describe the problem in details. It's better to prepare **the demo** and describe the test case (step by step instruction to reproduce the problem).

The method `$.jgrid.isCellClassHidden` was introduced for responsive scenario like in the demo http://jsfiddle.net/OlegKi/andm1299/26/. Try to resize the window with the grid and you will see that the last column `ComboDuration` will be hidden or visible depend on the width of the window.

You can overwrite `$.jgrid.isCellClassHidden` method by usage the code like
```
$.jgrid.isCellClassHidden = function () { return false; };
```
On the other side it would be interesting to improve the performance of jqGrid. It's interesting for me to optimize the code, but I need more details about your tests.

**Comment by OlegKi** [comment]
Please post additional information about the reported problem or close the issue. I'd like to improve performance of free jqGrid, but I can analyse the problem only if I can reproduce it.

**Comment by ryanlin1986** [comment]
Sorry for the delayed reply,  solved the performance problem by following code:
`                        var isCellClassHidden = $["jgrid"].isCellClassHidden;
                        $["jgrid"].isCellClassHidden = function (className) {
                            if (className == null)
                                return false;
                            return isCellClassHidden(className);
                        }`

This optimization is just enough for me.

**Comment by OlegKi** [comment]
Thank you for the feedback! I included your suggestions in [the fix](https://github.com/free-jqgrid/jqGrid/commit/a1a5cf5356863db006e10e6bc67a5426b9cdd6b1), which I posted to GitHub.
