### ISSUE TITLE
filterToolbar

### ISSUE THREAD

**Issue by resistorsoftware** [free-jqgrid/jqGrid#332]
I added a filterToolbar to my grid. I see the callback to the server sends the column that was selected. The data contains no indication that this _search=true data is for filtering. 

EXPECTED:   filter: { "some_column" => "foosbar" }
RECEIVED: /my_route?_search=true&nd=1494352780968&rows=50&page=1&sidx=name&sord=desc&some_column=FE"

Any clue as to why the request for data does not use some key like filter?

**Comment by OlegKi** [comment]
Please post the JavaScript code , which you use or better post the demo, which can be used to reproduce the problem. Write always the version of free jqGrid, which you used.

The parameters, which you posted do contain `_search=true` *and* `some_column=FE`, which is the expected filter. 

jqGrid provide multiple searching/filtering modes. One can see that you use the oldest mode of `filterToolbar`, which send the filter information in the form `colOrIndexName=searchingValue`. Another, more recent form can be enabled by using `stringResult: true` parameter of `filterToolbar`. One can additionally use `searchOperators: true`, to allow the user to choose searching operation used in the filtering by the column. The mode `searchOperators: true` force sending `filters` parameter to the server with full information encoded in the same format like for Advanced Searching (see [here](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:advanced_searching#options)). As the result you can implement parsing of the information on the server side and building WHERE clause for the filtering of the data.

Another way, which is recommended by not so large dataset (<1000 or <10000 rows), is the usage of `loadonce: true` which can be combined with `forceClientSorting: true` option. As the result the server should return **all the data**. The `datatype` will be changed to `"local"` automatically after loading the data and later sorting, paging and filtering/searching of data will be made by jqGrid internally on the client side. I recommend you to try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-15-60000-25-free-jqgrid.htm), which fill the grid with 60000 rows and 15 columns. The demo displays the time of sorting, paging and filtering. Reducing the page size to 10, for example, increase the performance: see [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-15-60000-10-free-jqgrid.htm). Reducing the numbers of rows from 60000 to 5000 (see [one more demo](http://www.ok-soft-gmbh.com/jqGrid/OK/performane-15-60000-25-free-jqgrid.htm)), holding the page size as 25, increase the performance too. The option `forceClientSorting: true` allows to sort and to filter the data loading from the server *on the client side* before displaying the first page of data.

Thus I recommend everybody to consider to use `loadonce: true` and `forceClientSorting: true` option before implementing complex server side code. The round trip of the request to the server, for the filtering the data, could be longer as local sorting.

**Comment by resistorsoftware** [comment]
I added that parameter.. saw no change in the sent data:

search: true,
stringResult: true,
searching: {
  defaultSearch: "cn"
},

and ending my setup with .jqGrid('filterToolbar');

**Comment by resistorsoftware** [comment]
Ahhh. I see... added to the actual call to jqGrid... and things change... 

Parameters: {"_search"=>"true", "nd"=>"1494359130328", "rows"=>"50", "page"=>"1", "sidx"=>"name", "sord"=>"desc", "filters"=>"{\"groupOp\":\"AND\",\"rules\":[{\"field\":\"status\",\"op\":\"cn\",\"data\":\"mapped\"}]}"}

**Comment by OlegKi** [comment]
You can specify any options of `filterToolbar` or `searchGrid` (searching dialog) **inside** of `searching` parameter of jqGrid. For example,
```JavaScript
searching: {
    stringResult: true,
    searchOperators: true,
    defaultSearch: "cn",
    multipleSearch: true,
    multipleGroup: true,
    closeOnEscape: true,
    searchOnEnter: true
}
```
Placing of `stringResult: true` as the option of jqGrid (not as the option of `filterToolbar`) **outside of** `searching` (see your first post) is wrong.

**Comment by resistorsoftware** [comment]
Coo.. thanks.. with this, a server-side parser can be built.

**Comment by OlegKi** [comment]
Please close the issue after your question will be cleared. You still not posted the approximative number of rows in the grid. I remind you that, you could spend many time in implementing server side filtering, which will work finally more slowly as the simplest client side filtering. Think about writing the server-side code so that it will be safe for security problems like SQL Injection (see [here](https://www.owasp.org/index.php/SQL_Injection) for example). Thus, one should *always* consider and to test the usage of `loadonce: true` and `forceClientSorting: true` before implementing server side filtering.

**Comment by resistorsoftware** [comment]
I will work on the loadonce concept once I master the conventional one. I doubt I will ever be dealing with more than 1000 rows in any particular session, but over time, a view of ALL records could easily exceed a big number (> 50,000 etc)... so yes, will be fun to move one. 

THANK YOU. You are an excellent host.

**Comment by OlegKi** [comment]
You are welcome!
