### ISSUE TITLE
 jqGrid warning dialog position

### ISSUE THREAD

**Issue by springbok** [free-jqgrid/jqGrid#333]
Hi Oleg,

Thank you for your continued work with this great component.

We have a number of grids on a page, to access some of these the user needs to scroll down the page. If they then try and do an edit for example without selecting a record, the warning dialog makes the page scroll up to the top and then displays, this causes the grid that they were working on to be hidden as it's no longer on the page.

Is there some way that this dialog can display over the top of the grid that caused the warning?

Thanks,

Etienne.

**Comment by OlegKi** [comment]
Hi Etienne,

it would be good it you write always, which version of free jqGrid you use and with which CSS framework (jQuery UI or Bootstrap). Moreover it could be important which version of jQuery you use and whether the grids (jqGrid grids) will be created inside of some absolute positioned elements or not. It's very helpful if you would post the demo, which can be used to reproduce the problem, which you describe.

I can't test your scenario, but I advice to use to try to add `alerttop` and `alertleft` options to `navGrid`. You can for example, you can add jqGrid option like
```JavaScript
navOptions: {
    alerttop: 100,
    alertleft: 10
}
```

Best regards
Oleg

**Comment by springbok** [comment]
Hi Oleg,

Thank you for your prompt response, I'm using the latest version of jqgrid & jquery with Bootstrap 4 alpha 5. Grids are created within a Bootstrap card and does not use absolute positioning.

After a lot more searching I came across this article which describes my problem and offers a solution:

[http://stackoverflow.com/questions/11719349/jqgrid-warning-please-select-row-position](url)

When using the code it was still not working with the latest version of jqgrid so after looking at the jqgrid code in particular:

```
if (options.toTop && h.o) {
	parentOffset = h.w.parent().offset();
	left = parseFloat(h.w.css("left") || 0);
	top = parseFloat(h.w.css("top") || 0);
	h.w.before('<span id="jqmP' + h.w[0]._jqm + '"></span>')
		.insertAfter(h.o);
	h.w.css({ top: parentOffset.top + top, left: parentOffset.left + left });
}
```
I modified the solution to the following and it now works:

```
var orgViewModal = $.jgrid.viewModal;
$.extend($.jgrid, {
  viewModal: function (selector, o) {
    if (selector.indexOf('#alertmod') >= 0) {
      var $gbox = $(o.gbox), $selector = $(selector);
      var of = $gbox.offset(), w = $gbox.width(), h = $gbox.height();
      var w1 = $selector.width(), h1 = $selector.height();
      $selector.css({
        'top': 0,
        'left': ((w-w1)/2)
      });
    }
    orgViewModal.call(this, selector, o);
  }
});
```
The modal alert is now displayed correctly on top of the correct grid. Not sure if there is a better way of doing this but it seems to work ok.
