### ISSUE TITLE
rowNum with grouping not working

### ISSUE THREAD

**Issue by Globulopolis** [free-jqgrid/jqGrid#334]
Hi!
I'm try to port from original jqgrid 4.7.0 to latest free jqgrid. Everything seems to be Ok, but I'm stuck on grouping. I need to display all rows but free jqgrid display only 25. rowNum isn't working at all because any values do not change the number of displayed results.

Maybe I'm something missed in configuration?
PS! On old 4.7.0 everything fine with rowNum(it's set to 0 and display all rows).

**Comment by OlegKi** [comment]
Please provide **the demo**, which reproduces the problem. All my tests have no problems with `rowNum`. I suppose that you specify `rowNum: 25` somewhere in your code, because free jqGrid has no such setting.

**Comment by Globulopolis** [comment]
@OlegKi thank you. A fresh look solved the problem.
