### ISSUE TITLE
cmTemplate not working

### ISSUE THREAD

**Issue by Xento** [free-jqgrid/jqGrid#335]
Hello,
I want to disable the clearSearch button in the filter toolbar for all grids.
So I added this to the top of my js-file:
`jQuery.extend(jQuery.jgrid.defaults, {
	    cmTemplate: {
	        searchoptions: {
	            clearSearch: false
	        }
	    }
	});`
This doesn't seem to work. 
I although tried to add it within the document-ready function but this don't works either.
When I add the cmTemplate part directly to the grid, it works.

Where is my mistake?
Is it a bug?

**Comment by OlegKi** [comment]
Sorry, but I can't reproduce the problem, which you reports. The demo https://jsfiddle.net/OlegKi/yvbt6w54/1/ for example displays "x" buttons in the filter toolbar. Adding of the line, which you posed above the code follows to results, which one can see on the demo  https://jsfiddle.net/OlegKi/yvbt6w54/15/. One can see that the only "x" button, which exists now, is in the Client column (with `name: "name"`), where `clearSearch: true` specified explicitly. `cmTemplate` specifies **default** settings, which can be overwritten by explicit settings in `colModel`.

Could you provide your demo, which reproduces the problem? You can use my demo as the basis and modify it so , that one can see the problem.

**Comment by Xento** [comment]
I found the error:

`$.jgrid = {
	defaults: {
		cmTemplate: {
			searchoptions: {
				clearSearch: false
			}
		}
	}
};`

I added this in an other file which is included to the page and this seems to break the default, because ists wrong.

I removed it and now it works.

**Comment by OlegKi** [comment]
I'm not sure, what you mean. The code, which you posted in your last comment is definitively wrong. If you don't want to use `jQuery.extend`, then you could use something like the following:
```JavaScript
$.jgrid = $.jgrid || {};
$.jgrid.defaults = $.jgrid.defaults || {};
$.jgrid.defaults.cmTemplate = { searchoptions: { clearSearch: false } };
```
or like
```JavaScript
$.jgrid = $.jgrid || {};
$.jgrid.defaults = $.jgrid.defaults || {};
$.jgrid.defaults.cmTemplate = $.jgrid.defaults.cmTemplate || {};
$.jgrid.defaults.cmTemplate.searchoptions = $.jgrid.defaults.cmTemplate.searchoptions || {};
$.jgrid.defaults.cmTemplate.searchoptions.clearSearch = false;
```
In any way I don't see any issue in the code of free jqGrid.

You still don't closed the issue. Do you have still some unsolved problems? Please close the issue if the problem is solved.

**Comment by Xento** [comment]
No I don't have any other issues.
This was my first try to set the default options until I found the correct syntax.
