### ISSUE TITLE
Add event parameter of jqgrid event

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#336]
In firefox, window.event is undefined in event, for exmaple
onSortCol: function (index, iCol, sortorder) {
      var check=typeof window.event==="undefined";
}
It would be great if we can access event object in event.

**Comment by OlegKi** [comment]
I'm not  sure **why** you could need to have the event object. If you provide an example of the usage the event I could extend the option of `onSortCol` with additional event parameter.

**Comment by ryanlin1986** [comment]
For example, I want implement custom sort logic, such as , when event.ctrlKey is true, then treat it as multi-sort,  instead of using built-in sort logic.

**Comment by OlegKi** [comment]
It sounds reasonable. I made the corresponding changes in the code of free jqGrid (see [here](https://github.com/free-jqgrid/jqGrid/commit/053ad4fedad3f731bb9f7761afbf3bd3d8c9c2de) and [here](https://github.com/free-jqgrid/jqGrid/commit/583e85cd8e4c847c22fdb416b25c42685be3086e)). The callback `onSortCol` and the event `jqGridSortCol` contains now one more parameter, which represent the Event object of the click event.

Please be carefully in the implementation of your callback `onSortCol`. I can imagine situations, when the event object is undefined (the corresponding parameter will be initialized to empty object in the case). I mean that the event parameter is always Event of the click in the standard case (the click on the column header), but the same callback could be executed in some cases by call of public `sortData` method (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.base.js#L6011)).
