### ISSUE TITLE
Reloading filters and sorting

### ISSUE THREAD

**Issue by bolzo5** [free-jqgrid/jqGrid#337]
Hi, 
I'm trying to reload the filters, sorting and the last page viewed before unloading the grid.
To do this I'm using the following code to save the parameters:
 ```
gridStatus.postData = grid.jqGrid('getGridParam', 'postData');
    gridStatus.sortName = grid.jqGrid('getGridParam', 'sortname');
    gridStatus.sortOrder = grid.jqGrid('getGridParam', 'sortorder');
    gridStatus.page = grid.jqGrid('getGridParam', 'page');

---

 grid.jqGrid('setGridParam', { postData: gridStatus.postData, search: true });
        grid.jqGrid('setGridParam', { sortname: gridStatus.sortName });
        grid.jqGrid('setGridParam', { sortorder: gridStatus.sortOrder });
  grid.jqGrid('setGridParam', { page: gridStatus.page });
        grid.trigger("reloadGrid");
```
Everything is working good, but when I set the sortorder, the grid doesn't apply the sorting icon, it remains in display:none,

**Comment by OlegKi** [comment]
Sorry, but you should post **more details**. First of all it's unclear which version of free jqGrid you use, which kind of grid you use and with which parameters (`datatype` and so on). Do you try to reload the data from the server or to make *local* reloading?...

I can analyse the problem only if I can reproduce the problem. Thus, please, create the demo, which reproduces the problem. I could debug it and to fix the problem either in the code of free jqGrid or in the code of your demo.

The code fragments, which you sent, shows only some small problems. First of all you set `page` parameter in the wrong way. Triggering of `reloadGrid` without additional parameter will reset the `page`. Making many calls of `setGridParam` to set different parameters is ineffective too. You can use one call of `setGridParam` or `getGridParam` and one call of `reloadGrid` with parameter `{ page: gridStatus.page }` (see [the old answer](https://stackoverflow.com/a/3808014/315935) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/ts/free-jqgrid.d.ts#L773-L777)). The code could be
```JavaScript
grid.jqGrid('setGridParam', {
    postData: gridStatus.postData,
    search: true,
    sortname: gridStatus.sortName,
    sortorder: gridStatus.sortOrder
}).trigger("reloadGrid", { page: gridStatus.page });
```
or
```JavaScript
var p = grid.jqGrid('getGridParam'); // get reference to internal parameters
p.postData = gridStatus.postData;
// it's better to replace the above line to setting some specific property of postData
// for example you could save filters property of postData in gridStatus.filters and to use
//     p.postData.filters = gridStatus.filters;

p.search = true; // should be depend on the content of gridStatus.filters or gridStatus.postData
p.sortname = gridStatus.sortName;
p.sortorder = gridStatus.sortOrder;
grid.trigger("reloadGrid", { page: gridStatus.page });
```

**Comment by bolzo5** [comment]
thank you for your answer it's really usefull,
I'm using jqGrid 4.14.0 and now I'm using your code to save the parameters, 
however after the trigger of reloadGrid, everything works but the sorting order while being correct, doesn't have it's icon displayed.
(by icon I mean for example the fa-sort-amount-desc from font awesome).
Thank you again for your time!

**Comment by OlegKi** [comment]
I hope that I understand your problem now. One can't just change **any** option of jqGrid and trigger `reloadGrid`. Some changes in the grid could be not set/reset in the case.

As the workaround for you I would suggest to use `sortGrid` method. For example,
```
grid.jqGrid("sortGrid", gridStatus.sortName);
```
See https://jsfiddle.net/OlegKi/tg8e6esb/ for the code example.

P.S. I repeat: please send always the demo, which reproduce the problem, which you reports. I just get the demo posted in the README of free jqGrid 4.14.0 and modified it to demonstrates my suggestions.

**Comment by bolzo5** [comment]
Thank you that's exactly what I needed.
