### ISSUE TITLE
Autoresizing in very specific situation

### ISSUE THREAD

**Issue by cosinus90** [free-jqgrid/jqGrid#338]
Hi,
When I set minimal font size in my browser's settings (Opera) to bigger value (17px) so it affects font size in cells - auto resizing works incorrectly, even after page reload.  Probably need another mechanism for detection of content width.

**Comment by OlegKi** [comment]
it's important to post every related version information: the version of free jqGrid, the version of the Opera (for example Opera 45.0.2552.881, Opera developer 46.0.2602.0 and so on), the version of jQuery, which CSS you use (jQuery UI or Bootstrap) and in which version, ...

Please, prepare the demo, which could be used to reproduce the problem and describe the test case it the problem can't be see directly after opening the demo.

**Comment by cosinus90** [comment]
Ok, it's here
https://codepen.io/zzmaster/pen/xdowRJ/

I took code from fillingTest.htm so you can see versions. One of cell is extra-large, it resized correctly. Now, in Opera 	45.0.2552.812 (PGO) we go to settings, enter 'font' in search field, click 'Customize fonts' in search results, scroll down, and set Minimal Font Size to 24 and voila 
- extra large cell doesn't fit. Reload page - and it still doesn't fit. 
(Actually, I use value of 17 becouse of eye tiredness and in one of my projects this value cause the problem)

![clipboard01](https://cloud.githubusercontent.com/assets/16591556/26559278/9828da7e-4463-11e7-97bd-1f3426056cb7.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/16591556/26559279/982a7ec4-4463-11e7-8b23-e6577d0cc93a.jpg)

**Comment by OlegKi** [comment]
It seems to me that you have absolute another problem. I suppose that the width of `node` column is just larger as 300px, which is default max value for columns during auto-resizing (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.0/js/grid.base.js#L2761)). Try to increase the value by adding the option
```JavaScript
autoResizing: { maxColWidth: 3000 } // increase max column width from 300 to 3000
```
See https://codepen.io/anon/pen/MmMazV

One can specify `autoResizing.maxColWidth` either for specific columns including the property (`autoResizing: { maxColWidth: 3000 }` for example) in `colModel` or to set common option for all columns like I did it in my demo.

**Comment by cosinus90** [comment]
Oh, really.. Thank you!

**Comment by OlegKi** [comment]
You are welcome! Please, close the issue if the problem is solved now. Is the problem fixed by using `autoResizing.maxColWidth` or it has another origin?

**Comment by cosinus90** [comment]
Yes, it was fixed by autoResizing: { maxColWidth: 3000 }
