### ISSUE TITLE
Differences with jqGrid "not free"

### ISSUE THREAD

**Issue by AurelienC** [free-jqgrid/jqGrid#339]
Hello,

Is it possible into free-jqrid to use some functionalities of jqGrid, sush as : 
* [colMenu](http://www.guriddo.net/demo/guriddojs/functionality/column_menu/index.html)
* [Exports (CSV, Excel, PDF)](http://www.guriddo.net/demo/guriddojs/export/grouping/index.html)

Thanks for your response !
Aurélien

**Comment by OlegKi** [comment]
Free jqGrid is Open Source project available under MIT/GPL-licenses. I made the fork of jqGrid 4.7.0 (the last version of jqGrid) and made a lot of changes: bug fixes, implementing new features and so on. Guriddo jqGrid JS is **commercial** product. You can see the prices and the licence agreement [here](http://guriddo.net/?page_id=103334). *Both products be developing independently*.

Thus one can't use the features (or the code fragments) of Guriddo jqGrid JS in the code of free jqGrid. In the same way, the users of Guriddo jqGrid JS can't use the features implemented in free jqGrid.

**Comment by AurelienC** [comment]
Hi Oleg,

Yes, I well understand the difference between Guriddo jqGrid project and free jqGrid.

I just want to know if it's possible with free jqGrid to use columns menu and exports ?

Thanks 😄

**Comment by OlegKi** [comment]
No Aurélien,

free jqGrid don't support `colmenu` or `coloptions` properties of `colModel`. Thus it don't supports colMenu. All supported properties could be found [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/ts/free-jqgrid.d.ts#L725-L787). In the same way `autoResizing`, `createColumnIndex`, `labelAlign`, `labelClasses`, `editable` with callback or "hidden" | "disabled" | "readonly" values and a lot of other properties of `colModel` available in free jqGrid are not available in Guriddo jqGrid JS.

The feature, which you asked, are new features of Guriddo jqGrid JS. The features not exist in free jqGrid.

About exporting of data in Excel, CSV and PDF. In my opinion it should be the features of *server side code*. The data displayed in the grid exist *on the server side* in the most scenarios. I personally use ASP.NET on the backend and exports the data with respect of Open XML SDK (see [here](https://github.com/OfficeDev/Open-XML-SDK) and [here](https://msdn.microsoft.com/en-us/library/office/bb448854.aspx)). I use the code, which is close to the code, which I posted in [the answer](https://stackoverflow.com/a/9349688/315935) and in [this one](https://stackoverflow.com/a/13957161/315935). Export to PDF used in Guriddo jqGrid JS are based on the usage of [pdfmake](https://github.com/bpampuch/pdfmake). You can use it directly. Of cause you will need to write some parts of additional JavaScript code.

**Comment by AurelienC** [comment]
Many thanks for these details !
