### ISSUE TITLE
viewsortcols horizontal has no effect

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#34]
According to http://www.trirand.com/jqgridwiki/doku.php?id=wiki:options  and http://stackoverflow.com/questions/8885937/how-to-make-sort-icons-visible-in-all-column-headers-in-jqgrid-regardless-on-sor

viewsortcols : [true,'horizontal',true]

should create horizontal sort icons.

Actually sort icons are still vertical, horizontal setting as no effect.

**Comment by OlegKi** [comment]
The option `viewsortcols : [true,'horizontal',true]` do work with default `iconSet` (`iconSet: "jQueryUI"`). The option don't supported with other `iconSet`.
