### ISSUE TITLE
Misalignment of column headers with Group Headers

### ISSUE THREAD

**Issue by hdbonnett** [free-jqgrid/jqGrid#345]
I'm encountering an issue when using setGroupHeader with ColSpanStyle=true and 3 columns spanned. My free-jqgrid version is 4.13.3 (from the CDN). 
The involved columns are defined as such:
`		   	   {name:'qty_ordered',index:'qty_ordered',align: 'right',width:70,hidden:true, search:false},
		   	   {name:'qty_remaining',index:'qty_remaining',align: 'right',width:70, hidden:true,search:false},
		   	   {name:'qty_percent',index:'qty_percent',formatter:'currency', align: 'right',
		   			formatoptions:{decimalSeparator:".", decimalPlaces: 0, suffix: "%"},width:30, hidden:true,search:false},`
The columns are hidden initially and revealed when the user clicks a tab to filter.

Width of the table is fixed at 680px, ShrinktoFit =true
All is fine when I don't have the grouped header showing: (the blank line below the header is for a grouping column to the left of the image)
![image](https://user-images.githubusercontent.com/19419731/27363772-c8298750-5679-11e7-82c7-6557b7be435d.png)
but when I show my new columns and the grouped header above them, the headers no longer align to the table columns:
![image](https://user-images.githubusercontent.com/19419731/27363820-034a7a24-567a-11e7-83a7-fe820e61ca40.png)
Setting useColSpanStyle=false doesn't fix the issue
Most of the columns are 6px wider in the table than the header, whether under the grouped header or not. Resizing the columns doesn't fix the issue but destroying the group header does. It appears that the headers are being reduced but the cells aren't.

Any ideas how to resolve this?

**Comment by OlegKi** [comment]
Please provide **the demo**, which reproduces the problem. Only debugging can help find the reason on the problem. Please never use old versions of free jqGrid if the new one is published. The current released version of free jqGrid is 4.14.1. You can use it  in the demo or the latest code from GitHub (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)).

Small code fragment, which your posted looks a little strange. **All** the columns which get grouped header are hidden. You should verify that you make the columns visible **before** calling of `setGroupHeaders` method.

**Comment by hdbonnett** [comment]
Hi Oleg, I'll try to put together a demo that illustrates the issue but since the site is restricted and the data comes from an intranet, that may be difficult. 

I'm testing now with 4.14.1, I thought I was on the latest but realised I was behind after I posted the issue, so my apologies.
Regarding your last point, the columns involved are hidden on the initial grid but are shown via calls to showCol before I set up the GroupHeader. 
I'll update this issue with 4.14.1 feedback once I have it.

**Comment by OlegKi** [comment]
Hi @hdbonnett, you can create demo in [jsfiddle](https://jsfiddle.net/) for example. You can use https://jsfiddle.net/OlegKi/m7rqjyqo/ as the starting point and modify it to your application. If you need to load the data from the server, then you can use [Echo](http://doc.jsfiddle.net/use/echo.html) service of jsfiddle. See https://jsfiddle.net/OlegKi/92mhochf/ as an example.

**Comment by OlegKi** [comment]
Please, provide the demo, which demonstrates the problem, or close the issue.

**Comment by hdbonnett** [comment]
Hi Oleg, I'm working with 4.14.1 now and still seeing some weird behaviour but I don't have the time at present to set up the demo :( so I'm going to close the issue. I'll create a new one when I can create a demo and have more useful info.
