### ISSUE TITLE
jgrid numeric and multiselection filtering 

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#347]
Hi Oleg,

as you can see in my example I'm using the dropdown and the text filtering
https://jsfiddle.net/01th999n/13/

but I have a question is possible to have multiselection for the drop down filtering(in this exemple column address) and for some numeric column have a numeric filter(for example for column number can I filter like >1 so only column with number 2 and 3 will appear )?

Thanks

**Comment by OlegKi** [comment]
Your current code don't use some new features of free jqGrid. I'd change your demo to https://jsfiddle.net/OlegKi/01th999n/14/, which used `stype: "select", searchoptions: { generateValue: true, noFilterText: "Any"}` in `address` columns.

About your main question. Free jqGrid don't have direct support of multiselection, but one can use `multiple="multiple` attribute of `<select>` to have multiselect possibility. You can add `stype: "select", searchoptions: { attr: { multiple: "multiple", size: 4 } }` option to the column to enable the feature.

There are some plugins, which allows to use `multiple="multiple` attribute of `<select>` in more comfortable form. You can find some examples in [the issue #290](https://github.com/free-jqgrid/jqGrid/issues/290), for example. You can try to use [select2](https://select2.github.io/examples.html) alternatively. The demo https://jsfiddle.net/OlegKi/yvbt6w54/1/, which I included in [the README](https://github.com/free-jqgrid/jqGrid/blob/master/README4.14.0.md#new-main-features-implemented-in-the-version-4140-compared-with-4136) of version 4.14.0. It don't use multiple option, but it demonstrates some other features, which could be helpful for you, and it could be starting point to your final solution.

**Comment by Ant02** [comment]
Hi Oleg,

thanks for your reply about the multiselection filtering. About the numeric filtering do you have any idea how I can manage that (for example for column number can I filter typing ">1" so only rows with number "2" and "3" will appear?)

Thanks

**Comment by OlegKi** [comment]
Sorry, but if you look at the demo, which I posted you in the previous comment, you will see that the most fields of the filter toolbar contains additional small button, which allows to choose filtering operation.

![menu](https://user-images.githubusercontent.com/249117/27534398-268f16ca-5a67-11e7-9eff-d03c6130a920.png)

The method `filterToolbar` supports `searchOperators` option, which default value is false. One can specify `searchOperators: true` in the option of `filterToolbar`, for example, replace
```JavaScript
$grid.jqGrid("filterToolbar",
    { stringResult: true, searchOnEnter: true, defaultSearch: "cn" });
```
to
```JavaScript
$grid.jqGrid("filterToolbar",
    { stringResult: true, searchOnEnter: true, defaultSearch: "cn", searchOperators: true });
```
or to use `searching` option of jqGrid to specify `searchOperators: true` as default option of `filterToolbar` (see the demo https://jsfiddle.net/OlegKi/yvbt6w54/1/).

After adding `searchOperators: true` option the user will be able to choose ">" operation and enter 1 in the input field. It forces filtering of data like you need.

**Comment by OlegKi** [comment]
One more remark. You can use `searchoptions.sopt` to specify the list of possible comparing operation allowed in the column. The first operation will be default filtering operation. For example, https://jsfiddle.net/OlegKi/01th999n/15/ displays
![menu1](https://user-images.githubusercontent.com/249117/27534861-a89d2408-5a68-11e7-977f-ee93dfbc7a29.png)

**Comment by Ant02** [comment]
Great! Thank you so much for your help!
