### ISSUE TITLE
Row highlighting position in cell editing can become "stuck" with keyboard navigation

### ISSUE THREAD

**Issue by arrinmurr** [free-jqgrid/jqGrid#348]
This is a very minor issue.

When using up/down arrow keys to move in the grid while cell editing mode is active, the position of the row highlighting can become "stuck" somewhere in the middle of the grid. The grid needs to have a scrollbar for this to happen. This affects at least the latest versions of Firefox and Chrome.

Example:
* 4.14.1: https://jsfiddle.net/o8v2ybcp/

Steps to reproduce:
1. Click on "abc1".
1. Press the down arrow key on the keyboard until the scrollbar starts moving.
1. Press the up arrow key a couple of times.
1. Continue pressing the down arrow key. Notice how the scrollbar starts moving immediately, instead of the row highlighting position moving to the currently visible bottom row first. The highlighting position starts moving again only after the scrollbar hits the bottom.

**Comment by OlegKi** [comment]
Thank you for the bug report! It's very helpful to have the demo with clear described test case. It simplifies analyzing and fixing the problem. I posted [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/a1157de8724b0a3d58646276c3a1d80eaf3c5552) to GitHub. The modified demo https://jsfiddle.net/OlegKi/o8v2ybcp/1/ uses the latest code from GitHub. One can verify that the reported problem is fixed now. Please confirm that and close the issue if everything is OK now.

**Comment by arrinmurr** [comment]
Looks good to me, thank you!
