### ISSUE TITLE
Do not allow anything on `Actions` column and issue with `undefined` values

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#349]
I'll try to tackle two issues on this issue. First related to `Actions` column, second related to `Undefined` value in some columns.

**1st issue:**
I would like to:

- Don't allow the column `Actions` to:
    - <strike>be sortable (do not allow to sort ASC or DESC on this column, does not have any sense)</strike>
    - <strike>be searchable (there is nothing to search for there)</strike>
    - be orderable (not drag & drop on this column at all)
    - <strike>be removable(not to be added|remove this column on `Columns` window - I can't make this example to work properly)</strike>
    - be ix it to the first position (this should be always the first column not matter what)

**2nd issue:**
<strike>For some reason some values are being displayed as 'undefined' and I don't know what I am missing here. Seems to be properly mapped so ....</strike>

[Here is](https://jsfiddle.net/reynierpm/1vnLnm6L/3/) a Fiddle to play with.

@OlegKi if you want me to split this in two different issues just say it.

**Comment by OlegKi** [comment]
I answered you [here](https://github.com/free-jqgrid/jqGrid/issues/346#issuecomment-310179854)  on your question already. The demo, which you post contains the following properties of the column `actions`:
```JavaScript
{
      "name": "actions",
      "width": 60,
      "fixed": true,
      "sortable": false,
      "resize": true,
      "formatter": "GridLicenseActions",
      "formatoptions": "",
      "index": "actions",
      "align": "left",
      "hidden": false,
      "edittype": "",
      "classes": false,
      "editable": false,
      "label": "Actions",
      "key": "",
      "autoResizable": true,
      "frozen": true,
      "resizable": true, // !!! false
      "search": false
}
```
You should fix it to the following:
```JavaScript
{
      "name": "actions",
      "width": 60,
      "fixed": true,
      "sortable": false,
      "resize": true,
      "formatter": "GridLicenseActions",
      "formatoptions": "",
      "index": "actions",
      "align": "left",
      "hidden": false,
      "edittype": "",
      "classes": false,
      "editable": false,
      "label": "Actions",
      "key": "",
      "autoResizable": false, // !!! 
      "frozen": true,
      "resizable": false, // !!!
      "search": false,
      "hidedlg": true, // !!!
      "viewable": false // !!!
}
```
About the 2nd issue. You need just use correct `name` property of columns in `colModel`, which corresponds the property name of the input data. You need fix
```JavaScript
{"name": "product.Product-PartNumber",...
{"name": "product.Brand", 
```
to probably the following
```JavaScript
{"name": "product.PartNumber",...
{"name": "product.Source", 
```
See https://jsfiddle.net/OlegKi/1vnLnm6L/4/

**Comment by reypm** [comment]
@OlegKi I've strike out those ones working for me from your example but there is two remaining:

- Don't allow the column `Actions` to:
    - be orderable (not drag & drop on this column at all)
    - be ix it to the first position (this should be always the first column not matter what)

Those can't be achieved? I am trying on your same example without any changes.

**Comment by OlegKi** [comment]
jqGrid use sortable of jQuery UI to reorder the column. It allows to disable some items from sorting by using `items` option (see [here](http://jqueryui.com/sortable/#items)). In case of jqGrid the usage of the option will be a little tricky. One need replace the jqGrid option `sortable` to the following:
```JavaScript
sortable: {
    options: {
        items: ">th:not(:has(#jqgh_grid1_cb,#jqgh_grid1_rn,#jqgh_grid1_actions),:hidden)"
    }
}
```
where `grid1` is the id of the grid and `actions` is the name of Action column. Other two names `rn` and `cb` are the names of rownumber column and multiselect column.
See https://jsfiddle.net/OlegKi/1vnLnm6L/6/

I described the solution, for example, in [the old answer](https://stackoverflow.com/a/12609087/315935), but it's difficult to find the answer.

**Comment by reypm** [comment]
Pefect, many thanks, that did the trick.

**Comment by OlegKi** [comment]
You are welcome!

**Comment by reypm** [comment]
Is there any docs for default formatter usage? I am having an issue with `select` formatter, do you want me to open an issue with this?

**Comment by OlegKi** [comment]
You can ask the question in new issue or on the stackoverflow. I'm not sure what you mean under "default formatter". The options of `select` formatter are mostly the same as describe in [the old jqGrid documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:predefined_formatter#formatter_type_select). The real implementation is a little more tricky because I tried to have the most possible support to old versions of jqGrid, which allows a little more as described in documentation.
