### ISSUE TITLE
checkbox formatter search options are not localizable using language file

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#35]
Search options for FontAwesome and CheckBox formatters are defined in source code as as

				stype: "select", searchoptions: { sopt: ["eq", "ne"], value: ":Any;true:Yes;false:No" }

Words Any, Yes, No appear in english always. Localizaton is not present in language file.

**Comment by OlegKi** [comment]
The formatters don't have any `searchoptions` settings. You mean probably `template: "booleanCheckboxFa"` and `template: "booleanCheckbox"`.

One can use `template: "booleanCheckboxFa", searchoptions: {value: ":Beliebig;true:Ja;false:Nein" }` to overwrite the words `Any`, `Yes`, `No` displayed in filter toolbar and in searching dialog by default to localized texts `Beliebig`, `Ja`, `Nein`.

I agree with you in general, that one could introduce new parameter for `Any` string and use it by default in `searchoptions` in case of `stype: "select"`, but if could be still not perfect solution which will be good for every situation.

I will still thought later about the new localize parameters.
