### ISSUE TITLE
How do I access the checked row Ids from a function triggered by a grid button?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#351]
Hi @OlegKi (does bother to you at all be naming you when opening an issue?? shouldn't do that):

I am trying to pick the list of checked checkboxes on a jQgrid from a button bar and this is how I am doing:

```javascript
  $('#grid1').jqGrid('navButtonAdd', '#grid1-gridpager', {
    caption: 'Resend',
    title: 'Resend latest failed notifications',
    onClickButton: function() {
      var selRowId = $('#grid1').jqGrid('getGridParam', 'selrow');
      console.log(selRowId);
    }
  });
```

For some reason on my side is picking up the wrong values and this mean if I pick the first one and the last one I only got one value in the `console.log()`. I am not sure if I am doing something wrong, any help?

[Here is](https://jsfiddle.net/reynierpm/1vnLnm6L/11/) a Fiddle I've made to play with but unfortunately I couldn't make the button appear on the bar.

**Comment by OlegKi** [comment]
The parameter `selarrrow` should be used instead of `selrow` in case of usage multiple selection (`multiselect: true`). See https://jsfiddle.net/OlegKi/1vnLnm6L/15/.

**Comment by reypm** [comment]
Ups miss that one, thx
