### ISSUE TITLE
Error when formatting dates using parseDate method

### ISSUE THREAD

**Issue by XjSv** [free-jqgrid/jqGrid#357]
I am attempting the following: `$.jgrid.parseDate('ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y');`

But I seem to be getting this error: `Uncaught TypeError: Cannot read property '6' of undefined at Object.parseDate (jquery.jqgrid.min.js:1300)`

I noticed that `dayNames` and `monthNames` are not being set even though this should work in theory:
`root2 = (jgrid.formatter || {}).date || {},` at line# 1135. 

When debugging the values are not there and I can't seem to figure out why. Only `masks` exist but according to the code `dayNames`, `monthNames`, `AmPm`, `S`, `srcformat` & `newformat` should be set.

**Using:** jqGrid 4.15.0-pre

**Comment by OlegKi** [comment]
I suppose that you have some problem to migrate your code from old jqGrid to free jqGrid. The method `$.jgrid.parseDate` is designed to work in context of some jqGrid, which contains locale specific information about date formatting. Free jqGrid require `this` be initialized to the DOM of the grid (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/ts/free-jqgrid.d.ts#L632)). If you have `var $grid = $("#grid");` then the code could be
```JavaScript
$.jgrid.parseDate.call($grid[0], 'ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y');
```
If you need to use `$.jgrid.parseDate` inside of some grid callback then `this` is already initialized to the DOM of the grid in the callbacks and you can use typically just
```JavaScript
$.jgrid.parseDate.call(this, 'ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y');
```

**Comment by OlegKi** [comment]
I thought a little more about your problem and made [the changes](https://github.com/free-jqgrid/jqGrid/commit/63c1833f718bb45a736417a312b57bfedaa6bb6f) in the code of free jqGrid to improve upwards compatibility and to make the old code `$.jgrid.parseDate('ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y')` working too. In case if one included multiple locale files, the call of `$.jgrid.parseDate` will uses the last included locale. If you use en-US locale then you don't need to include `grid.locale-en.js`. `$.jgrid.parseDate` will uses en-US locale included in the main code of free jqGrid (`jquery.jqgrid.min.js` or `jquery.jqgrid.src.js`).

**Comment by XjSv** [comment]
I did not migrate code from the old jqGrid. My mistake was looking at the old jqGrid docs instead of the free jqGrid docs. I figured hopefully the same line of code works in the free jqGrid also. But I guess I was wrong. 

As you mentioned I could have called the function like this:
`$.jgrid.parseDate.call($grid[0], 'ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y');`
Which would have worked. 

It looks like I don't have to now since you already made the compatibility fix. Thank you by the way.

**Comment by OlegKi** [comment]
You are welcome! I'm not sure whether the problem is fixed or you still have some problems with the usage of `$.jgrid.parseDate`. If the problem is solved, please close the issue. If you have some problems, then it would be helpful if you prepare the demo (in jsFiddle for example), which reproduces the problems.

**Comment by XjSv** [comment]
Just confirmed with the latest code that this now works:

`$.jgrid.parseDate('ISO8601Long', '2017-04-15T00:00:00Z', 'd/M/Y');`
