### ISSUE TITLE
"moveVerical" function

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#358]
Hi, I know this is just a typo, not really important, but you have a function named "moveVerical", when it's supossed to be "moveVertical" (missing the T)

regards!

**Comment by OlegKi** [comment]
Thank you very much for reporting the issue. I know that I make frequently typing errors, but I just don't see such errors myself. Thus I'm glad if other find the errors and report these.

**Comment by aberel** [comment]
You are welcome. I know it's just a typo error :+1:
