### ISSUE TITLE
filterToolbar issue

### ISSUE THREAD

**Issue by himiklab** [free-jqgrid/jqGrid#36]
Здравствуйте!
Проблема такая, если сделать фильтрацию с помощью `filterToolbar`, а затем вызвать меню расширенного поиска с помощью кнопки на `navGrid`, то поля по которым производилась фильтрация окажутся в форме поиска. Если я их оттуда удаляю и допустим добавляю новые критерии, то поиск производится по этим новым критериям без учёта того, что стоит в `filterToolbar`, такое поведение вполне логично, но есть проблема, состояние `filterToolbar` после поиска не изменяется, в нём остаются старые значения, которые однако уже никак не влияют на результаты. Хотелось бы, чтоб удалённые в форме поиска критерии исчезали и из `filterToolbar`.

**Comment by OlegKi** [comment]
Привет! Основная проблема состоит в том, что `filterToolbar` позволяет создать менее сложный филтр, чем Advanced Searching, особенно если использовались опции `multipleSearch: true` и `multipleGroup: true`. Поэтому заполнение filter toolbar в общем случае не всегда возможно. В то же время я написал код, опубликованный в [ответе](http://stackoverflow.com/a/6884755/315935). Возможно, он решит основные ваши проблемы. Я хотел его сначала включит в основной код free jqGrid, но потом заметил, что код не достаточно общий. Во-первых, он не учитывает опцию `searchOperators: true` введенную позже, а также теучитывает более экзотическую опцию `groupOp`, которую можно сутановить в `groupOp: "OR"`. Одним словом, у меня руки не дошли до того чтобы переработать старый код и включить его в основной код free jqGrid. Я, все же надеюсь слелать это вскоре, когда разбирусь с текущими проктами, на которых я зарабатываю деньги. Одним словом я рекомендую пользоваться `refreshSerchingToolbar` из ответа http://stackoverflow.com/a/6884755/315935 и взглянуть на http://www.ok-soft-gmbh.com/jqGrid/ColumnChooserAndLocalStorage1.htm из другого старого ответа http://stackoverflow.com/a/8436273/315935 где дополнительно фильтр сохраняется при перезагрузке страницы.

**Comment by himiklab** [comment]
Спасибо! Похоже на то, что нужно. Но может можно сделать опцию чтоб `filterToolbar` сбрасывался если используется `Advanced Searching`?

**Comment by OlegKi** [comment]
Я не очень понимаю, что означает "`filterToolbar` сбрасывался". Можно использовать, например, `destroyFilterToolbar` чтобы удалить searching toolbar и тут же заново создать его с помощью `filterToolbar`.  Можно это делать в `onSearch` и `onReset` callbacks. Но мне лично такое "решение проблемы" не нравится.

**Comment by himiklab** [comment]
Спасибо, попробую эти способы!
