### ISSUE TITLE
jqgrid modal dialogs not dragging?

### ISSUE THREAD

**Issue by aberel** [free-jqgrid/jqGrid#361]
(I am in free jqGrid 4.13.7-pre)
In all modal/dialogs created by jqgrid, the title-bar (ui-jqdialog-titlebar) has css "cursor: move", so it seems like I can drag the dialog with the mouse, BUT the dragging action does not work, and the dialog stay static in place, ignoring the mouse action at all.
Is this behavior correct? Or is an issue?
Examples: "Delete confirm", "Please, select row", and many others...

regards.

**Comment by OlegKi** [comment]
Please include always the demo, which **reproduces** the problem, which you report. Which CSS framework you use and in which version? Which options you use for jqGrid? For example, the demo https://jsfiddle.net/OlegKi/su7ebs65/, included in the readme to the last published version, don't have the problem. Moreover, please use some *specific* version. The last released version is 4.14.1. The versions, with the suffix **-pre** is some *preliminary* version between releases. One have to specify *the date* of the file. Moreover, I can't support any old -pre versions. You should use either the last released version (4.14.1) or the latest code from GitHub (see [here](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)). It's today the version **4.15.0-pre** with the date stamp **2017-08-07**.

**Comment by aberel** [comment]
ok got it.
Anyway, I see the demo, so the error is not in jqgrid, thanks.
