### ISSUE TITLE
.loading indicator on delete not triggered

### ISSUE THREAD

**Issue by Gazoo** [free-jqgrid/jqGrid#365]
When I save or edit a row the grid loading indicator is displayed with the message "saving". Is it possible to do the same when deleting a row? I have some operations that take some time when deleting and you can't tell that the grid is working until it completes.

**Comment by OlegKi** [comment]
You can use `progressBar` method to show/hide the loading indicator. You can display "Deleting..." message by the code like
```JavaScript
$(this).jqGrid("progressBar", {method: "show", loadtype: "enable", htmlcontent: "Deleting..."});
```
which you can execute inside of `onclickSubmit`, `beforeSubmit` or `serializeDelData` callback of deleting. You can use `formDeleting` option of jqGrid to define default options used during deleting. You should be carefully and return correct value for every callback (for example you can return `{}` from `onclickSubmit` or return `[true, ""]` from `beforeSubmit`).

Then you should hide the loading indicator by calling
```JavaScript
$self.jqGrid("progressBar", { method: "hide", loadtype: "enable" });
```
inside of both `afterSubmit` and `errorTextFormat`. Don't forget to return correct values from the callbacks too.

**Comment by Gazoo** [comment]
Your work around works when using the grid navigator delete but it seems that onclickSubmit, beforeSubmit or serializeDelData don't get called when using the delete button on the actions formatter. Any way to get it working for both in a clean way?

**Comment by OlegKi** [comment]
Actions formatter uses the same form editing method `delGridRow` to delete rows (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/jquery.fmatter.js#L747)). If you add `formDeleting` option to jqGrid (see [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods)), which uses for example `onclickSubmit`, `afterSubmit` and `errorTextFormat` then the callbacks will be called in case of *any direct or indirect usage of `delGridRow`*. In other words, it will be used by actions formatter, `navGrid` or if you for example call `delGridRow` directly.

**Comment by Gazoo** [comment]
Many thanks for the insight. All is working now :)

**Comment by OlegKi** [comment]
I thought about the problem once more and added more options to `delGridRow` holding defaults the same as in previous versions (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/0841a7bd8c394e23c44c36e58b61ea10888bcc57)). Now one can use just new deleting options `delui: "enable", deltext: "Deleting..."` to display the loading indicator, which you need:
```JavaScript
formDeleting: {
    delui: "enable",
    deltext: "Deleting..."
}
```
Default value of `delui` option is `"disable"`, which means that no "Deleting..." div will be shown.
By the way, one can use `delui: "block"` and `saveui: "block"` in the same way like one can use `loadui: "block"` option of jqGrid:
```JavaScript
loadui: "block",
formEditing: {
    saveui: "block"
},
formDeleting: {
    delui: "block",
    deltext: "Deleting..."
}
```

**Comment by Gazoo** [comment]
Very nice and clean :)
