### ISSUE TITLE
Red line because of AJAX call interruption, can be hidden without need to use CSS?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#367]
In the application I am working we have a lot of grids. If the user switch  from one to another quickly and the AJAX call gets interrupted by some reason the UI display a red line saying "error". I can't find a way to hide this other than CSS or I don't know if I am missing something else here regarding the way the grid should work to avoid this issue.

The thing people is complaining and saying they don't like this red line and I don't know how to explain the issue to them or how to fix it.

Take a look to the error:
![errorbar](https://user-images.githubusercontent.com/627886/30341823-7dc12686-97c5-11e7-8e47-3e3a256c8ee7.png)

Any ideas in how to fix this or how to tackle the issue?

**Comment by OlegKi** [comment]
Could you post more details about the problem and about your code. How exactly the AJAX call gets interrupted? Do you use your custom `loadError` callback or you hold the default implementation provided by free jqGrid (see [the code](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L2658-L2715))? How the Ajax call be aborted? Do you use `abortAjaxRequest` method? Which version of jqGrid you use?

In general, free jqGrid uses `displayErrorMessage` method (`$grid.jqGrid("displayErrorMessage", message);`, which you can use too (see [the code](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L6104-L6118)). It hides error div (see `div.ui-jqgrid-errorbar` on [the picture](https://free-jqgrid.github.io/getting-started/index.html#grid-internal-div)). The error div is available via `$grid[0].grid.eDiv`. It will be hidden before every new request (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L4648)) and after every successful response (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L4662)).

Additionally free jqGrid supports `errorDisplayTimeout` parameter of jqGrid, which can be set to specify the time im milliseconds after which the error div, displayed by `displayErrorMessage` will be automatically hidden (see [the lines](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L6112-L6117) of the code of `displayErrorMessage`).

**Comment by reypm** [comment]
@OlegKi  I will close this for now since I don't have enough information for provide it to you so you can debug. If I run into the same issue again I will reopen it with the requested info.

**Comment by OlegKi** [comment]
@reypm My problem is not only the ability to reproduce the problem. I still don't understand what is your question.

The default behavior of old versions of jqGrid: don't display any information about error in Ajax requests during filling of the grid. The default behavior in free jqGrid: displaying of error div with error information, which I try to get from the response of the server. The error div will be displayed in case of any error in Ajax request with exception of the `abort` error: by explicit call of [jqXhr.abort()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort). What jqGrid do is just setting *default* callback of `loadError` callback (see [the old answer](https://stackoverflow.com/a/6969114/315935)), which decodes the server response in common way and displays the error information.

The screen, which you posted, means that there was an error during Ajax request. The next successful request will hide the div. The only problem is: why the content of the div was empty (no error description). It means either that the server response really contained no error information or that the error information can't be correctly decoded by the standard `loadEddor` implementation (see the code of `stdLoadError` [here](https://github.com/free-jqgrid/jqGrid/blob/v4.14.1/js/grid.base.js#L2658-L2715)) and you should write your own `loadEddor` callback, which decodes the specific formatted responses sent by your web server.

If you need just don't display any error information in case of errors in Ajax request (the behavior of old versions of jqGrid) then you can just add empty `loadEddor` callback:
```JavaScript
loadError: function () {}
```
Is it what you want?
