### ISSUE TITLE
Is there an easy built-in way to export and/or print results?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#370]
Is there any easy way to export and/or print the _current_ grid results? By _current_ I mean the filtered result set and not the whole grid data? Forgive me if someone already asked about this previously but I can't find anything helpful around this topic

**Comment by OlegKi** [comment]
Which `datatype` you have in the grid? One can get **local filtered data** from `lastSelectedData` option, which is close to `data`, but contains sorted and filtered data. See https://jsfiddle.net/OlegKi/akv51mdq/ or https://jsfiddle.net/OlegKi/Ljejoh21/ demos or [the old demo](http://www.ok-soft-gmbh.com/jqGrid/OK/GetFilteredData.htm) from the [README](https://github.com/free-jqgrid/jqGrid/blob/master/README48.md#some-demos-which-demonstrates-new-features) of jqGrid version 4.8.

**Comment by reypm** [comment]
@OlegKi sorry for the late response. The `datatype` is `json` I am seeing from one of the example it's possible to use the `lastSelectedData` you mention even using it. I'll give it a try and if I've further questions I will reopen this. Closing for now .... thanks
