### ISSUE TITLE
Treegrid with drag and drop 

### ISSUE THREAD

**Issue by cprashant1** [free-jqgrid/jqGrid#373]
Do we have sample of Treegrid with drag and drop in same grid ? we want grid should be updated as soon as rows droped and all child rows along with parent should be selected

**Comment by OlegKi** [comment]
Sorry, for the late answer. TreeGrid don't have built-in feature, where tree node can be moved via Drag & Drop, You can still implement the feature yourself. You can use `sortableRows` method to activate Drag & Drop of rows. The current code don't support TreeGrid (see [the line](https://github.com/free-jqgrid/jqGrid/blob/v4.15.0/js/grid.jqueryui.js#L676)). As the workaround you can temporary change change `treeGrid` option to `false`, call `sortableRows` and change `treeGrid` back to true after calling of `sortableRows`. `sortableRows` uses jQuery UI Sortable plugin internally and you can use options of `sortableRows` to forward and custom options to jQuery UI sortable. The most important option is `update`, which can be used for any custom action, which need be done after the end of Drop of the node. See [the answer](https://stackoverflow.com/a/3357770/315935) and [this one](https://stackoverflow.com/a/9045125/315935) for the corresponding code examples and demos. It's important to understand, that all child nodes are direct sibling elements of the parent node. The collapsed elements are just hidden. The method `getNodeChildren` can be used to get ids of all child elements. Other methods, which could be helpful: `addChildNode` and `setTreeRow`.

**Comment by OlegKi** [comment]
I didn't get any response from use since a long time. I'm closing the issue now. You can post additional information about your problem and *reopen* the issue.
