### ISSUE TITLE
Dependencies of free-jqgrid

### ISSUE THREAD

**Issue by pribeirojtm** [free-jqgrid/jqGrid#380]
Hi,

Can anyone tell me exactly what are the requirements of this project? 
Obviously jquery. But, Is jQueryUI necessary? i'm trying to avoid jqueryUI and trying to use these grids with bootstrap only. Is it possible? 

UPDATE: Can you please provide the dependecies versions compatibility also? 

Thanks

**Comment by OlegKi** [comment]
It's depend on how one defines the "dependencies" and with which options one uses free jqGrid.

Free jqGrid has `guiStyle` option, which specifies CSS framework, which jqGrid uses. Default value of  `guiStyle` is `"jQueryUI"`. It means that jqGrid requires jQuery UI CSS framework. Thus one needs `jquery-ui.min.css`, but `jquery-ui.min.js` isn't required.

If one uses other value for `guiStyle` (`"bootstrap"`, `"bootstrapPrimary"`, `"bootstrap4"` or other), that one can uses free jqGrid absolutely without jQuery UI. See [here](https://free-jqgrid.github.io/getting-started/index.html#bootstrap) and example of usage free jqGrid with Bootstrap only.

Bootstrap 3 CSS is supported by free jqGrid starting with 4.13.0. Boostrap 4 (v4.0.0-alpha.6 and v4.0.0-beta) is supported starting with free jqGrid 4.14.0.

One can use free jqGrid with jQuery in any version starting with 1.7.2 and jQuery UI CSS staring with 1.8.11. It's recommended to use the latest jQuery 3.x.y or the latest 1.x.y. Currently I use jQuery 3.2.1 or 1.12.4 in tests of free jqGrid.

It's strictly recommended to use only the latest version of free jqGrid. Free jqGrid can be used completely free of charge under MIT/GPL licenses and I can't provide any free support for more old versions as the last one. The last released version is 4.15.0, but I plan to publish the current GitHub code as version 4.15.1 at the next weekend.

**Comment by pribeirojtm** [comment]
Thanks OlegKi! This topic could help other developers with  same question.

Another question more or less related, is that i've notice that for using columnchooser requires the usage of jqueryui (css only? or js also?). Can I use the guiStyle: "bootstrap", even in this case? 
They do not conflict with each other?

Just one more question, if you can help me:
I'm also trying to use fontawesome  icons inside the grids. 
Can I just use iconSet: "fontAwesome"? It is not necessary to extends the grid to initFontAwesome jqGrid("initFontAwesome"), or that's for other purposes? 

Notice: I'm using latest versions of freejgrid, jquery, bootstrap and fontawesome. 

Thanks a lot.

**Comment by OlegKi** [comment]
You are welcome!

One can include both Bootstrap and jQuery UI, for example to use `columnChooser`. I recommend only to choose Theam of jQuery UI, which corresponds color schema used in Bootstrap. I mean just that the pictures like below looks not so nice inspite of correct working of the `columnChooser`:
![columnch](https://user-images.githubusercontent.com/249117/30926345-18e76cb0-a3b5-11e7-8bf9-c4a51ac2f84f.png)
Only small problem, which I could see were in jQuery UI Datepicker used together with Bootsrtap CSS. One can fix the problem by adding CSS rule like
```css
.ui-datepicker select.ui-datepicker-year,
.ui-datepicker select.ui-datepicker-month {
    color: #222222; /*black*/
}
```
In any way, it's not a problem of jqGrid, but common problem of compatibility of jQuery UI with Bootstrap. If you want to use `columnChooser`, then you of cause need to include `ui.multiselect.css` and `ui.multiselect.js` from `plugins` folder of free jqGrid.

To use Font Awesome in jqGrid you need just include Font Awesome CSS and add jqGrid option. See an example [here](https://free-jqgrid.github.io/getting-started/index.html#type_of_data_code). I remind you that you can find working free jqGrid examples in READMEs of old versions. For example, I wrote you that free jqGrid 4.13.0 introduced Bootstrap support. [Here](https://github.com/free-jqgrid/jqGrid/blob/master/README4.13.0.md#main-new-features-and-improvements-implemented-in-the-version-4130) you will find links to some demos, which demonstrate the features.

**Comment by pribeirojtm** [comment]
Once again, thanks!

**Comment by OlegKi** [comment]
You are welcome! Please, don't forget to close issues after everything is cleared. I can close any issue too, but I prefer that the requester decide when to close.

**Comment by pribeirojtm** [comment]
Sorry Oleg. I'll close it later. And thanks for your help.

I'm still having problems setting column chooser correctly. Even using latest versions for everything, the layout was bugging. One thing I discovered is that is needed that bootstrap.min.js must be loaded before jquery-ui.min.js. That fixed me some layout problems in columnchooser, but, I'm still having a button with the text "undefined". I dont know why this is happening, and I also dont know how to costumize the column Chooser button(s).

Can you help me in this case? thanks
![column_chooser](https://user-images.githubusercontent.com/18724236/31013386-c0ea6512-a50d-11e7-8b41-f5655e9fccd7.png)

**Comment by pribeirojtm** [comment]
Oleg, I have figured out!!! Damn!
I didn't know that the order of importing js was important!
I was imporing ui.multiselect.js after jquery.jqgrid.min.js, but it must be imported BEFORE! 
Duh!

Sorry, now it works... thanks anyway.

**Comment by pribeirojtm** [comment]
Other thing I've notice is that I dont need to include your jQuery.jqGrid.columnChooser.js. 
I only need to include the ui.multiselect.js and ui.multiselect.css to make column chooser work... (I was using that plugin also :( )

What also was the key fact here was the order of includes of css and js!

I'll put here the order that I've used:
css:

1. jquery-ui/themes/base/jquery-ui.min.css
2. bootstrap/dist/css/bootstrap.min.css
3. free-jqgrid/dist/css/ui.jqgrid.min.css
4. free-jqgrid/dist/plugins/css/ui.multiselect.min.css

js:

1. jquery/dist/jquery.min.js
2. bootstrap/dist/js/bootstrap.min.js
3. query-ui/jquery-ui.min.js
4. free-jqgrid/dist/plugins/min/ui.multiselect.js
5. free-jqgrid/dist/jquery.jqgrid.min.js

The order used is very important to make column chooser to work.
