### ISSUE TITLE
showlink formatter not working

### ISSUE THREAD

**Issue by byterock** [free-jqgrid/jqGrid#383]
Just playing about today and noticed that this

formatter:'showlink', formatoptions:{baseLinkUrl:'someurl.php', addParam: '&action=edit'}

no longer works all I get is the URL for the present page

does this still work on Free JQGRID??

**Comment by OlegKi** [comment]
Could you provide the demo, which reproduces the problem? Include expected results of the link produced and the results, which you have in the grid instead. In my tests I could see any problems and the formatter produces `<a>` elements with `href` like `someurl.php?id=myrowid&action=edit`.

**Comment by byterock** [comment]
I will close this one.

It was a problem on my part.  Seems there was some older code, that generates the model, that I forgot about.  It was overriding the any 'formatter:showLink'  with the 'baseLinkUrl'  with other some custom code.

Sorry about that
