### ISSUE TITLE
Multiselection questions

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#391]
Hi Oleg, I have few question about the multiselection on the jqgrid (I have already checked your demo http://www.ok-soft-gmbh.com/jqGrid/OK/multiPageSelection.htm) .

I possible to show\hide the checkbox of the multiselection line by line? I have a column that when is valorized with cause the hide of the checkbox.

Also is possible to limit the line selection just when a user click on the checkbox instead of the click on the entire line?

And also a last thing how I can retrive a column value for all the lines selected?

Thanks

**Comment by OlegKi** [comment]
Hi Ant02!

Free jqGrid have many options, callbacks and events which allow to customize selection (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/ts/free-jqgrid.d.ts#L1152-L1171) the description of the option in TypeScript). For example, `hasMultiselectCheckBox` callback can be used to specify, which rows should not contain multiselect checkbox. The callback `beforeSelectRow` will be called on every click inside of the grid. One can return `false` from the callback to prevent selection. The ids of selected rowd will be saved in the `selarrrow` array. Look at the demo https://jsfiddle.net/768z549w/ which demonstrates the most features, which you asked my.

**Comment by Ant02** [comment]
It works perfectly thank you! A last question how I can disable the select all from the header?

Thanks

**Comment by OlegKi** [comment]
I'm not sure, where you see any problem. The id of "select all" chechbox is `"cb_grid1"` (where `grid1` is the grid id). Thus you can disable it like any other checkbox of HTML page:
```JavaScript
$("#cb_grid1").prop("disabled", true);
```
or better as
```JavaScript
$("#cb_" + $.jgrid.jqID($grid[0].id))
    .addClass("ui-jqgrid-disablePointerEvents")
    .prop("disabled", true);
```
See https://jsfiddle.net/768z549w/2/

**Comment by Ant02** [comment]
thank you
