### ISSUE TITLE
Jqgrid get the column sum dinamically basign on the filters

### ISSUE THREAD

**Issue by Flanders89** [free-jqgrid/jqGrid#393]
Hi Oleg,

there is any way to calculate the sum of column dinamically basing on the filters applied?
Also I would like to have the sum of the full rows not by page is something that I can do?

Thanks

**Comment by catbadger** [comment]
Things that will aid in this request:
Sum of what? Sum of the column values, or widths? 

Have you tried getting the grid's data and iterating over it?

**Comment by Flanders89** [comment]
Sum of the columns values inside the single cell.
I'm able to have it when the grid is loaded the first time but I'm not able to retrive it dinamically when the filter is applied(I'm using loadOnce: true so when I do the filtering I'm not applying it on the DB query but just on the data on real time).

**Comment by OlegKi** [comment]
@Flanders89 : please send more details of what you do. Which `datatype` you use? Do you need to calculate the sum of *local* data? Free jqGrid supports `lastSelectedData` parameter in case of usage local data. It's close to `data` parameter, but contains only filtered data. You can get the data and calculate the loop inside of simple loop. You can do this for example inside of `loadComplete` callback and to set the sum in the summary/footer line.

**Comment by Flanders89** [comment]
@OlegKi  Hi Oleg I have a paged jqgrid with loadOnce: true so I load data from DB only at first time.
What I need is to have a way to sum all the data for a "number" column and have it refreshed everytime that a filter is applied on the grid, Is something that I can do? Do you have any example?

**Comment by OlegKi** [comment]
@Flanders89 I made the demo https://jsfiddle.net/qdqpmj2x/ for you to demonstrate what I mean in my previous comment. Next time *you* should prepare the demo, which demonstrate what you do currently. If you want that somebody help you then you should try to save the time of persons, who try to help you.

**Comment by Flanders89** [comment]
@OlegKi thank you for your great help and sorry about the demo that I didn't provide to you
