### ISSUE TITLE
Jqgrid horizontal scrolling event

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#397]
Hi Oleg,

there is any jqgrid event that gets fired once that user scroll the horizontal scrollbar of the jqgrid?

here I have created a small fiddle to show a jqgrid with an horizontal scrollbar

https://jsfiddle.net/01th999n/23/

Thanks

**Comment by OlegKi** [comment]
Hi!

You can just bind `.scroll` to the body div of jqGrid. I added in the demo https://jsfiddle.net/OlegKi/01th999n/24/ `span id="log"></span>` below the grid and set the value of `scrollLeft` property of the body div inside:
```JavaScript
$grid.closest(".ui-jqgrid-bdiv").scroll(function () {
    $("#log").text(this.scrollLeft);
});
```
During horizontal scrolling you will see the `scrollLeft` in the span.

**Comment by Ant02** [comment]
It's works thank you
