### ISSUE TITLE
Jqgrid filter option selection with keyboard

### ISSUE THREAD

**Issue by Ant02** [free-jqgrid/jqGrid#401]
Hi Oleg currently in jqgrid when I'm in the filter area and I press the Tab button inside a filter boxbox I move in the next filter textbox (demo https://jsfiddle.net/01th999n/26/).

My question (related to my demo) is possible when I press Tab in the "address" filter textbox to select and open the filter options of the "wage" column and then with key down and key up select the operation and with enter press select the option?

So I'm trying a way to don't use everytime the mouse for the filter operatior selection.

Do you have any suggestion?

Thanks

**Comment by OlegKi** [comment]
I'm not sure that I understand you correctly. You write about the filter options of the "wage", but you don't use `stype: "select"`. Additionally, you don't wrote which version of free jqGrid you use currently. I modified your demo to https://jsfiddle.net/OlegKi/01th999n/29/, where I used `generateValue: true` or `generateDatalist: true` properties of `searchoptions` to generate select of textbox with `<datalist>`. I hope it's what you want to implement.

**Comment by Ant02** [comment]
I'm currently using jqGrid 4.14.0, and maybe I have explained wrong my need. 
There is any way to open the filter options(this showed in the screenshot) with the keyboard and navigate the options (greater, greater or equal, etc..) with key down and key up buttons?
![image](https://user-images.githubusercontent.com/27280862/33523379-624a70bc-d805-11e7-8e43-80994de90831.png)

**Comment by OlegKi** [comment]
The menu for choosing of filter operation isn't support keyboard navigation out of the box, but you can easy implement the behavior based on your requirements. For example the demo https://jsfiddle.net/01th999n/30/ allows to choose the filter operation in the "wage" column. One can use <kbd>Tab</kbd> and <kbd>Shift-Tab</kbd> to navigate over menu items. By pressing the <kbd>Enter</kbd> key one sets the focus on the "wage"-select. The example code used in the demo is
```JavaScript
$("a[data-colname=wage]")
    .attr("tabindex", "0")
    .on("focus", function () {
	$(this).click();
        setTimeout(function () {
            $(".g-menu-item[data-oper='>']").focus();
            $(".g-menu-item").keyup(function (e) {
                if (e.which == 13) {
                    $(this).click();
                    $("#gs_grid_wage").focus();
                }
            });
        }, 0);
});
```
You can modify the code like you want. For example, you can extend the code of `keyup` to allow to use <kbd>Up</kbd> and <kbd>Down</kbd> keys for navigation in the menu.

**Comment by Ant02** [comment]
Hi Oleg

the tab click is working correctly, but the is any when I'm in the wage menu items to select the current 
selected item with the same style that you use on the mouse hover instead of the dotted line?

![image](https://user-images.githubusercontent.com/27280862/33838720-9a7f7a68-de90-11e7-990e-3faffbc44e69.png)

**Comment by OlegKi** [comment]
You cab set any CSS style on the focused item by applying CSS rule on `.ui-search-menu.ui-menu .ui-menu-item a:focus`. For example, the demo https://jsfiddle.net/OlegKi/01th999n/32/ uses
```css
.ui-search-menu.ui-menu .ui-menu-item a:focus {
	background: aquamarine;
}
``` 
![menu1_](https://user-images.githubusercontent.com/249117/33869701-8d8f7202-df0a-11e7-9bc7-217b6baddbe2.png)

and another demo https://jsfiddle.net/OlegKi/01th999n/33/ uses the same settings like `ui-state-hover` from jQuery UI css:
```css
.ui-search-menu.ui-menu .ui-menu-item a:focus {
    border: 1px solid #79b7e7;
    background: #d0e5f5 url("images/ui-bg_glass_75_d0e5f5_1x400.png") 50% 50% repeat-x;
    color: #1d5987;
}
``` 
![menu2](https://user-images.githubusercontent.com/249117/33869706-9256493c-df0a-11e7-9fe2-85231fad634c.png)

**Comment by Ant02** [comment]
thank you for the help!
