### ISSUE TITLE
jqGrid old WIKI page not working

### ISSUE THREAD

**Issue by zajc** [free-jqgrid/jqGrid#404]
Couple of days the http://www.trirand.com:80/jqgridwiki/doku.php stops working. The documentation there is still very helpful. Is there any alternative site or at least backup of that site.

**Comment by OlegKi** [comment]
Sorry, but I have no access to  http://www.trirand.com:80/jqgridwiki/doku.php. You could try to contact Tony Tomov at https://github.com/tonytomov/jqGrid/issues for example.

The information, which I can suggest is [free-jqgrid.d.ts](https://github.com/free-jqgrid/jqGrid/blob/master/ts/free-jqgrid.d.ts), https://free-jqgrid.github.io/getting-started/index.html and https://github.com/free-jqgrid/jqGrid/wiki. The file contains no comments, but it describes (in TypeScript language) practically all existing options, callbacks and events existing in free jqGrid.

**Comment by zajc** [comment]
Thanks.
