### ISSUE TITLE
It's possible to use Select2js while inline editing?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#410]
I want to switch from DataTables to jqGrid in a new project I am working on and some of the features I should provide is inline editing. I did know that's supported by jQgrid ([example here](http://www.ok-soft-gmbh.com/jqGrid/OK/focusOfEditRow.htm)) but because there is a lot of data available on such column I would like to use [Select2js](https://select2.org/) for this purpose.

Is this possible? If so how? Can you provide me with a single example so I can try on my end?

**Comment by catbadger** [comment]
Yes it's possible, but it's very unlikely someone will do it for you.

**Comment by reypm** [comment]
@catbadger I don't want anyone do it for me I just need an example in how to do it and I will continue from there, makes sense? :)

**Comment by OlegKi** [comment]
One can easy use select2 with free jqGrid. I posted some answers on the stackoverflow about the subject. I posted the demo https://jsfiddle.net/OlegKi/su7ebs65/ in [the readme](https://github.com/free-jqgrid/jqGrid/blob/master/README4.14.1.md#new-main-features-implemented-in-the-version-4141-compared-with-4140
https://jsfiddle.net/OlegKi/su7ebs65/) of the version 4.14.1. The demo https://jsfiddle.net/OlegKi/9uvzumop/ is simple modification of the demo. I added the usage of select2 in editing additionally to the usage in the filter toolbar. I think it's what you need. Additionally I recommend you to look at the feature `generateDatalist: true` in the filter toolbar to "Clients" column. It uses `<datalist>` native supported by many web browsers and it's more quickly as jQuery UI Autocomplete.

**Comment by reypm** [comment]
@OlegKi thanks for the answer that's exactly why I need and see @catbadger he didn't do the job for me just show me how to do it :) I will close this for now and will reopen it if I found any issues having this to work

**Comment by reypm** [comment]
@OlegKi In the example you leave here where the options for the Select2 element are coming from? Is there any chance to trigger an AJAX call to get those options from the server instead? If you've a time could you modify the example to reflect this behavior? Thanks in advance

**Comment by OlegKi** [comment]
I used `edittype: "select", editoptions: {  generateValue: true, ... }` to generate `value` dynamically from different data already loaded in the grid. One can specify for example `value: "FedEx:FedEx;DHL:DHL;TNT:TNT"` directly or to use `dataUrl` and optionally `buildSelect` and `ajaxSelectOptions` to get the data for `<select>` from the server and to convert there to HTML fragment with `<select>`. Select2 will convert **any** `<select>` to select2. See  https://jsfiddle.net/OlegKi/9uvzumop/1/

**Comment by reypm** [comment]
@OlegKi can you post any of the previous answers on SO you mention before? My idea is to use the Select2 element to perform the search I think I can achieve the same using `ajaxUrl` but is no so complete as Select2 it's
