### ISSUE TITLE
TypeScript: Rersharper error when errorTextFormat is set for delGridRow()

### ISSUE THREAD

**Issue by askrinnik** [free-jqgrid/jqGrid#416]
Hi @OlegKi 
I wanted to invoke delGridRow method with setting errorTextFormat:
```
grid.delGridRow(rowId, {
  errorTextFormat(data: JQueryXHR) {
    return data.responseText;
  }
});
```
But  I got an error from Resharper:

> Supplied parameters do not match any signature of call target: parameter type mismatch. Parameter 'options' should have type assignable to 'FreeJqGrid.FormDeletingOptions', but it has type '{ [index: string]: (data: JQueryXHR) => string; errorTextFormat: (data: JQueryXHR) => string}'.

    
It caused because the second parameter of the method is options: FreeJqGrid.FormDeletingOptions
The interface doesn't have errorTextFormat. But in fact it is used in javascript code of the grid

I managed to fix the error when added a property errorTextFormat into interface FormDeletingOptions in free-jqgrid.d.ts
`errorTextFormat?: (this: BodyTable, data: JQueryXHR) => string;`

Is this correct way?

**Comment by OlegKi** [comment]
Thanks you Alexander for the feedback! You are right - some properties / callbacks missing in `FreeJqGrid.FormDeletingOptions`. I looked one more thought the code and extended `FormDeletingOptions` (see [the commit](https://github.com/free-jqgrid/jqGrid/commit/abe4ffc5a3ab6c5aa1ff14bb1bfebbeea5cc1cb7)). The problem should be fixed now.

**Comment by askrinnik** [comment]
Sounds great. Thanks a lot!
