### ISSUE TITLE
Number Formatter based on edit/read status

### ISSUE THREAD

**Issue by Toumi0812** [free-jqgrid/jqGrid#429]
Hi Oleg,

I would like to change the decimal places when a cell is in edit mode.
As you can see in https://jsfiddle.net/j2g5rfu3/13/ the column Number has no decimal places so editing the number e.g. 12.43 when I save I will see only 12 and on mouse over I see in tooltip 12.43.
I would like to see 12.43 when I am editing.  Is there a way to change the formatter to be able to see the decimals in editing mode?

Thanks,
Hicham

**Comment by OlegKi** [comment]
I'm not sure that I correctly understand, which you want to implement, but I can suggest you to add the following unformatter (`unformat`) function to the definition of the column with the number:
```JavaScript
unformat: function (value, options, domOfCell) {
    var item = $(this).jqGrid("getLocalRow", options.rowId);
    return item[options.colModel.name];
}
```
The unformatter returns the value, which was previously saved locally. See https://jsfiddle.net/j2g5rfu3/40/
