### ISSUE TITLE
Form edit and formatter: checkbox

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#432]
For demo https://jsfiddle.net/yzyj77ay/36/
When use form edit and checkbox formatter with last version , in the 2nd row, even if I check the checkbox , the value for ver  is all F.

**Comment by OlegKi** [comment]
Thank you for the bug report. I posted [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/8904b54c5e0a06821cbaddd0f5bab373e0ae718c) to GitHub. See https://jsfiddle.net/yzyj77ay/55/, which uses the modified code.

**Comment by InaraSolutions** [comment]
I think this bugfix merits a minor version bump and release, since the current "stable" release (4.15.4) is broken for systems using form checkboxes and not everyone checks github issues to know that there's a patch available.
