### ISSUE TITLE
Question: Can I use treeGrid with subGrid?

### ISSUE THREAD

**Issue by madnetmad** [free-jqgrid/jqGrid#433]
Hi Oleg,
at first I want to thank you for continue free-jqGrid development.

I did an extensive search but didn't found any example of such implementation, neither found a comment that this isn't possible.
I made some tries but results are not any good. I get the "plus" icon for subGrid but is not clickable.

Thank you

**Comment by madnetmad** [comment]
What I want to do is the following:
2 grids
1. In this grid you can add/edit/delete Items with some set of options (Done)
2. In this grid you can add/edit/delete Categories with some set of options (Done)
PLUS you can assign Items to any of the Categories AND edit some set of Item options related to the category they are under. Categories may be 2-3 or more levels in depth.

So one can assign the item with id:1 to many categories but with different set of options for each category.

I made a jsfiddle example and I tried to keep it us minimal as I could.
https://jsfiddle.net/g4bg3wza/
You can see that I get the "+" icons for the subGrids but are not clickable.

**Comment by madnetmad** [comment]
So, is that a bug? or treeGrid can't work with subGrid by design?

**Comment by OlegKi** [comment]
I thought about your problem a little more and I think that in your case you can try to use the following workaround
```JavaScript
onInitGrid: function () {
    this.p.subGrid = true;
}
```
See https://jsfiddle.net/OlegKi/g4bg3wza/3/

**Comment by OlegKi** [comment]
In general, you are right, but the code of `treeGridBeforeCollapseRow` have to collapse not only the subgrid of the current row, but the subgrids of any child node too. You can try for example to do the following:
 1. to collapse to node "Category 1-1-1"
 2. to expand subgrids of the node "Category 1-1-1"
 3. to collapse the node "Category 1"
One will still see the subgrid of the node "Category 1-1-1" under the collapse node "Category 1".

Nevertheless, one can follow the same idea and to collapse all child nodes of currently collapsing. One can use `getFullTreeNode` method to get the nodes. See https://jsfiddle.net/OlegKi/g4bg3wza/10/ where I made the corresponding modifications and to fix your code a little to make it working in case of usage `idPrefix` in the main grid too. The code of `treeGridBeforeCollapseRow` includes in the demo is the following:
```JavaScript
treeGridBeforeCollapseRow: function(options) {
    var $self = $(this),
        collapsingNodes = $self.jqGrid("getFullTreeNode", options.item),
        p = $self.jqGrid("getGridParam"),
        idName = p.localReader.id,
        iColSubgrid = p.iColByName.subgrid;

    collapsingNodes.forEach(function (item) {
        var tr = $self.jqGrid("getGridRowById", p.idPrefix + item[idName]),
            $td = $(tr.cells[iColSubgrid]);

        if ($td.hasClass("sgexpanded")) {
            $td.children(".sgbutton-div")
                .children(".sgbutton")
                .click();
        }
    });
}
```

**Comment by madnetmad** [comment]
You are right. I didn't check the combination of collapsed treeNode with expanded subGrid.
A right Prefix is also a must. 
Thanks again for the workaround.
