### ISSUE TITLE
Grid size change and scrollbar disappears when autoresizing column

### ISSUE THREAD

**Issue by gabounce** [free-jqgrid/jqGrid#435]
Hi, 

I should use a grid with a limited size and a large number of columns. In this use case, I thus have a horizontal scrollbar in order to see all my data. I'm using version 4.15.3

I have a bug when I try to autoresize one column : the scrollbar disappears and the size of the grid has increased in order to display all the columns, which thus destroys the design of my page.

I also got the same problem by using the resizeDblClick callback as follows : 
```JavaScript
resizeDblClick(iCol, data, evt) {
    $('#MyGrid').jqGrid('autoResizeColumn', iCol);
    return false
}
```
Thanks in advance for your help

**Comment by OlegKi** [comment]
Please post **full demo** inclusive JavaScript code and the test data, which can be used to *reproduce* the problem, which you reports. The only small fragment of the code, which you use has no sense, because if you don't define any `resizeDblClick` callback then `autoResizeColumn` will be called by default. See [the lines of code](https://github.com/free-jqgrid/jqGrid/blob/v4.15.4/js/grid.base.js#L6139-L6142).

**Comment by gabounce** [comment]
Here are below 2 demos (both reproduce the same problem). 

Demo 1 (without using resizeDblClick callback)
[https://jsfiddle.net/Gabounce/w9dntm40/1/](https://jsfiddle.net/Gabounce/w9dntm40/1/)

Demo 2 : (using resizeDblClick callback)
[https://jsfiddle.net/Gabounce/nkfypk0h/2/](https://jsfiddle.net/Gabounce/nkfypk0h/2/)

**Comment by OlegKi** [comment]
I can see from the demos your problem.

In demo 1 one can solve the problem by adding the option
```JavaScript
autoResizing: {
    adjustGridWidth: false
}
```
See https://jsfiddle.net/OlegKi/w9dntm40/4/

In demo 2 one can solve the problem by usage the second parameter of the method `autoResizeColumn`:
```JavaScript
resizeDblClick: function (iCol) {
    $(this).jqGrid('autoResizeColumn', iCol, true);
    return false;
}
```
See https://jsfiddle.net/OlegKi/nkfypk0h/4/
See [here](https://github.com/free-jqgrid/jqGrid/blob/v4.15.4/ts/free-jqgrid.d.ts#L1733) and [here](https://github.com/free-jqgrid/jqGrid/blob/v4.15.4/ts/free-jqgrid.d.ts#L1338) for more details.

**Comment by gabounce** [comment]
That's exactly what I was looking for. Thank your very much for your fast answer.
