### ISSUE TITLE
Nav add button afterSubmit postData.id Revise invalid

### ISSUE THREAD

**Issue by centercao** [free-jqgrid/jqGrid#436]
v4.15.4 Nav add button afterSubmit postData.id Revise invalid, id = jpg1

**Comment by OlegKi** [comment]
Sorry, but it's unclear for me what you mean. Could you provide **the demo**, which can be used to reproduce the problem. Typically the problem with ids like jpg1 exists if one **fills** the grid in the wrong way. jqGrid fill the grid based on the input data and it sets `id` attribute for every row. See [here](https://free-jqgrid.github.io/getting-started/index.html#grid-internal-div). *Only if the input data doesn't contains `id` information* jqGrid **generates** unique ids with values like jpg1. Other parameters like `id` property of `prmNames` parameter or the `key: true` property in one column of of the `colModel` could changes the default behavior.
You should review the input data and verify that it contains `id` information. If you would have some problems you should post me more information, which should include either the demo or JavaScript code with test input data, which you use to fill the grid.

**Comment by centercao** [comment]
{ // add
					checkOnSubmit:false, closeAfterAdd: true,height:280,reloadAfterSubmit:false,modal: true,jqModal: true,addedrow:'last',
					url:"/users",
					mtype:"post",
					onclickSubmit: function(params, postData) {
						return [true,''];
					},
					beforeSubmit:function(postData, formid) {
						// check
						/* if(postData.id_room.replace(/(^s*)|(s*$)/g, "").length ==0)
						 {
						 return [false,'Name is empty!'];
						 }*/
						return [true,''];
					},
					afterSubmit:function(response, postData){
						var result=response.responseJSON;
						postData.id = result.id;
						return [true,""];
					}
				}

this is  in "jQuery("#list").jqGrid('navGrid','#pager',....."
afterSubmit:function(response, postData){
						var result=response.responseJSON;
						postData.id = result.id;
						return [true,""];
					}
but new id is not  "result.id"

**Comment by OlegKi** [comment]
I suppose that you try to return the id from the server after successful Add operation. The correct code of `afterSubmit` have to return array with **3** elements in the case, where the 3-d element should be the id, returned from the server. The fixed code could look like the following:
```JavaScript
afterSubmit: function (jqXhr, postdata, editOrAdd) {
    return [true, "", jqXhr.responseJSON.id];
}
```
See [old documentation](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:form_editing#events) of `afterSubmit` or [the old answer](https://stackoverflow.com/a/13191881/315935) for additional information.

**Comment by centercao** [comment]
yes ,I try to return the id from the server after successful Add operation. I want to set id,but 
id is always jqg1.but I use "https://github.com/tonytomov/jqGrid" is OK.I think this must be a bug.

**Comment by centercao** [comment]
question: add data(no id) ->server save return id ->client to "afterSubmit:function(response, postdata)" I want set id ,I use postdata.id = ...,but table id is "jqg1". I use  "https://github.com/tonytomov/jqGrid"  as same ,is ok.

**Comment by OlegKi** [comment]
I wrote you in [my previous comment](https://github.com/free-jqgrid/jqGrid/issues/436#issuecomment-397692222) that `afterSubmit` must return array with **3** element, where the **3-d** element is the new id.

If you want to reopen the issue, that you should post the demo, which reproduce the problem or at least to post *the current* code, which you use.

I can help you **only with free jqGrid** and not with commercial **Guriddo jqGrid JS** (see [here](http://guriddo.net/?page_id=103334)) which source code is still publishing on https://github.com/tonytomov/jqGrid

**Comment by centercao** [comment]
afterSubmit: function (jqXhr, postdata, editOrAdd) {
    return [true, "", jqXhr.responseJSON.id];
}
is ok ,thanks!
