### ISSUE TITLE
actionsNavOptions on hover some action cells title problem

### ISSUE THREAD

**Issue by pribeirojtm** [free-jqgrid/jqGrid#437]
Hi,

I'm using latest freejqgrid version and I'm using `actionNavOptions`.

But I've found that, sometimes, not in every cell, the `title` shows incorrectly, just when mouseovering an action cell area (but not hovering the button(s)) .

Please find your example ( [https://jsfiddle.net/OlegKi/aw47ytqz/2/](https://jsfiddle.net/OlegKi/aw47ytqz/2/) ) bellow:

![freejqgrid_action_btn_title](https://user-images.githubusercontent.com/18724236/42212763-f709e6b0-7eae-11e8-903c-1829bfdda333.png)

Do you know why this is happening? It is a bug?

Thanks.

**Comment by OlegKi** [comment]
Thank you for the bug report. To solve the problem it's enough to add `title: false` property to the definition of the column which uses `formatter: "actions"`. I added the property to the definition of the `template: "actions"`. The same demo https://jsfiddle.net/OlegKi/aw47ytqz/2/, which loads the latest code from GitHub, works now correctly.
