### ISSUE TITLE
Feature Enhancement Request: subGridRowCollapsed callback

### ISSUE THREAD

**Issue by PhilHawkins** [free-jqgrid/jqGrid#438]
There is an option to specify a callback function for subGridRowExpanded, but not one for subGridRowCollapsed. I'm pretty sure all it requires is adding 
`if ($.isFunction(p.subGridRowCollapsed)) {
								p.subGridRowCollapsed.call(ts, subgridDivId, rowid);
							}`
after line 310 in grid.subgrid.js

**Comment by OlegKi** [comment]
There are exist `subGridBeforeCollapse` and `subGridBeforeExpand` callbacks. See https://jsfiddle.net/OlegKi/mc4epzrw/. Is it enough for your purpose?

**Comment by PhilHawkins** [comment]
That will work well enough for my purpose. Thank you.
