### ISSUE TITLE
Supporting title attribute on column headers

### ISSUE THREAD

**Issue by jimmccarthy** [free-jqgrid/jqGrid#44]
I currently truncate long column header names.  Looks like there is no great way to add a title to the th so I can get a tooltip.  Any thoughts on supporting that?

**Comment by OlegKi** [comment]
Try `headertitles: true` option of jqGrid.

**Comment by jimmccarthy** [comment]
Awesome!  Thanks for the quick response.  I should have checked the doc
instead of the code.
