### ISSUE TITLE
Same DOM id for search arrows

### ISSUE THREAD

**Issue by KWB** [free-jqgrid/jqGrid#443]
The arrows for column search seem to get the same DOM id (which should be unique). I have noticed that as I have a little code snippet which checks for id duplicates.

Those look like `arrowmenuItem9902270856030274000`, maybe this helps to locate them and give them unique ids somehow.

**Comment by OlegKi** [comment]
Sorry, but I don't understand what you mean. What you mean under "column search"? What is `arrowmenuItem9902270856030274000`?

**Could you provide the demo, which demonstrates the problem?**

**Comment by KWB** [comment]
Clearly my mistake, issue can be closed. For me it looked those ids come from jqGrid, but it is another jq component generating them. My apologies.

**Comment by OlegKi** [comment]
No problem. Thanks for the feedback.
