### ISSUE TITLE
Search box does not look the same when accessed from the search top bar button ...

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#444]
In the following example [here](https://jsfiddle.net/reynierpm/71aw2shL/3/) when you run it for first time a search box is open. Do the following:

 - close it and click on the search icon (at the top bar), why the new search box does not appears like the first one?
 - how I can remove the search box from being loaded at first when the page open?

Is this an issue or I am missing something in my configuration?

**Comment by OlegKi** [comment]
I'm not sure that I full correctly understand your question. Removing of the search box from being loaded at first when the page open is very easy. You call `searchGrid` method with the option `{ multipleSearch: true }` *explicitly* in your demo (directly after calling of `.jqGrid('setFrozenColumns')`). The same method will be called by `navGrid` if the user clicks on the Search button. Thus you can just remove `.jqGrid('searchGrid', { multipleSearch: true })`.

You asked me **"why the new search box does not appears like the first one?"** without specifying exactly which difference you mean. I suppose you mean `multipleSearch: true` option will be not used if the user click on Search button and `navGrid` calls `searchGrid` method for you. To fix that one can use additional options of `navGrid` or better to specify *default option*, which should be used by `searchGrid` method with respect of `searching` parameter of jqGrid. For example https://jsfiddle.net/OlegKi/71aw2shL/10/ uses 
```JavaScript
searching: {
    multipleSearch: true,
    //multipleGroup: true,
    width: 650,
    closeOnEscape: true,
    searchOnEnter: true
}
```

**Comment by reypm** [comment]
@OlegKi thanks for your answer I have stopped working on this piece of code for now but when I started again I will try your suggestions, for now I will close this
