### ISSUE TITLE
How to initialize grid with empty set of data and change the data source to JSON on the fly?

### ISSUE THREAD

**Issue by reypm** [free-jqgrid/jqGrid#446]
I am trying to start an "empty" grid with no data available and the code looks like:

```
var questions = $('#questions')
questions.jqGrid({
  data: {},
  datatype: 'local',
  colNames: ['id', 'grid_id', 'seq', 'type', 'text'],
  colModel: [
    {name: 'field_id', index: 'id', width: 100},
    {name: 'grid_id', index: 'grid_id', width: 50},
    {name: 'field_seq', index: 'seq', width: 45},
    {name: 'type', index: 'type', width: 125},
    {name: 'field_name', index: 'text', width: 585}
  ],
  autowidth: true,
  rowNum: 200,
  cmTemplate: {autoResizable: true,  editable: false, search: false},
  viewrecords: true
}).jqGrid('hideCol', 'cb')
  .jqGrid('sortableRows', {
    update: function (e, ui) {
      var selectedRowId = questions.jqGrid('getGridParam', 'selrow')
      var cellValue = questions.jqGrid('getCell', selectedRowId, 'field_seq')
      resequence_questions(site_url)
      questions.trigger('reloadGrid', {fromServer: true})
    }
  })
  .jqGrid('navGrid', {
    reloadGridOptions: {fromServer: true}
  })
```
The code above worked fine. Now I want to change the `datasource` from `local` to `json` and of course add a URL for fetch the data. The code below is the one doing that:

```
const selected_form = $('#selected-form')
selected_form.select2({
  ajax: {
    url: '/ajax/forms/get_all',
    dataType: 'json',
    cache: false
  },
  placeholder: 'Select a form',
  selectOnClose: true,
  allowClear: true
}).on('select2:select', function (e) {
  const form_id = e.params.data.id
  update_grid(form_id)
})

function update_grid (form_id) {
  const questions_grid = $('#questions')
  const options_grid = $('#options_grid')
  site_url = sessionStorage.getItem('site_url')

  questions_grid.setGridParam({
    url: site_url + 'ajax/questions/get/' + form_id,
    datatype: 'json'
  })

  $('#grid_cells_example').html('')
  questions_grid.trigger('reloadGrid', {fromServer: true})

  options_grid.clearGridData()
  options_grid.trigger('reloadGrid')
}
```
Anytime I call the `update_grid()` function like on the `select2:select` event the following error appears on the console:

```
Uncaught TypeError: x.data.push is not a function
    at HTMLTableElement.H (jquery.jqgrid.src.js:4170)
    at Object.success (jquery.jqgrid.src.js:4715)
    at i (jquery-3.2.1.min.js?v=1534191965:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js?v=1534191965:2)
    at A (jquery-3.2.1.min.js?v=1534191965:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js?v=1534191965:4)
```
What I am doing wrong?

**Comment by OlegKi** [comment]
Please specify **always** the version of free jqGrid, which you used in your tests. The line numbers of errors (jquery.jqgrid.src.js:4170, jquery.jqgrid.src.js:4715) gives no information without knowing the exact version of free jqGrid.

It's better to provide **the demo**, which can be used to reproduce the problem. I can't see any clear error in the code, which you posted. Just don't use and semicolon, the variables `site_url` and `options_grid` are undefined. I can only guess that you could initialize `data` parameter of jqGrid to some wrong value.

I'd recommend you to verify that you don't use any `data` parameter to create the grid and you can add add `data: []` option to `setGridParam` options.

**Comment by reypm** [comment]
@OlegKi,

sorry about the version I completely forgot to mention it ... anyways is the latest and what I read on the `jquery.jqgrid.src.js` is `4.15.5-pre`.

**Comment by OlegKi** [comment]
4.15.5-pre is not a version. It's just a state between 4.15.4 and 4.15.5 and I can't get the 4.15.5-pre of `jquery.jqgrid.src.js`, which you use. Could you upgrade to 4.15.5, repeat the test and post the line numbers of `jquery.jqgrid.src.js` of 4.15.5, where you have the problem.?

**Comment by reypm** [comment]
@OlegKi, I have downloaded 4.15.5 from [here](https://github.com/free-jqgrid/jqGrid/archive/v4.15.5.tar.gz) after unzip that file I went to `dist` folder and open the file `jquery.jqgrid.src.js` from there is where I got the `4.15.5-pre`. 

I repeated the test and the error change into:

```
Uncaught TypeError: ee.data.push is not a function
    at HTMLTableElement.N (jquery.jqgrid.src.js:4283)
    at Object.success (jquery.jqgrid.src.js:4828)
    at i (jquery-3.2.1.min.js?v=1534191965:2)
    at Object.fireWith [as resolveWith] (jquery-3.2.1.min.js?v=1534191965:2)
    at A (jquery-3.2.1.min.js?v=1534191965:4)
    at XMLHttpRequest.<anonymous> (jquery-3.2.1.min.js?v=1534191965:4)
```
Is this helpful? I am trying to setup the demo in a Fiddle but not sure if I can make it to work properly.

**Comment by reypm** [comment]
@OlegKi I have found the issue however I don't know the why: by removing the `data` from the first definition it makes it to work. See below:

Before:
```
questions.jqGrid({
  data: {},
  datatype: 'local',
  colNames: ['id', 'grid_id', 'seq', 'type', 'text'],
  colModel: [
    {name: 'field_id', index: 'id', width: 100},
    {name: 'grid_id', index: 'grid_id', width: 50},
    {name: 'field_seq', index: 'seq', width: 45},
    {name: 'type', index: 'type', width: 125},
    {name: 'field_name', index: 'text', width: 585}
  ],
  autowidth: true,
  rowNum: 200,
  cmTemplate: {autoResizable: true,  editable: false, search: false},
  viewrecords: true
})
```

After:
```
questions.jqGrid({
  colNames: ['id', 'grid_id', 'seq', 'type', 'text'],
  colModel: [
    {name: 'field_id', index: 'id', width: 100},
    {name: 'grid_id', index: 'grid_id', width: 50},
    {name: 'field_seq', index: 'seq', width: 45},
    {name: 'type', index: 'type', width: 125},
    {name: 'field_name', index: 'text', width: 585}
  ],
  autowidth: true,
  rowNum: 200,
  cmTemplate: {autoResizable: true,  editable: false, search: false},
  viewrecords: true
})
```
I will close this since is not an issue anymore nor a bug and feel free to comment anything if you want to.

Thanks for point me in the right direction

**Comment by OlegKi** [comment]
The line [#4283](https://github.com/free-jqgrid/jqGrid/blob/v4.15.5/js/grid.base.js#L4283) contains the following line of code:
```JavaScript
p.data.push(rd);
```
The message `ee.data.push is not a function` means that you use corrupted `data` parameter. I suggested you in the previous comment to reset `data` parameter explicitly to an empty array before triggering `reloadGrid`. Do you tried that?

**Comment by reypm** [comment]
Ok, one more question/doubt: is there any way to get the row count after reload the grid with the new server side data? For example I am trying to do it as follow:

```
function update_grid (form_id) {
  const options_grid = $('#options_grid')
  questions.setGridParam({
    url: 'ajax/questions/get/' + form_id,
    datatype: 'json'
  })

  questions.trigger('reloadGrid', {fromServer: true})
  const count = questions.jqGrid('getGridParam', 'reccount')
  console.log(count)
}
```

But I got `0`

**Comment by OlegKi** [comment]
I reload the page and can see your other posts. One can see that you use `data: {}` which is **wrong**. The `data` parameter have to be array. The empty array `[]` is the default value and you should don't change it.

**Comment by reypm** [comment]
@OlegKi yup, I tested it the original code by changing `data: {}` into `data: []` and it worked I guess that removing the option will defaulted to `data:[]` which is the why is working after removed the wrong one.

**Comment by OlegKi** [comment]
Answer on your question from your lats comment. `questions.jqGrid('getGridParam', 'reccount')` should be used **after the data have loaded from the server**. Thus you have to move the line inside of `beforeProcessing` callback for example or inside of `loadComplete` callback. The callback `beforeProcessing` have raw data returned from the server as parameter. I think you know how to get the number of items having the data. Inside of `loadComplete` callback you can use your existing code `$(this).jqGrid('getGridParam', 'reccount')`.
