### ISSUE TITLE
addRow for 'before/after' position

### ISSUE THREAD

**Issue by truelife2** [free-jqgrid/jqGrid#447]
hi,
the addRow has a position option, but when use after/before position,lose a src argument for addRowData

maybe can add a position_src for this ?

$self.jqGrid("addRowData", o.rowID, o.initdata, o.position);
=>$self.jqGrid("addRowData", o.rowID, o.initdata, o.position,o.position_src);

**Comment by OlegKi** [comment]
Free jqGrid supports `"afterSelected"` and `"beforeSelected"` values for position, which are sufficient for the most cases. Nevertheless, your suggestion is very easy to implement and I committed the corresponding changes just now (see [here](https://github.com/free-jqgrid/jqGrid/commit/031ca4811ba93f66e117098147dc3a21267b0b43)). It should solve your requirements.

**Comment by truelife2** [comment]
thank you very much, this help me
