### ISSUE TITLE
afterSaveCell event is not fired

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#45]
this.jqGrid=$('#grid').jqGrid({afterSaveCell:function(rowid, cellname, value, iRow, iCol){
//This is never fired
}});

or
this.jqGrid.bind('jqGridAfterSaveCell', function (rowid, nm, v, iRow, iCol) {
                        //This is not fired either
                    });
Am I use it in wrong way? but  beforeSaveCell event fired correctly.

**Comment by OlegKi** [comment]
Thank you very much for the bug report. I introduced the internal method `$.jgrid.feedback` which I use internally to make the most callbacks and to trigger events. The `$.jgrid.feedback` method had at the beginning less parameters as now, but I didn't make the corresponding changes in cell editing module.

I fixed the problem now. You should refresh your sources from github. 

To use correctly `jqGridBeforeSaveCell` you need add one more parameter to the event handler:
```JavaScript
$('#grid').bind('jqGridBeforeSaveCell', function (e, rowid, nm, v, iRow, iCol) {
//This is not fired either
});
```
where the first `e` parameter have the type [Event](https://api.jquery.com/category/events/event-object/) like all other jQuery events.

**Comment by ryanlin1986** [comment]
Thank you so much for the great hard work on the free-jqGrid, really helped us a lot.

**Comment by OlegKi** [comment]
You are welcome! I close the issue.
