### ISSUE TITLE
Allow only one cell per row to be selected. Not working after a sort is performed

### ISSUE THREAD

**Issue by hoalzein** [free-jqgrid/jqGrid#462]
My goal is to be able to highlight a cell when clicked and remove highlight when clicked again. Each row can have only one cell highlighted. I have attempted to get it to work but whenever the grid is sorted, my target functionality doesn't seem to work anymore. Any help or suggestion will be highly appreciated. 
Here is the demo https://jsfiddle.net/hoalzein/hwondp71/9/

**Comment by OlegKi** [comment]
Sorry for the delay. I was very busy last time. I found that you posted the same question to stackoverflow. You will find my answer [here](https://stackoverflow.com/a/53896298/315935).

**Comment by hoalzein** [comment]
Thanks @OlegKi for your effort !!! I really appreciate.  Problem 100% solved.
