### ISSUE TITLE
Issue with Bootstrap 4 and Dialog

### ISSUE THREAD

**Issue by rbruhn** [free-jqgrid/jqGrid#464]
Using v4.15.5
Demos:
Edit Page: https://dev.biospex.org/demo.html
View Page: https://dev.biospex.org/demo2.html

When clicking the search icon to bring up the dialog on the Edit page, the search box is way off the screen. You can't even scroll to it. The only way to make it visible is to remove the form section. Whatever is calculating the distance from "top" simply isn't working.

On the View page, it works but if you scroll down to the bottom, then click search, the dialog appears at the bottom of the table..... where the top of the table would have been if you hadn't scrolled down.

When clicking the column chooser in both cases above, it appears where it should.

So my question: How can I fix this situation so the dialog for search (and the delete dialog) show up correctly for both pages? Or, at least for the Edit page so it can at least be seen.

Thank you.

**Comment by OlegKi** [comment]
Could you describe more exactly how the problem could be reproduced? You wrote about "the search icon" which I don't see neither on the "Edit Page" nor on the "View Page" . Clicking on other buttons require some kind of authentication.

Additionally it's better to create separate demo on JSFiddle for example which reproduce the problem, which you want to report. I don't want to debug your whole solution, but I can try to solve free jqGrid problems, which you have.

**Comment by rbruhn** [comment]
I ended up fixing this issue.
