### ISSUE TITLE
0 value converted to empty string while using standard edit form 

### ISSUE THREAD

**Issue by AuthorProxy** [free-jqgrid/jqGrid#47]
> jqGrid  4.8.0-post - free jqGrid
> Date: 2015-03-22

Use case: edit row with standard form editing. Instead 0 value in field, I got empty field.

In some of my columns I was having next `unformat` rule:

    function unformatObject(entry, el, td) {
      return $(td).find('span').data('id') || null;
    }

Everything was ok, until I met bug that instead 0 value, I got null, so I little update my func to next:

    // return 0, not empty value or null
    function unformatObject(entry, el, td) {
      var elData = $(td).find('span').data('id');
      return elData === 0 ? 0 : elData || null;
    }

But the problem don't dissapear, cause this rule change 0 value to '':
````
if (!tmp || tmp === "&nbsp;" || tmp === "&#160;" || (tmp.length === 1 && tmp.charCodeAt(0) === 160)) {
  tmp = '';
}
````

Yes I know that i can just change `...0 ? 0 : ...` to `...0 ? '0' : ...`, but it looks like unintuitive behaviour on the lib, because 0 it's a concrete value of an entry field, and not empty value. Or may be I missed something?

For some research may be you will need some more information, here is my `formatter` function:

````
  function formatObject(entry) {
    if (_.isString(entry) || _.isNumber(entry)) {
      entry = _.defaults({}, entry, {
        id: entry,
        name: entry || undefined
      });
    }

    entry = _.defaults({}, entry, {
      name: 'Not specified'
    });

    var $container = $('<span />', {
      text: entry.name,
      'data-id': entry.id
    });

    if (!entry.id) {
      $container.addClass('gridcell-undefined');
    }

    return $container[0].outerHTML;
  }
````

And here is how my grid cell looks finaly:
```
<td role="gridcell" style="text-align:center;" title="0" aria-describedby="jqGrid_phoneNumber">
    <span data-id="0">0</span>
</td>
```

Here is simplified use case demo: http://jsfiddle.net/AuthorProxy/Ly7vcjv3/1/

**Comment by OlegKi** [comment]
Sorry, but could you provide more clear description what you do? You have some input data which you use to create and to fill jqGrid. Which options you use to create the grid? Which input data (test data) you use? You have problem in **form editing** for one column. So you have to include at least the definition of the column in `colModel`. You posted the code of formatter and unformatter, but **no options which are related for editing**. If I correctly understand you then you have the problem in *editing* and not with formatting?

Even the formatter and unformatter seems strange for me. **Which `datatype` you use in the grid? Do you use `loadonce: true` or not?** The `entry` parameter of `formatObject` looks like an object, which is untypical. **In the case you should provide the test data for `entry`.** All other functions used in the formatter seems strange for me to. I suppose that you use underscore, which I personally not use. Which value have `entry` in your test? What do `_.defaults`, `_.isString` and other method? If `_.isString(x)` just do `typeof x === "string"` then why one should use any function? It makes the code only slowly. Isn't so. It's very important to understand, that formatter will be used for every cell in the loop. So **the performance of the code of formatter is critical for the total performance of the filling of the grid**. If you would make the code of the formatter slowly then the grid will works also slowly. I suppose that the code of `formatObject` which you posted can be rewritten to work at least 10-100 times quickly if you would use standard JavaScript functions and no Underscore and jQuery methods. Look [the article](http://learn.jquery.com/performance/append-outside-loop/) for example. One have the best performance if one just construct strings with HTML fragments. It's the main idea of custom formatters, `rowattr` and `cellattr` callbacks. **The whole content of `<tbody>` will be constructed as string in case of usage `gridview: true`**. The string will be placed on the page as one DOM operation. So I recommend you to rewrite the formatter to improve the performance of the grid.

In any way, to be able to help you in the main problem, which you posted, I have to have clear code with clear test case. The most productive will be **to provide the demo which reproduces the problem** and which uses the latest non-minimized code of free jqGrid. You can use RawGit for example (see [the wiki](https://github.com/free-jqgrid/jqGrid/wiki/Access-free-jqGrid-from-different-CDNs#access-githib-code-from-rawgit)).

Best regards
Oleg

**Comment by AuthorProxy** [comment]
1. I have not any problem with performance, so it's never was a problem.
2. No all lodash funcs use something more than just incapsulation of vanilla js funcs.
3. It's not a question about performance, but thanks you for advice.
4. Ok, I will prepare demo for you later.

**Comment by OlegKi** [comment]
Hi!

Please **don't modify previous posted comment if you includes an important new information**. I found out accidentally that you included the demo in your previous post. I get no email notifications about the changes and the changes in GitHub (https://github.com/notifications) don't shows such changes too.

After I read the code of the demo it was clear the reason of the problem. You used
````JavaScript
function unformatObject(entry, el, td) {
    var elData = $(td).find('span').data('id');
    return elData === 0 ? 0 : elData || null;
}
```
at the unformatter and it returns **numeric** 0. On the other side jqGrid suppose that it's string. If you would add for example conversion to string in returned results (`return String(oldNumericResults)`) then the problem will be not exist.

Nevertheless the problem which you reported is common in my opinion and other users could have it. So I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/b34aec9696bd2962f236dfc5a8860d4095ba06b3) which solves the problem. You need refresh the code of free jqGrid which you use.

**Comment by AuthorProxy** [comment]
Yea it was not critical, but I agree that this can confuse somebody. So next time they don't need to debug to fix the problem.
