### ISSUE TITLE
Custom action 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#473]
It looks like the latest version, custom action  does not work.
Link http://www.ok-soft-gmbh.com/jqGrid/OK/CustomActionButton1.htm

**Comment by antoineluong** [comment]
What exactly does not work?
Version 4.15.5 seems functional to me: https://jsfiddle.net/s5qc2Lh6/

**Comment by davgino** [comment]
Function isDisplayButtons which  show custom button, not work.

**Comment by antoineluong** [comment]
The first parameter passed to the isDisplayButtons callback changed with 13c3931c05198f621dda8d28fb640ed3aaf0cad0.
Using rowData instead of options.rowData fixes the issue: https://jsfiddle.net/et324ywq/
