### ISSUE TITLE
Using Datepicker from Toolbar search doesn't work as I expected

### ISSUE THREAD

**Issue by kswager-o3** [free-jqgrid/jqGrid#484]
It's easy to replicate this issue using [this page](http://www.ok-soft-gmbh.com/jqGrid/OK/customFilterOperartion.htm). Apologies, I didn't save the link to the page that referenced it but it was a sample solution to another toolbar search issue probably from Stackoverflow.

Click in the date field on the search toolbar and change the date to any other date in the current month. The datepicker popup closes and changes the selected search date to be the selected value. The current criteria of == indicate that the filter should only display data matching that date, but nothing changes.

Click on the == to open that popup menu and then just click on the selected value of == and now the display is updated to show no records, which is what I expected.

I did find a [page](http://crgee.blogspot.com/2015/11/jqgrid-date-picker-for-column-filtering.html) that indicated a fix for the issue, but it didn't work for me.

As an additional FYI that should maybe be documented somewhere, trying to use the Datepicker in a search toolbar on a frozen column doesn't work; it ends up creating two input fields for the same column both with the same ID.

Thanks.

**Comment by pribeirojtm** [comment]
Hello @kswager-o3 

I'm not a maintainer of this project, although I use it and I'm giving a try to help you.

**Firstly** you're showing an old example that uses an "old" version of free jqgrid:
```
/**
 * @license jqGrid 4.13.6-pre - free jqGrid: https://github.com/free-jqgrid/jqGrid
 * Copyright (c) 2008-2014, Tony Tomov, tony@trirand.com
 * Copyright (c) 2014-2016, Oleg Kiriljuk, oleg.kiriljuk@ok-soft-gmbh.com
 * Dual licensed under the MIT and GPL licenses
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl-2.0.html
 * Date: 2016-11-05
 */
```
Please try , if possible to use the latest version published.

**Secondly**. I have similar situations in the projects I work. The second link you used it is from an old and the original library that originated the development of this one (free jqgrid is a fork from jqgrid and followed a different path).

I suggest you to have an initDatepicker function and inside of it, having something that detects the "changeDate" which can triggerToolbar() search. Example:
```

var initDatepicker = function (elem, options) {
    var self = this,
        $elem = $(elem),
        $gBox = $(this).closest(".ui-jqgrid"),
        onChangeDate = function () {
            //code below commented to do not autosubmit on select...
            if (options.mode === "filter") {
                setTimeout(function () {
                    self.triggerToolbar();
                }, 0);//or 10
            } else {
                $elem.change();
            }
        };

    if ($gBox.hasClass("ui-jqgrid-bootstrap")) { /* ->>> bootstrap used in my case, but the situation is similar (logic) with jqueryui */
        // uses bootstrap-datepicker.js
        $elem.datepicker({
            format: "yyyy-mm-dd",
            //autoSize: true,
            calendarWeeks: true,
            clearBtn: true,
            todayBtn: false,
            todayHighlight: true,
            autoclose: true,
            showWeek: true
        });
        // fix position of the datepicker
        $elem.on("show", function () {
            var $datepicker = $("body>.datepicker-dropdown");
            if ($gBox.length > 0 && $datepicker.length > 0) {
                $datepicker.css("top",
                    this.getBoundingClientRect().top +
                    window.pageYOffset +
                    $(this).outerHeight());
            }
        });
        $elem.on("changeDate", onChangeDate);//executes the function above when date changes
    } else {
        // use jQuery UI datepicker (not used)
        $elem.datepicker({
            dateFormat: "dd-yy-M",
            autoSize: true,
            changeYear: true,
            changeMonth: true,
            showButtonPanel: true,
            showWeek: true,
            onSelect: onChangeDate
        });
    }
};

//ADD CUSTOM TEMPLATES for colModel use
$.extend(true, $.jgrid.cmTemplate,
    {
        customDateTemplate: customDateTemplate,
    });


//TO USE customDateTemplate in the colModel (column definition) "template":"customDateTemplate"
var customDateTemplate = {
    align: "center",
    width: 80,
    fixed: true,
    /*, sorttype: "date", datefmt: "Y-m-d", */ /*datefmt: Governs format of sorttype:date (when datetype is set to local) and editrules {date:true} fields.*/
    /*editable: true, editrules: {date: true}, editoptions: {dataInit: initDatepicker},*/
    searchoptions: {
        sopt: ["bw", "cn", "eq", "ne", "lt", "le", "gt", "ge", 'nu', 'nn', 'in', 'ni'],
        attr: {maxlength: 10, autocomplete: 'off'}, // for searching toolbar
        maxlength: 10,                     // for searching dialog
        clearSearch: false,
        dataInit: initDatepicker
    },
    sorttype: 'date', /*applicable only when datatype is local*/
    //stype: "text",//
};

```
Hope it can help you.

**Comment by kswager-o3** [comment]
Thank you @pribeirojtm for your reply.

Yes, I knew that the sample page I references was not the latest version, but I do have the latest version installed and since that page already existed on the same site as the other samples and exhibited the same exact issue, I thought it would be simpler to reference it.

I'll try and find some time later today to work thru your suggestions and see if anything changes.

Again, thanks for your reply and assistance.

**Comment by kswager-o3** [comment]
Many thanks @pribeirojtm. With your help we were able to resolve our issue.
