### ISSUE TITLE
TypeError: cm is undefined

### ISSUE THREAD

**Issue by himiklab** [free-jqgrid/jqGrid#49]
После коммита `introduce new jqGrid parameter iColByName` при попытки вызова окна расширенного поиска вываливается ошибка `TypeError: cm is undefined` в строке 6965 файла jquery.jqgrid.src.js (по состоянию файла на этот коммит). Ошибка возникает только при попытке вызова этого окна после изменения состояния грида через `setGridParam`, изменяемые параметры `search`, `sortname`, `sortorder`.

**Comment by OlegKi** [comment]
Could you find the line in **the current version of `jquery.jqgrid.src.js`**. You can download the code now or to use URLs `https://rawgit.com/free-jqgrid/jqGrid/master/css/ui.jqgrid.css`, `https://rawgit.com/free-jqgrid/jqGrid/master/js/i18n/grid.locale-en.js` (it's optional) and `https://rawgit.com/free-jqgrid/jqGrid/master/js/jquery.jqgrid.src.js`.

Any bug could be easy fixed if you provide the demo which reproduces it. If you can provide the demo it will speed up the fixing in multiple times.

**Comment by himiklab** [comment]
Line is 7018 in `jquery.jqgrid.src.js`.

**Comment by OlegKi** [comment]
Thank you very much for the bug report! I could reproduced the problem and posted the bug fix (see [here](https://github.com/free-jqgrid/jqGrid/commit/f022ce49fd9901a5a7e73e9936084ba76fc1673e)). Please reload the code of free jqGrid and confirm that the problem is solved now.

**Comment by himiklab** [comment]
Yes, problem is solved now. Thank you!
