### ISSUE TITLE
How to add new sopt to source code

### ISSUE THREAD

**Issue by MSIH** [free-jqgrid/jqGrid#53]
I have created a customSortOperations that I want to add into the jqGrid source. I am a notice and am not sure where to add into the source code. I see ferences to search in grid.filter.js and jquery.searchfilter.js .

Here is my custom sort operation

       customSortOperations: {
        // the properties of customSortOperations defines new operations
        // used in postData.filters.rules items as op peroperty
        sIn: {
            operand: "sIN", // will be displayed in searching Toolbar for example
            text: "String IN", // will be shown in Searching Dialog or operation menu in searching toolbar
            title: "Type multiple values separated by space to search for one from the specified values",
            filter: function (options) {

                var fieldData = options.item[options.cmName];
                var words = options.searchValue.split(" ");                
                
                $.each(words, function () {
                    var searchResults = fieldData.toLowerCase().indexOf(this.toLowerCase())
                    //alert(searchResults);
                    if (searchResults < 0) {
                        fieldData = "";                        
                    }
                });

                return fieldData;
            }
        }
    }

**Comment by OlegKi** [comment]
I'm not sure what you mean with "to add into the jqGrid source". `customSortOperations` is jqGrid **option**. So you need to add the option to the grid which you create and not to modify the code of some jqGrid module. 

If you want to use `sIn` searching operation in *multiple grids* you can add `customSortOperations` to the list of standard jqGrid options. So you can execute
```JavaScript
$.extend(true, $.jgrid.defaults, {
    customSortOperations: {
        sIn: {
            ...
        }
    }
});
```
It's important that the option just defines new operation, but the operation will be not used automatically in every grid column. To use it in come column you need add the operation to the list of searching operation used for the column:
```JavaScript
searchoptions: { sopt: ["nIn", "eq", "ne", ...] }
```
You can examine the code of [the demo](http://stackoverflow.com/a/29415927/315935) created for [the answer](http://stackoverflow.com/a/29415927/315935), [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/DatetimeSearch1.htm) from [the answer](http://stackoverflow.com/a/29676941/315935), the demos from [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/Custom-filtering-searching-Operation) and so on.

**Comment by MSIH** [comment]
Thank you for the quick response.

**Comment by OlegKi** [comment]
You are welcome! Do you have success now? Could you close the issue when the problem will be solved?

**Comment by MSIH** [comment]
Yes.  I would like to have this search option available for all of my grids in the future. To accomplish this are you suggesting that I create a javascript file and link it to all the pages. The contents of the javascript file would be:

     $.extend(true, $.jgrid.defaults, {
    customSortOperations: {
        sIn: {
            ...
        }
      }
    });

**Comment by OlegKi** [comment]
Yes, but you need still one more step to make the operations available. You need place the operation in `sopt` for the columns which need have the operation (see my previous comment and the referenced demos).

I still not sure what you mean under searching: filter toolbar or searching dialog. If you want to add the new operation in searching dialog for **all columns**, which have no `sopt` specified then you can execute additionally (in the JavaScript file which you includes to all the pages):
```JavaScript
$.extend(true, $.jgrid, {
    filter: {
        numopts: ["nIn", "eq", "ne", "lt", "le", "gt", "ge", "nu", "nn", "in", "ni"],
        stropts: ["nIn", "eq", "ne", "bw", "bn", "ew", "en", "cn", "nc", "nu", "nn", "in", "ni"]
    }
});
```
The code looks like default settings, but the new operation `"nIn"` exist as the first in the lists of available operations.

**Comment by MSIH** [comment]
thank you
