### ISSUE TITLE
Allow easily resize last column in there is no horizontal scrollbar

### ISSUE THREAD

**Issue by kobruleht** [free-jqgrid/jqGrid#55]
It should be possible to resize last column in free jqgrid if there is no horizontal scrollbar.
Currently it allows to resize only by few pixels.
To make column wider, resize shoudl repeated lot of times. Each resize can resize last column by few pixels only.

http://stackoverflow.com/questions/10780664/resize-last-column-in-jqgrid contains Ilya Kr. solution for this. Maybe similar code should added.

**Comment by OlegKi** [comment]
I implemented the feature in free jqGrid. See [the commit](https://github.com/free-jqgrid/jqGrid/commit/7152beface9fef824879702a83da9625aa04d507).

**Comment by OlegKi** [comment]
@kobruleht Have you seen the last changes which I published 10 days ago? It fixed the problem. So I close the issue. If you will do find some problems you can reopen it.
