### ISSUE TITLE
Using Filters in URL

### ISSUE THREAD

**Issue by lalato** [free-jqgrid/jqGrid#57]
Hi Oleg,
Thanks for continuing the free version of jqgrid.  I truly appreciate your efforts.

I was wondering if you had any suggestions for me regarding this issue.  I want to enter a filter value in the URL and have that filter value populate in the Filter appropriate column in the grid.  Preferably, I would want the filter applied after load.

For example... I would enter a url like this  http://www.mysite.com/mygrid/index.html?RULESET=WFTDA

This would load the grid as normal, and then after load, it would copy the value "WFTDA" into the Ruleset filter box at the top of the column.  It would then filter the list for this value.  I don't want to send the filter as part of the WHERE clause in SQL.  I just want to load the grid and filter after load.

Is this possible?

**Comment by OlegKi** [comment]
Hi!

It's possible in general. You need just get the parameters from the URL, set `postData` parameter of jqGrid and to set `search: true` parameter of jqGrid. The format of `postData` properties depend on the searching possibility which you integrated in the server.

For example you can open the URL http://www.ok-soft-gmbh.com/jqGrid/OK/UrlWithParameters.htm?param1=value1&param2=value2

You can get HTTP trace using developer tools of IE/Chrome/Firebug. You will see that jqGrid will make request to get the data from 

http://www.ok-soft-gmbh.com/jqGrid/OK/DummyUrl?param1=value1&param2=value2&_search=false&nd=1431446888358&rows=10&page=1&sidx=invdate&sord=desc

The parameters part of the URL was parsed and used to build the parameters send to the server to get the grid data. The corresponding code fragment is
```JavaScript
var parameters = window.location.search.substr(1).split("&"), i, p, myOptions = {};
for (i = 0; i < parameters.length; i++) {
    p = parameters[i].split("=");
    if (p.length === 2) {
        myOptions[p[0]] = p[1];
    }
}
....
$grid.jqGrid({
    datatype: "json",
    url: "DummyUrl",
    postData: myOptions,
    ...
});
```
Best regards
Oleg

**Comment by OlegKi** [comment]
Please close the issue if the problem is solved now. Please send additional information if the problem is still not solved.

**Comment by lalato** [comment]
Thanks.  I haven't implemented it yet, but I will give it a go this week.

**Comment by OlegKi** [comment]
Thanks for the feedback!

**Comment by lalato** [comment]
Just wanted to say that your answer [here on stackoverflow](http://stackoverflow.com/questions/7688385/triggering-client-side-filtering-at-load-time-in-a-jqgrid) is proving very useful.  Thanks for offering so much of your time and knowledge.  Unfortunately, I don't have enough reputation to upvote.

**Comment by lalato** [comment]
Ultimately used this function to grab the parameters from the URL, which I got from [stackoverflow](http://stackoverflow.com/a/3855394/3225555)...

```javascript
var qs = (function(a) {
    if (a == "") return {};
    var b = {};
    for (var i = 0; i < a.length; ++i)
    {
        var p=a[i].split('=', 2);
        if (p.length == 1)
            b[p[0]] = "";
        else
            b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
    }
    return b;
})(window.location.search.substr(1).split('&'));
```
I combined that with this code which you provided in the [stackoverflow thread](http://stackoverflow.com/a/7689042/3225555) I posted earlier.

```javascript
loadComplete: function () {
    var gridDOM = this; // save $("#list")[0] in a variable
    if ($(this).jqGrid('getGridParam', 'datatype') === 'json') {
        // the first load from the server
        setTimeout(function () {
            $("#gs_PID").val('AA');
            gridDOM.triggerToolbar();
        }, 100);
    }
}
```

Thanks for pointing me in the right direction!

**Comment by OlegKi** [comment]
You are welcome!

I consider to provide the feature to make **local** sort and filtering of data after loading  and before the data will be displayed in jqGrid. The feature could be practical in case of usage `loadonce: true` and the source of JSON/XML data which can't be changed (loading from public source for example). The feature will be not part of free jqGrid 4.9 which will be published very soon, but I hope that I will include it in the version 4.10.
