### ISSUE TITLE
jqPivot column grouping is not working properly

### ISSUE THREAD

**Issue by gelo32k** [free-jqgrid/jqGrid#58]
I wrote about it here: http://stackoverflow.com/questions/30167229/jqpivot-is-grouping-column-headers-that-do-not-belong-to-the-group

**Comment by OlegKi** [comment]
Thank you for the bug report. I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/306bd56cccd140f9bd1fda313e9b5417999f5bac) which resolves the problem.

**Comment by gelo32k** [comment]
I updated the links in my JSFiddle, but it seems that nothing happened.

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/11883895/7627458/2e37473c-fa4a-11e4-89f9-baf5a241a9ee.PNG)

**Comment by OlegKi** [comment]
It would be very helpful if you would invest one more minute of your time and to describe the problems which reports more clear. There was a bug in *column grouping* in free jqGrid *after* publishing of jqGrid 4.8. I fixed the bug. Now the current version of free jqGrid on GitHub, the free jqGrid 4.8 and free jqGrid 4.7 display **identical results**. Compare [jqGrid 4.7 demo](http://www.ok-soft-gmbh.com/jqGrid/OK/pivotGrouping47.htm) with [current free jqGrid](http://www.ok-soft-gmbh.com/jqGrid/OK/pivotGrouping.htm).

One common remark. I don't used jqPivot before. No my customers had the corresponding requirements. So I invested my time for analyzing the existing code of jqGrid only for you. So it would be good it you would describe the problems more clear and detailed in your future posts.

I see that the existing code of jqPivot works incorrectly in the case if `yDimension` have more as one element. It's *an old bug* in the code of jqGrid 4.7. The bug exists somewhere in the recursive function `list` (see [here](https://github.com/free-jqgrid/jqGrid/blob/master/js/grid.pivot.js#L321-L420)). I will examine and probably rewrite the function later.

Best regards
Oleg

**Comment by OlegKi** [comment]
I commeted [more fixes](https://github.com/free-jqgrid/jqGrid/commit/613daeb026bbce078b53ca72e212495741bfdaf2) in jsPivot module, which should fix the old bugs which come from jqGrid 4.7. Now your JSFiddle demo https://jsfiddle.net/4en1b68c/5/ produce correct results. I hope that the code works correct for more complex input data too. Moreover you can remove the last block with hiding columns having `cmi.label.length == 3 || cmi.label.length == 0 || cmi.label == '\&nbsp\;'`. The columns don't exist more in the grid.

**Comment by gelo32k** [comment]
Sorry if I wasn't able to help much but Thank you very much :)
