### ISSUE TITLE
Editrules caption 

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#61]
When use editrules:{required:true} for validation , caption for info_dialog caption = undefined.
Image = http://my.jetscreenshot.com/demo/20150516-1omr-7kb

**Comment by OlegKi** [comment]
Than you very much for the bug report. [The last committed changes](https://github.com/free-jqgrid/jqGrid/commit/31c4a531472ab6afda7b88ef3153ca9b1b0fce25) fix the bug.
