### ISSUE TITLE
pivot table header group columns are not correct

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#62]
I found that header group is not right.
The 2011 should include 12 and 2011.
But the top level column did not include them.

I tried 4.8 and 4.9 beta. But the result is same. 
Could you give me a tips to fix that?

Sample:
http://codepen.io/anon/pen/jPrLPJ?editors=101

**Comment by OlegKi** [comment]
Thank you for the bug report. I made [one small fix](https://github.com/free-jqgrid/jqGrid/commit/5cd1f6b45833d182b758945d768e93f30cee8ad6). Please retry with the latest sources from GitHub.

**Comment by mrjumpy** [comment]
wow!! 
it's works. Thank U!

**Comment by OlegKi** [comment]
You are welcome! I close the issue in the case.
