### ISSUE TITLE
Multiselect width

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#70]
I think the last change width of multiselect is wrong. Pls. see http://my.jetscreenshot.com/demo/20150527-jwg6-2kb

**Comment by OlegKi** [comment]
Please could you describe the problem more exactly. First of all which web browser you used in the tests? Which zoom you used? I used to use the latest version of Google Chrome and IE10 in my main tests.

**Comment by davgino** [comment]
I use Mozilla Firefox , but in Google Chrome is ok.
http://my.jetscreenshot.com/demo/20150527-nzz2-40kb

**Comment by OlegKi** [comment]
I could reproduce the problem in Firefox in case of usage zoom factor which is not divisible to 100% (I mean not 100%, 200%, 400%, ...). I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/aa239a2566f679283a8101c3ed2db72928d2a46c) which should fix the problem.
