### ISSUE TITLE
PivotGrid - Missed total label on footer

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#72]
Take a look:
![image](https://cloud.githubusercontent.com/assets/8980713/7877855/b29d6816-0612-11e5-9f25-1fbe88eae57b.png)
The red block one should have Total:
I think that should have a label options to custom strings.
Thank you.

**Comment by OlegKi** [comment]
Thanks for the suggestion! I am rewriting now **full new code** of `jqPivot`. The most parts of new code is already working. I try to hold mostly the close names of options, but I think that some changes like youth are required. Additionally the new code can sort the input data by y or x dimensions. The usage of unsorted data follows to wrong results and the correct grouping of column headers is not possible. I will inform you after I'm ready with rewriting.

**Comment by mrjumpy** [comment]
OK.
Let me know If any suggestions are not suitable for pivotGrid.

**Comment by mrjumpy** [comment]
Considering you prepare to rewriting pivotGrid,
I think that I should inform you the other relatively issues about this one.

I updated the picture of the total's label:
The Blue one also should have the options to render its text. 

![image](https://cloud.githubusercontent.com/assets/8980713/7879303/ffd99442-0621-11e5-81a8-fd5565d0957c.png)

**Comment by OlegKi** [comment]
Sorry, but I don't understand the requirement. When should be set the background color?

I'm not sure what you need to implement, but in general `xDimension` items build the first columns of `colModel` and `xDimension` can contains any `colModel` properties. One can define `cellattr` callback in  `xDimension` to set class or style of the cells of the column based on content of the column or any other columns in the row? See [the answer](http://stackoverflow.com/a/6048865/315935) as an example.

By the way I have already new working jqPivot. I am implementing only the totals by `yDimension` and the main aggregation totals as the last columns of the grid. I added some new options. Moreover I want rename the `rowTotals`, `rowTotalsText` and `rowTotalsTitle` inside of `yDimension` to `totals`, `totalText` and `totalHeader`. The prefix  `row` seems me unneeded and misunderstandable. The name "Title" will be used for tooltips too. The "Header" seems me less misunderstandable as all other names.

I want to rename `rowTotals` to `footerTotals` but to test whether the old name `rowTotals` is defined. If `footerTotals` is undefined, but the old `rowTotals` is defined then I will set `footerTotals` to the value of `rowTotals`. It will allow to use new names, but to hold some backward compatibility.

I want to rename `rowTotalsText` to `totalText` and to add `totalHeader`. It can specify the text and the header of the last columns of the grid.

I implemented already `totalText` property in `xDimension`. So one can use `totalText: "Total:"` in the first item of `xDimension` to add the text `"Total:"` at the beginning of the footer row.

I implemented additionally sorting of input data by `xDimension` or/and `yDimension`. The sorting by `yDimension` is required for good building of column headers. There are exist options `sortByX` and `sortByY` which can be set to `false` to prevent sorting of data.

The old version of jqPivot used always `$.trim` before building of unique xValues and yValues. the option is OK for the most scenarios, but I includes `trimByCollect` option which can be set to `false` to prevent trimming.

Please inform me if you have some other ideas about new options which could be helpful.

P.S. I will provide new version of jqPivot very soon.

**Comment by mrjumpy** [comment]
Sorry for my abstract description.
Here is I want it:
![image](https://cloud.githubusercontent.com/assets/8980713/7880493/859946cc-062c-11e5-9eba-15b16fb3dcb6.png)
Take a look at image.
Enable to put string like `Subtotals:` and `Total:`  in the cell.

**Comment by OlegKi** [comment]
OK! I understand you now, but it seems to be pure grouping problem. You can define the property `summaryType` in the `ProductName` column (in `xDimension`) as the following:
````JavaScript
summaryType: function () { return "Subtotals:"; }
````
It should solve the problem because it informs jqGrid grouping how to fill the summary for the column.

**Comment by mrjumpy** [comment]
Yes, it's solve the problem.
Thank you.

**Comment by OlegKi** [comment]
OK I'll published preliminary version without totals of yDimension. All is not yet finished.

**Comment by OlegKi** [comment]
I forget to include the link to the demo which demonstrates some options: [here](http://www.ok-soft-gmbh.com/jqGrid/OK/pivotGroupingMultipleAgregations5.htm)

**Comment by mrjumpy** [comment]
Yes!!,this is what exactly I want.
Thank you Oleg.
I'll close this issue.
