### ISSUE TITLE
PivotGrid - rowTotalsText

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#73]
In the pivotOpt, we use `rowTotalsText` to named the final total.
There is a problem that we can't assigned `function` to `pivotOpt's rowTotalsText` just like we use it like in the `yDimension's rowTotalsText`

http://codepen.io/mrjumpy/pen/qdRajE?editors=101

It should be there to satisfied the custom total string feature.
What do you think?

**Comment by OlegKi** [comment]
Sure, I will implement the feature.

**Comment by OlegKi** [comment]
The name of new option is `totalText`. One can use either template form like `totalText: "Grand Total {0} {1}"` or the callback form. Try for example to use the following option
```JavaScript
totalText: function (aggr, iAggr) {
    return "<span style='font-style: italic'>Grand Total " + iAggr + ": " +
        aggr.aggregator + " " + aggr.member + "</span>";
}
```
It will display the last "row total" (the total over all the data of the row) like on the following picture
![untitled](https://cloud.githubusercontent.com/assets/249117/7917554/88b0ad8a-088b-11e5-9b14-07f1edd29b0b.png)

**Comment by OlegKi** [comment]
See the next demo http://codepen.io/anon/pen/jPyoEX with more modifications which demonstrates the features.

**Comment by mrjumpy** [comment]
In this new version,
If I change options to below: 
1: change `rowTotals` to false,
2. remove `totalText`
3. remove `totalHeader`

it will be some errors occur.

**Comment by OlegKi** [comment]
Thank you . Please try again after the fix.

**Comment by mrjumpy** [comment]
OK!

If I'm using 2 yDimensions instead of 1 yDimensions.
Problem still there.
Take a look:
http://codepen.io/mrjumpy/pen/rVyVQL?editors=001

**Comment by OlegKi** [comment]
Thank you! It was almost the same but, but in another function. It's fixed now too.

**Comment by mrjumpy** [comment]
OK!
It's works now. Thank you.

**Comment by OlegKi** [comment]
Please be carefully. **I changed the name of some options and to changed the options used in the callback parameters.** Please read [the new wiki article](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9) which I published today. It describes all (I hope) options of jqPivot.

The wiki article (like all other) is opened for writing. So you can change the text or you can post new wiki article. I will start with the documentation site after publishing free jqGrid 4.9 in the next days.
