### ISSUE TITLE
MouseUp event being stopped

### ISSUE THREAD

**Issue by jmcpeak** [free-jqgrid/jqGrid#76]
So around line 4931 of master/js/jquery.jqgrid.src.js:

```javascript
$(document).bind( "mouseup.jqGrid" + ts.p.id, function () {
	if(grid.resizing !== false) {
		grid.dragEnd( true );
		return false;
	}
	return true;
});
```

If grid.resizing is undefined (which it is almost always is) the goofy logic stops the mouse event by returning false.

This is the fix:
```javascript
	if(grid.resizing) {
```

**Comment by OlegKi** [comment]
Thank you for the bug report! I agree with you. Moreover I made more changes in the code which I [commit just now](https://github.com/free-jqgrid/jqGrid/commit/fc6c2c3bbc442edb3c179c63215da190f3844aad). After the changes the code `$(document).bind("mouseup.jqGrid" + ts.p.id,...)` will be executed **inside of `dragStart` only**. I execute the corresponding `unbind` inside of `dragEnd` which will be called in `mouseup`. In other words there are no permanent `mouseup` binding more. The handle will be registered on starting of column resizing only (on `mousedown`) and will be removed on `mouseup`.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who report a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
