### ISSUE TITLE
HTMLElement is undefined in IE8

### ISSUE THREAD

**Issue by pbacka** [free-jqgrid/jqGrid#77]
In Internet Explorer 8 condition

```
if ($p instanceof $ || $p.length > 0) {
	p = $p[0];
} else if (("HTMLElement" in window && $p instanceof HTMLElement) || ("Element" in window && $p instanceof Element)) {
	p = $p;
	$p = $(p);
} else {
	return $(); // return empty jQuery object
}
```
in getGridComponent causes error: HTMLElement is undefined.

**Comment by OlegKi** [comment]
Thank you for the bug report. I committed [the corresponding fix](https://github.com/free-jqgrid/jqGrid/commit/858349a9b36dfa493248cac9fb71fbe83127b86f) just now. Please reload free jqGrid which you use from [GitHub](https://github.com/free-jqgrid/jqGrid).

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
