### ISSUE TITLE
PivotGrid - missed average aggregate 

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#78]
We have `sum` and `count` aggregate already. 
But I thought that we should provide `average` aggregate  also .

**Comment by OlegKi** [comment]
You can use `aggregator: "avg"`. I documented in [the part](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9#usage-aggregator-as-callback-functions) of wiki that "sum", `"count"`, `"avg"`, `"min"` and `"max"` can be used. The name `"avg"` will be already used in many places of old jqGrid for grouping summary and by `getCol` method which will be used for filling the footer too. Moreover I described in the same [the part](https://github.com/free-jqgrid/jqGrid/wiki/jqPivot-in-version-4.9#usage-aggregator-as-callback-functions) of wiki article how to implement **custom** aggregate too. I hope that one have maximal flexibility in the way.

**Comment by OlegKi** [comment]
Please examine all opened issues which you posted and close the issues which are solved already.
