### ISSUE TITLE
clearGridData not empty data

### ISSUE THREAD

**Issue by ignrac** [free-jqgrid/jqGrid#84]
free-jqgrid-4.9.0rc1
This grid definition:

$("#grid_exp").jqGrid({
    datatype: "local",
    colNames:['exp','items'],
    colModel:[
        {name:'fi_id',index:'fi_id',width:30, key:true},
        {name:'fi_items',index:'fi_items',width:40 }
    ],
    rowNum: 5000,
    gridview: true,
    loadonce:true,
    localReader :{id:'fi_id',repeatitems: true},
....
});

I set the data with an json array in ajax call, format:
[{"cell":["1602.JP","12"]},{"cell":["1505.JP","8"]}]}

Executing:
var grid = $("#grid_exp");
grid.clearGridData();
grid.setGridParam({
        datatype:'local',
        data: json_array});
grid.trigger('reloadGrid');

The grid show only the data of first call.
I modified clearGridData function, adding (jquery.jqgrid.src.js file):
+ 6130 
clearArray(p.data);
clearArray(p.lastSelectedData);

Now, the grid show the data correct.

**Comment by OlegKi** [comment]
Thank you for the bug report! [The commit](https://github.com/free-jqgrid/jqGrid/commit/584ef68b1dbbb22625b0847c1832049469fb5fc2) fixes the bug.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
