### ISSUE TITLE
editGridRow only add last col for same colpos

### ISSUE THREAD

**Issue by ignrac** [free-jqgrid/jqGrid#85]
free-jqgrid-4.9.0rc1
This grid definition:

$("#grid_con").jqGrid({
    datatype: "local",
    colNames:['con','Name', 'Short','ACR'],
    colModel:[
        {name:'con_id',index:'con_id',hidden:30, key:true},
        {name:'con_name',index:'con_name',width:140,formoptions:{label:'Full Name',rowpos:1,colpos:1}},
        {name:'con_short',index:'con_short',width:90,formoptions:{rowpos:2,colpos:1}},
        {name:'con_acronim',index:'con_acronim',width:40,formoptions:{label:'Short Name / ACR',rowpos:2,colpos:1}}
    ],
    rowNum: 5000,
    gridview: true,
    loadonce:true,
....
});

editGridRow call, HTML result:
```html
<tr data-rowpos="1" class="FormData" id="tr_con_name"><td class="CaptionTD">Full Name</td><td class="DataTD"><input type="text" size="36" maxlength="50" tabindex="1" id="con_name" name="con_name" role="textbox" class="FormElement ui-widget-content ui-corner-all"></td></tr>
<tr data-rowpos="2" class="FormData" id="tr_co_short"><td class="CaptionTD">Short Name / ACR</td><td class="DataTD"><input type="text" size="3" maxlength="2" tabindex="2" id="co_acronim" name="co_acronim" role="textbox" class="FormElement ui-widget-content ui-corner-all"></td></tr>
```
Not show 'con_short' input

I modified editGridRow function (jquery.jqgrid.src.js file):
10452 - $data.html(frmopt.elmprefix).append(elc).append(frmopt.elmsuffix);
10452 + $data.append(frmopt.elmprefix).append(elc).append(frmopt.elmsuffix);

Now, HTML result:
```html
<tr data-rowpos="1" class="FormData" id="tr_con_name"><td class="CaptionTD">Full Name</td><td class="DataTD"><input type="text" size="36" maxlength="50" tabindex="1" id="con_name" name="con_name" role="textbox" class="FormElement ui-widget-content ui-corner-all"></td></tr>
<tr data-rowpos="2" class="FormData" id="tr_co_short"><td class="CaptionTD">Short Name / ACR</td><td class="DataTD"><input type="text" size="15" maxlength="16" tabindex="2" id="co_short" name="co_short" role="textbox" class="FormElement ui-widget-content ui-corner-all"><input type="text" size="3" maxlength="2" tabindex="3" id="co_acronim" name="co_acronim" role="textbox" class="FormElement ui-widget-content ui-corner-all"></td></tr>
```
Showing 'con_short' and 'co_acronim' in same DataTD

**Comment by OlegKi** [comment]
Thank you for the bug report! [The commit](https://github.com/free-jqgrid/jqGrid/commit/bbccbe84522b7a4cec1a2a96e493081b6c30b1fd) includes the fix, which you suggested and it makes some other minor improvements.

**Comment by OlegKi** [comment]
I close the issue. You can reopen it again if you find that the problem still not solved. I prefer that the person who reports a problem confirms that the fix work and he/she close the issue. Please think about closing the issues which you post the future. Best wishes!
