### ISSUE TITLE
Multiselect and autocomplete UI plugin

### ISSUE THREAD

**Issue by davgino** [free-jqgrid/jqGrid#86]
I have a grid with multiselect:true option and inlineNav and a field with automplete UI plugin.
When i add a row in grid and load data form server for field with autocomplete and i use up arrow or down arrow for select item , new_row of grid disapear.

**Comment by OlegKi** [comment]
Sorry, but I'm not sure that I correctly understand the problem. **Could you describe it more detailed?** Where you use jQuery UI Automplete? In some field of inline editing? What will be done in your test case? Do you click on "+" (Add new row) and you use *immediately* the jQuery UI Automplete in the field? Or you saves first the new added row and then continue add/editing and you don't see new added data in the jQuery UI Automplete which you use *later*? How exactly you load the data from the server for Autocomplete? Do you set some additional HTTP headers which responsible for caching? Or you use at least `cache: false` option? I personally set `Cache-Control: private, max-age=0` in such scenario to be sure that one makes new Ajax request to the server every time.

**Comment by davgino** [comment]
Yes, i use in some field of inline editing. I use click(+Add new row).  Problem not is at Jquery UI autocomplete , data is loaded corect form server , but when i use arrow up or arrow down for select item from list loaded with UI autocomplete, new_row dispear .

**Comment by OlegKi** [comment]
Sorry, but I still can't follow you. **Could you describe the full test case or better to provide small demo which reproduces the problem?**

It's clear from the last post that you click on "+" (Add new row) of the `inlineNav`. Some column (`explicop`) have `editoptions.dataInit` which calls `autocomplete`. It is still unclear what is the problem. You wrote "new_row dispear". What you mean? You still didn't saved the new row. Why some data from the new line (which is still not saved on the server) should appears in the Autocomplete menu?

**Comment by davgino** [comment]
Demo : http://jsfiddle.net/9ezy09ep/37/
Problem is when i use bindkey.

**Comment by OlegKi** [comment]
Thank you for the demo! The method `bindkey` should be changed of cause to skip key navigation in case of usage inline editing. I posted [the fix](https://github.com/free-jqgrid/jqGrid/commit/d8a62f68610b0139d948ebaee94bbd03fc05c6d5) just now. Your demo works now.
