### ISSUE TITLE
Setting filterToolbar options in grid complete

### ISSUE THREAD

**Issue by springbok** [free-jqgrid/jqGrid#87]
Hi Oleg,

I'm trying to set the afterSearch event in the grid complete event but this does not seem to work due to the following code:

var $t = this, grid = $t.grid, $self = $($t), p = $t.p, bindEv = jgrid.bindEv, infoDialog = jgrid.info_dialog;
if (this.ftoolbar) { return; }

When the grid complete event is called the this.ftoolbar is true meaning I can't set any custom options. Am I not able to set search options once the grid has been created, if this is the case where should I be setting these options?

**Comment by OlegKi** [comment]
Hi,

Sorry, but setting one callback (`afterSearch` for example) inside of another callback (`gridComplete`) is wrong in the most cases.

Mostly you should add `searching` option to jqGrid and set any callbacks or options of fillter Toolbar or any callbacks or options of the searching dialog *inside of* `searching` option.

For example
```JavaScript
$("#grid").jqGrid({
    colModel: ...
    data: ...
    ...
    searching: {
        // search dialog options:
        searchOnEnter: true, 
        closeOnEscape: true,
        multipleSearch: true,
        multipleGroup: true,
        // filter toolbar options:
        searchOperators: true,
        defaultSearch: "cn",
        afterSearch: function () {
            alert("in afterSearch");
        }
    }
});
```
In the way you can set the search options once the grid has been created. The options specified default options of searching used in the grid. You can read more about the style of setting the options in [the wiki article](https://github.com/free-jqgrid/jqGrid/wiki/New-style-of-usage-options-of-internal-methods).

If the above example don't help you, then you should describe the requirements more detailed and to post the code (or the demo) which you use currently.

**Comment by springbok** [comment]
Thank you for the explanation it's much appreciated, I'll adjust my code.
