### ISSUE TITLE
Inline edit - adding new row not selecting new row and not entering edit mode

### ISSUE THREAD

**Issue by Wooya** [free-jqgrid/jqGrid#88]
I've noticed when adding new row in inline edit mode that new row is not selected and not in edit mode.  Row just appears as empty. After investigation I think that line:
https://github.com/free-jqgrid/jqGrid/blob/master/js/jquery.jqgrid.src.js#L13358

should be before
https://github.com/free-jqgrid/jqGrid/blob/master/js/jquery.jqgrid.src.js#L13357

like that:
```javascript
o.rowID = p.idPrefix + o.rowID;
$self.jqGrid("addRowData", o.rowID, o.initdata, o.position);
```

When I exchanged those lines locally everything working fine.

**Comment by OlegKi** [comment]
Thank you for the bug report! I full agree with you. The bug come from jqGrid 4.7 (see [here](https://github.com/free-jqgrid/jqGrid/blob/v4.7.0/js/grid.inlinedit.js#L463-L464)) and it should be fixed of cause. I commited [the corresponding changes](https://github.com/free-jqgrid/jqGrid/commit/a51acecf4b9bb8532773429981bef910422c39a2) in the code. Thanks once more!
