### ISSUE TITLE
Column resizing (4.9.0-rc1)

### ISSUE THREAD

**Issue by petronellius** [free-jqgrid/jqGrid#90]
When resizing column by clicking the line between 2 columns, a big blue strip shows up.
In Developer Tools I can see a strange inline style (height: 865px;...) added to div with class .ui-grid-resize-mark. The same height has also div with class ui-grid-view that wraps whole grid.
![grid-resize-column](https://cloud.githubusercontent.com/assets/12825401/8076800/80f661ae-0f50-11e5-8863-41fc9eaee12e.png)

**Comment by OlegKi** [comment]
Thank you for the bug report, but you understand that one can't debug the picture. I need **the demo which can be used to reproduce the problem**. I suppose that there are some CSS settings in your project which you use and which will be applied to resizer div. Could you prepare the demo which reproduces the problem? I could analyse the problem and to fix CSS settings of resizer in the main code of free jqGrid.

**Comment by petronellius** [comment]
Your post leads me to check our css style and I found out that we forgot to upgrade ui.jqgrid.css when we upgraded from 4.8.0 to 4.9.0. Now it works great. Thanks;)

**Comment by OlegKi** [comment]
OK! I'm glad to hear that the problem is solved. You are welcome!
