### ISSUE TITLE
reloadGrid cause multiple requests to server

### ISSUE THREAD

**Issue by pbacka** [free-jqgrid/jqGrid#91]
These are my settings:

```
		grid.jqGrid({
			url: url,
			datatype: "json",
			mtype: "GET",
			pager: '#pager',
			colNames: gridReportConfiguration.colNames,
			colModel: gridReportConfiguration.colModel,
			jsonReader: gridReportConfiguration.jsonReader,
			shrinkToFit: true,
			forceFit: true,
			rowNum: 40,
			scroll: true,
			loadonce: true,
			gridview: true,
			altRows: true,
			altclass: 'altRow',
			viewrecords: true,
			recordtext: 'totalRecords' + ": {2}",
			sortname: "StartTime",
			sortorder: "desc"
		});
```
calling 
```
mygrid.jqGrid('setGridParam', { datatype: 'json', url: url }).trigger("reloadGrid") 
```
causes multiple server roundtrips with different page number:
1. rows=40&page=1&sidx=StartTime&sord=desc
2. rows=40&page=2&sidx=StartTime&sord=desc

It works when i leave the scrollbar on the top and then reload the grid. It does not work only when i move the scrollbar and then reload the grid.

**Comment by OlegKi** [comment]
It seems to me the old problem with the implementation of virtual scrolling in jqGrid. The reason of two requests is the `scroll: true` which you use. Try to use `scroll: 1` or just remove `scroll` at all.

**Comment by pbacka** [comment]
It did not solve the issue. I want to use virtual scrolling, but with `scroll: 1` i have still the same issue.

**Comment by OlegKi** [comment]
You write that you want to use virtual scrolling. It means that you want to use **the current implementation** of virtual scrolling. Free jqGrid have almost unchanged virtual scrolling like it was in jqGrid 4.7. I personally don't like it. It have many side effects, restrictions in usage other options of jqGrid and so on.

Loading of more as one pages it's one from the side effects. It's not the worst one. Either you should don't use the feature, like I recommend everybody in the most cases, or you should just accept the existing limitations, restrictions and side effects.
