### ISSUE TITLE
Pivot - font-size poblem

### ISSUE THREAD

**Issue by mrjumpy** [free-jqgrid/jqGrid#95]
DEMO:
http://codepen.io/mrjumpy/pen/YXWmrE

The problem is:
When using bigger font-size. The layout abnormal.
Or I missed something?

**Comment by OlegKi** [comment]
First of all you use **wrong CSS** in your demo. You use CSS from jqGrid 4.8 with the code from jqGrid 4.9. Seconds I still don't understand your problem. It's clear that you have to made **much more** changes in CSS to increase the font-size. There are a lot of other settings (pagging, margin, height and so on) which needed be adjusted too.

**Comment by mrjumpy** [comment]
I'm tried to change the font-size.
But when the font-size increase.(in Dev Console, 20px -> 80px, etc)
The layout format looks error. 

Because I'm using `thead th` to tune the font-size through javascript directly in my project.
So the DEMO is normal. But my project not.

you can tried to render the font-size and increase it in the dev console.
After the jqGrid rendered complete.
And, you'll understand what errors that I'm talking about.

Sorry for my poor expression.
I made a DEMO. Hope you can understand well.
http://codepen.io/mrjumpy/pen/YXWmrE

If this is not a issue please let me know.

**Comment by OlegKi** [comment]
Sorry, but I see no sense in the last demo. It just increases the font size every second. I have no idea what you want to demonstrates with the demo. You can just 

The question seems me absolutely independent from jqPivot. You can just create any jqGrid and try to change the font size of the header or of the body of the grid. It's not so easy. First of all you should examine [ui.jqgrid.css](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0/css/ui.jqgrid.css). It contains some `font-size` settings and **many `padding`, `margin` and `height` values. Some from the `padding`, `margin` and `height` values should be changed too it you increase the font-size.

So changing of `font-size` of jqGrid is not so easy. You can do this, but it should be *many* CSS rules which overwrite the rules from `ui.jqgrid.css`. It's not so easy, but it's not too complex. The current implementation of jqGrid *don't allow* you to increase the font size just by setting of one css rule for `thead th`.

I'm not sure what your exact requirements, but you can try to add the CSS rule
```css
body {
    zoom: 200%;
}
```
and to see how the page will look like on opening.

**Comment by mrjumpy** [comment]
I mean the layout was wrong.

![2015-06-15 10 46 02](https://cloud.githubusercontent.com/assets/8980713/8162547/94c7ddac-13b0-11e5-8861-e5bab2d5ee5a.png)

Thank you for your advise I'll give a try.
It seems this is not a issue. So I closed.
