### ISSUE TITLE
afterInsertRow not fired after migrating to 4.9

### ISSUE THREAD

**Issue by ryanlin1986** [free-jqgrid/jqGrid#96]
Seems a break change not mentioned in the update readm-me.
I figured it out by change it to afterAddRow, works but the parameters now encapsulated into one parameter.
I'm not sure this is correct work-around. Can you please give me some advice?

**Comment by OlegKi** [comment]
The old version used **one** callback `afterInsertRow` in two different situations: filling the grid (inserting of multiple rows at once in `addXmlData` and `addJSONData`) and during manual adding one row of data by `addRowData` method.

The callback `afterInsertRow` will be called now only inside of `readInput` which is replacement of old `addXmlData` and `addJSONData`.

The methods `setRowData`, `delRowData` and `addRowData` calls now `afterSetRow`, `afterDelRow` and `afterAddRow` callbacks.

I try to hold one common rule in all new callbacks: all parameters are filled as *properties of one callback parameter* `options`, if one need to have more as one parameter. For example `afterDelRow` have only one parameter `rowid`, so it will be used directly as the only parameter of `afterDelRow`. Forwarding complex parameters as option allows to make the code more extensible: one can add additional property in the next release without breaking upwards compatibility. Moreover one can forward many optional information which will be used not by all the callback, but one will don't declare many too many unused parameters.

The callbacks `afterSetRow` and `afterAddRow` could need more information. So the information are saved as properties of one `options` parameter. The properties of `afterAddRow` which you need are the following: `rowid`, `inputData`, `position`, `srcRowid`, `iRow`, `localData`, `iData`. The property of `afterSetRow` are: `rowid`, `inputData`, `iData`, `iRow`, `tr`, `localData`, `cssProp`.

I didn't find time till now to write the corresponding documentation, but I reformatted the code of jqGrid and made many renaming of local variables to make the code more readable. The code is still far to be perfect, but I hope that you could look through [the code](https://github.com/free-jqgrid/jqGrid/blob/v4.9.0/js/grid.base.js#L5486-L5637) of `addRowData` method and understand the exact meaning of all the properties of the only `option` parameter of the `afterAddRow` callback.

**Comment by ryanlin1986** [comment]
Thanks for the great explanation, :+1:
