### ISSUE TITLE
treegrid changes in 4.9.0

### ISSUE THREAD

**Issue by john-w-watson** [free-jqgrid/jqGrid#98]
Hi Oleg - I have an existing treegrid that works in 4.8.0.  Do you have any examples of what I need to change to get my treegrid working in 4.9.0?  I saw the note regarding "additionalProperties", but I don't understand exactly what I need to change.  I'm using datatype set to a function, and use addJSONData to load the data into the grid.

**Comment by john-w-watson** [comment]
It looks like the issue has to do with how a reader gets specified if datatype is set to a function.  In 4.8, addJSONData defaults to using a jsonReader if datatype is not "local".  In 4.9, addJSONData is really readInput which doesn't end up setting a reader if datatype is a function.

**Comment by OlegKi** [comment]
Hi John,

Could you provide the demo which demonstrates what you do and how you do? It's difficult to read about the problem without seeing the JavaScript code and without any test data which you use for filling the grid.

**Comment by john-w-watson** [comment]
I haven't changed anything in the data I'm passing to addJSONData.  I've debugged both 4.8 and 4.9 to see why there's a difference in behavior.  In 4.8, the dedicated addJSONData method only looked for datatype === "local" - if not "local", it used a jsonReader which worked fine with datatype = function because I'm sending it a javascript object.  In 4.9, addJSONData is set to readInput which doesn't default to a jsonReader (or any other reader) because it doesn't know if the user is calling addJSONData or addXMLData, etc.  So when datatype = function, no reader gets set, so no data gets loaded.  Perhaps instead of setting addJSONData = readInput, addJSONData could be it's own function that calls readInput, passing it a parameter that would let readInput know it should default to a jsonReader if datatype is a function.

**Comment by OlegKi** [comment]
Sorry, but I can only repeat: **Could you provide the demo which demonstrates what you do and how you do?** I suppose that you have really minor issue and the problem could be solve very easy, but I have to see the code which you use and to know the format of input data. I have no idea why you use datatype as function, but to gives you any tips I really have to know details about what you do and how you do.

**Comment by john-w-watson** [comment]
Please look at the code I've mentioned above.  There is an obvious change that has been made to how addJSONData works in 4.9.  This change causes addJSONData to not load ANY data when datatype is set to a function.  It doesn't matter what data I'm passing because the data is completely ignored.

Here is the code from addJSONData in 4.8:

if (p.datatype === "local") {
	dReader = p.localReader;
	frd = "local";
} else {
	dReader = p.jsonReader;
	frd = "json";
}

As you can see, if datatype is a function, dReader will be set to p.jsonReader.

Here is the code from readInput in 4.9:

switch (datatype) {
	case "xml":
	case "xmlstring":
		dataReader = p.xmlReader;
		fieldReader = jgrid.getXmlData;
		break;
	case "json":
	case "jsonp":
	case "jsonstring":
		dataReader = p.jsonReader;
		break;
	default:
		break;
}

As you can see, if datatype is set to a function, then dataReader does not get set to p.jsonReader.  I've suggested a fix above, but obviously you're in a better position to decide the best way to deal with this regression.

**Comment by OlegKi** [comment]
I know the code of free jqGrid 4.8 and free jqGrid 4.9, but you don't posted **your code** although I asked you multiple time about it. Do you want to say that the code of free jqGrid 4.9 is not 100% compatible with the code of free jqGrid 4.8? I agree. It's true for almost all deep changes in the code. Do you want to find the solution of your problem? You have to make small changes in your existing code, but which one I can't say you because I have no idea what you do currently. You should not use `addJSONData`, `addXMLData` or any other **internal** methods to load the data. I suppose you can use `datatype: "jsonstring"` or `datatype: "local"` to load the data in TreeGrid instead. It's the standard way.

**Comment by john-w-watson** [comment]
I have to question why addJSONData is documented as a jqGrid method if we're not supposed to use it.  Is there another way to put data in the grid from a function?  I've noticed you often tell people not to use datatype = function.  Are you saying this is not something you support?  Again, it's part of the documented API.

The function I use constructs the JSON data on the client.  The code then simply calls addJSONData passing it the constructed javascript object.  This worked great at 4.8 except for the minor bug where jqGrid was trying to get the lowercase value of datatype.

Here is what the data looks like:

{
page: 1,
rows: [
{Key: "106322-010| | ", level: 0, parent: "", BaselineLabBill: 0, ...},
{Key: "106322-010|1PD| ", level: 1, parent: "106322-010| | ", BaselineLabBill: 0, ...},
{Key: "106322-010|1PD|COD", level: 2, parent: "106322-010|1PD| ", BaselineLabBill: 0, ...},
...
]
}

**Comment by OlegKi** [comment]
It seems to my that you have absolutely standard situation and you should just use `datatype: "jsonstring", datastr: mydata` where object `mydata` is your data or the array which you use as the value of `rows` property. It should solve your problem. See [the old demo](http://www.ok-soft-gmbh.com/jqGrid/OK/LocalAdjacencyTree.htm) as an example. I see no reason to use `datatype` as function in the way.

The only way why the feature `datatype` as function exist is loading of data from the server by some non-standard protocol, for example by WebSocket. The typical examples of usage `datatype` as function was the usage in absolutely another case and the usage was in 99% wrong. It broken many features of jqGrid by such wrong implementation. For example the `datatype` as function **must** calls some callbacks and trigger some events which used other parts of jqGrid and your code probably too. . You can find an example of the simplest implementation of `datatype` as function in [the answer](http://stackoverflow.com/a/7455157/315935) written almost 4 years ago. Since the time jqGrid become more complex and the callback `datatype` contains 5 parameters since a long time. All examples of the usage `datatype` as function was incorrect implementation which can be easy replaced with more standard and simple code.

**Comment by john-w-watson** [comment]
I've been trying to keep things simple so we could stay focused on the difference in behavior between 4.8 and 4.9.  Let's take a step back.  I'm going to describe our requirements, and you can advise us as to how we should be using jqGrid to implement them.

We have an existing application environment built on top of can.js.  We have existing can.js models we want to use for all data retrieval and to save any changes.  We're evaluating jqGrid to determine if we can replace an existing grid controller with something we don't have to maintain ourselves so we can concentrate our efforts on application development.

The new application we're adding to our product primarily consists of a grid.  The grid has three horizontal sections that can be scrolled independently (we've done this in the past by creating three side-by-side grids and synchronizing their vertical scrolling).  This outer grid is a treegrid.  The design calls for the left-most section to include the tree column that's used to expand/collapse the tree nodes.  The other sections would need to be expanded/collapsed in sync without a visible tree column.  Each leaf node within the outer grid needs to appear to be expandable, and when the user expands those leaf nodes, we need to retrieve additional data from a separate model, and then create embedded content under the leaf node that consists of another three section treegrid as well as additional UI components outside the grid used to control a number of application behaviors.

During our evaluation we've been handling this using datatype = function so we could intercept the outer grid's leaf-node data request, call the other model's retrieval method, insert a dummy row within the outer tree using addJSONData so that jqGrid will add it to the tree correctly, and then replacing the dummy row's content with a single td that has a large colspan and a container div that then allows us to add an arbitrary amount of content within the outer grid that will behave correctly when the outer grid's row is expanded or collapsed.  We then construct the inner treegrid and the rest of the embedded UI, and use addJSONData to add the data from the second model to the inner grid.

How would you advise us to build the application I've described using jqGrid?

**Comment by OlegKi** [comment]
Sorry, but you still didn't included any **examples**. What kind of data you try to display? **The most simple would be to include 2-3 item of test data**, which build the tree node and the three horizontal sections like you display the data currently. Some information about the quantity of data are required too. You should understand that the implementation with 500000 rows and 160 columns should be absolutely another task as the grid with 500 rows and 10 columns.

Sorry, but nothing from above part provide for me any tips why you choose datatype as function and why you could be need to use `addJSONData`. All input information looks for me like a simple array with items. Some properties of the items are objects with complex properties like another arrays or objects. So you can just use TreeGrid/Subgrid/jqGrid with `datatype: "local"` or `datatype: "jsonstring"`. In case of usage `datatype: "jsonstring"` you need just include additional option `additionalProperties: [...]` with array of "complex" properties. All the data will be saved locally in `data` of the TreeGrid/Subgrid/Grid. You can use `getLocalRow` to access the full information about the row. Look at [the answer](http://stackoverflow.com/a/13241406/315935) or [this one](http://stackoverflow.com/a/14205263/315935) provides examples which uses subgrids to display hierarchical data. One can use different variation of the same idea. One can hold the main data set in other form.

From the information which you post before it's unclear for me whether it would be better to use TreeGrid or Subgrid or Grouping. I don't think that we can go forward without any **real example with at least 2-3 item of data and some pictures** which shows how you represent the data currently in TreeGrid/Grids. Could you post the corresponding examples?

**Comment by OlegKi** [comment]
It seems that the old issue can be closed. You can reopen it any time later, but please post more details (the demo or at least JavaScript code with simple test data), so that I could reproduce the problem.
